import { createApi } from "@reduxjs/toolkit/query/react";

import { baseQueryWithReauth } from "./base-query-with-reauth";

export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Auth",
    "Session",
    "Job",
    "JobStatistics",
    "JobApplication",
    "Profile",
    "ProfileStats",
    "Lead",
    "LeadStatistics",
    "User",
    "Queue",
    "File",
    "DocumentTemplate",
    "DocumentIssue",
    "Blog",
    "BlogCategory",
    "Course",
    "CourseCategory",
    "Video",
    "ServicePage",
    "Role",
    "Security",
    "EmailTemplate",
    "EmailCampaign",
    "EmailSuppression",
    "ExternalApplication",
    "DeveloperProject",
    "DeveloperTask",
    "DeveloperMessage",
    "DeveloperNotification",
    "Workspace",
    "ProductOverview",
    "ProductProject",
    "ProductUsers",
    "ProductSprint",
    "ProductTask",
    "ProductActivity",
    "ProductTimeline",
    "ProductRelease",
    "ProductDelivery",
    "ProductReport",
    "ProductNotification",
    "ProductChat",
    "HROverview",
    "HREmployee",
    "HRAttendance",
    "HRLeave",
    "HRPayroll",
    "HRPerformance",
    "HROnboarding",
    "HRAsset",
    "HRShift",
    "HRAnnouncement",
    "HRReport",
    "HRHoliday",
    "HRTimesheet",
    "HRExpense",
    "HRCase",
    "HRPolicy",
    "HROperations",
    "HRInterview",
    "HRSchedule",
  ],
  refetchOnFocus: true,
  refetchOnReconnect: true,
  endpoints: () => ({}),
});
