"use client";
import {useMemo,useState,type FormEvent} from "react";
import {Laptop,PackageCheck,Plus,RotateCcw,Wrench} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useGetHRAssetsQuery,useGetHREmployeesQuery,useSaveHRAssetMutation,useUpdateHRAssetMutation} from "@/src/lib/features/hr-management/hr-management-api";
import type {HRAsset} from "@/src/lib/features/hr-management/hr-management-types";
import {Badge,Card,CardHeader,ColorButton,Empty,ErrorBox,Field,HRPageTitle,Metric,PrimaryButton,SecondaryButton,fmtDate,idOf,input,personName} from "./hr-ui";
const base={assetTag:"",type:"Laptop",name:"",serialNumber:"",employeeId:"",status:"available",purchaseDate:"",notes:""};
export function HRAssetsWorkspace(){const [show,setShow]=useState(false);const [form,setForm]=useState(base);const [search,setSearch]=useState("");const [error,setError]=useState("");const [feedback,setFeedback]=useState("");const q=useGetHRAssetsQuery({page:1,limit:200,search:search||undefined});const employees=useGetHREmployeesQuery({page:1,limit:200});const [save,state]=useSaveHRAssetMutation();const [update]=useUpdateHRAssetMutation();const rows=q.data?.data??[];const stats=useMemo(()=>({assigned:rows.filter(r=>r.status==="assigned").length,available:rows.filter(r=>r.status==="available").length,repair:rows.filter(r=>r.status==="repair").length}),[rows]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await save({...form,employeeId:form.employeeId||undefined,purchaseDate:form.purchaseDate||undefined,status:form.employeeId?"assigned":form.status}).unwrap();setFeedback("Asset saved.");setShow(false);setForm(base)}catch(x){setError(getApiErrorMessage(x))}}
 async function change(asset:HRAsset,status:string){let employeeId:string|undefined;if(status==="assigned"){employeeId=window.prompt("Employee id to assign this asset to:")||undefined;if(!employeeId)return}try{await update({id:idOf(asset),body:{status,...(employeeId?{employeeId}:{})}}).unwrap();setFeedback(`Asset marked ${status}.`)}catch(x){setError(getApiErrorMessage(x))}}
 return <><HRPageTitle eyebrow="Employee Asset Management" title="Assignment, recovery and" accent="asset lifecycle." description="Track laptops, devices, access equipment and other company assets by asset tag, serial number and employee assignment. Manage available, assigned, repair, lost and retired states." actions={<ColorButton onClick={()=>setShow(v=>!v)}><Plus className="h-4 w-4"/>Add asset</ColorButton>}/>{error&&<ErrorBox message={error}/>} {feedback&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{feedback}</div>}
 {show&&<Card className="mb-6"><CardHeader title="Create / assign asset" description="If an employee is selected, the asset is immediately marked assigned."/><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Asset tag"><input required value={form.assetTag} onChange={e=>setForm({...form,assetTag:e.target.value})} className={input} placeholder="QF-LAP-001"/></Field><Field label="Asset type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className={input}><option>Laptop</option><option>Desktop</option><option>Monitor</option><option>Mobile</option><option>SIM</option><option>Access Card</option><option>Headset</option><option>Furniture</option><option>Other</option></select></Field><Field label="Name / model"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={input} placeholder="MacBook Pro 14"/></Field><Field label="Serial number"><input value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})} className={input}/></Field><Field label="Assign to employee"><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className={input}><option value="">Keep available</option>{employees.data?.data.map(e=><option key={idOf(e)} value={idOf(e)}>{e.employeeCode} · {e.firstName} {e.lastName}</option>)}</select></Field><Field label="Purchase date"><input type="date" value={form.purchaseDate} onChange={e=>setForm({...form,purchaseDate:e.target.value})} className={input}/></Field><div className="md:col-span-2"><Field label="Notes"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className={input}/></Field></div><div className="md:col-span-2 xl:col-span-4 flex justify-end"><PrimaryButton type="submit" disabled={state.isLoading}>Save asset</PrimaryButton></div></form></Card>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Assigned assets" value={stats.assigned} helper="Currently allocated" icon={<Laptop className="h-5 w-5"/>} gradient="from-blue-500 to-violet-500"/><Metric label="Available assets" value={stats.available} helper="Ready for assignment" icon={<PackageCheck className="h-5 w-5"/>} gradient="from-emerald-500 to-teal-500"/><Metric label="Under repair" value={stats.repair} helper="Needs follow-up" icon={<Wrench className="h-5 w-5"/>} gradient="from-amber-500 to-orange-500"/></div>
 <Card className="mt-6"><CardHeader title="Asset register" description={`${q.data?.pagination.total??0} asset(s)`} action={<input value={search} onChange={e=>setSearch(e.target.value)} className={`${input} w-56`} placeholder="Search tag, serial, model…"/>}/>{q.isLoading?<p className="p-6 text-sm text-slate-400">Loading assets…</p>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Asset</th><th className="px-4 py-3">Serial</th><th className="px-4 py-3">Assigned employee</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Assigned</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(a=><tr key={idOf(a)}><td className="px-5 py-4"><b className="text-slate-800">{a.name}</b><p className="mt-1 text-xs text-slate-400">{a.assetTag} · {a.type}</p></td><td className="px-4 py-4 text-xs text-slate-500">{a.serialNumber||"—"}</td><td className="px-4 py-4 text-xs text-slate-600">{a.employeeId?personName(a.employeeId):"Unassigned"}</td><td className="px-4 py-4"><Badge tone={a.status==="assigned"?"blue":a.status==="available"?"green":a.status==="repair"?"amber":a.status==="lost"?"rose":"slate"}>{a.status}</Badge></td><td className="px-4 py-4 text-xs text-slate-400">{fmtDate(a.assignedAt)}</td><td className="px-5 py-4"><div className="flex justify-end gap-2">{a.status==="assigned"&&<SecondaryButton onClick={()=>void change(a,"available")}><RotateCcw className="h-3.5 w-3.5"/>Return</SecondaryButton>}{a.status==="available"&&<SecondaryButton onClick={()=>void change(a,"repair")}>Repair</SecondaryButton>}{a.status==="repair"&&<SecondaryButton onClick={()=>void change(a,"available")}>Ready</SecondaryButton>}</div></td></tr>)}</tbody></table></div>:<Empty title="No assets" description="Add company assets and optionally assign them to employees."/>}</Card>
 </>}
