"use client";
import {useMemo,useState,type FormEvent} from "react";
import {Check,ClipboardCheck,Plus,X} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useCreateHRLeaveMutation,useDecideHRLeaveMutation,useGetHREmployeesQuery,useGetHRLeavesQuery} from "@/src/lib/features/hr-management/hr-management-api";
import {Badge,Card,CardHeader,ColorButton,Empty,ErrorBox,Field,HRPageTitle,Metric,PrimaryButton,SecondaryButton,fmtDate,idOf,input,personName} from "./hr-ui";
const today=new Date().toISOString().slice(0,10);
export function HRLeaveWorkspace(){const [filter,setFilter]=useState("");const [show,setShow]=useState(false);const [form,setForm]=useState({employeeId:"",leaveType:"Casual Leave",startDate:today,endDate:today,days:1,reason:""});const [feedback,setFeedback]=useState("");const [error,setError]=useState("");const q=useGetHRLeavesQuery({page:1,limit:200,status:filter||undefined});const employees=useGetHREmployeesQuery({page:1,limit:200});const [create,state]=useCreateHRLeaveMutation();const [decide,decisionState]=useDecideHRLeaveMutation();const rows=q.data?.data??[];const stats=useMemo(()=>({pending:rows.filter(r=>r.status==="pending").length,approved:rows.filter(r=>r.status==="approved").length,days:rows.filter(r=>r.status==="approved").reduce((s,r)=>s+r.days,0)}),[rows]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await create(form).unwrap();setFeedback("Leave request created.");setShow(false);setForm({...form,employeeId:"",reason:""})}catch(x){setError(getApiErrorMessage(x))}}
 async function decision(id:string,status:"approved"|"rejected"){const note=window.prompt(status==="rejected"?"Rejection reason (recommended):":"Approval note (optional):")??undefined;try{await decide({id,status,note:note||undefined}).unwrap();setFeedback(`Leave ${status}.`)}catch(x){setError(getApiErrorMessage(x))}}
 return <><HRPageTitle eyebrow="Leave Management" title="Requests, approvals and" accent="leave decisions." description="Create employee leave requests, review pending items and record approval or rejection decisions with notes. Employee-linked accounts can also submit leave through the HR self-service API." actions={<ColorButton onClick={()=>setShow(v=>!v)}><Plus className="h-4 w-4"/>New leave request</ColorButton>}/>{error&&<ErrorBox message={error}/>} {feedback&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{feedback}</div>}
 {show&&<Card className="mb-6"><CardHeader title="Create leave request" description="Use this for HR-entered requests or corrections. Employees can submit their own requests when linked to an HR employee record."/><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-6"><Field label="Employee"><select required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className={input}><option value="">Select employee</option>{employees.data?.data.map(e=><option key={idOf(e)} value={idOf(e)}>{e.employeeCode} · {e.firstName} {e.lastName}</option>)}</select></Field><Field label="Leave type"><select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})} className={input}><option>Casual Leave</option><option>Sick Leave</option><option>Earned Leave</option><option>Maternity Leave</option><option>Paternity Leave</option><option>Comp Off</option><option>Unpaid Leave</option><option>Bereavement Leave</option><option>Other</option></select></Field><Field label="From"><input type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} className={input}/></Field><Field label="To"><input type="date" required value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} className={input}/></Field><Field label="Days"><input type="number" min="0.5" step="0.5" required value={form.days} onChange={e=>setForm({...form,days:Number(e.target.value)})} className={input}/></Field><div className="md:col-span-2 xl:col-span-1 flex items-end"><PrimaryButton type="submit" disabled={state.isLoading} className="w-full">Create request</PrimaryButton></div><div className="md:col-span-2 xl:col-span-6"><Field label="Reason"><textarea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} className={`${input} min-h-24 py-3`}/></Field></div></form></Card>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Pending approvals" value={stats.pending} helper="Requires HR / manager decision" icon={<ClipboardCheck className="h-5 w-5"/>} gradient="from-amber-500 to-orange-500"/><Metric label="Approved requests" value={stats.approved} helper="In current result set" icon={<Check className="h-5 w-5"/>} gradient="from-emerald-500 to-teal-500"/><Metric label="Approved leave days" value={stats.days} helper="Total approved days shown" icon={<ClipboardCheck className="h-5 w-5"/>} gradient="from-blue-500 to-violet-500"/></div>
 <Card className="mt-6"><CardHeader title="Leave register" description={`${q.data?.pagination.total??0} request(s)`} action={<select value={filter} onChange={e=>setFilter(e.target.value)} className={`${input} w-40`}><option value="">All status</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select>}/>{q.isLoading?<p className="p-6 text-sm text-slate-400">Loading leave requests…</p>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Employee</th><th className="px-4 py-3">Leave</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Days</th><th className="px-4 py-3">Reason / decision</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Decision</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={idOf(r)}><td className="px-5 py-4"><b className="text-slate-800">{personName(r.employeeId)}</b>{typeof r.employeeId==="object"&&<p className="mt-1 text-xs text-slate-400">{r.employeeId.employeeCode} · {r.employeeId.department}</p>}</td><td className="px-4 py-4 text-xs font-bold text-slate-600">{r.leaveType}</td><td className="px-4 py-4 text-xs text-slate-500">{fmtDate(r.startDate)} → {fmtDate(r.endDate)}</td><td className="px-4 py-4 text-xs font-black text-slate-700">{r.days}</td><td className="max-w-sm px-4 py-4 text-xs text-slate-500"><p className="line-clamp-2">{r.reason}</p>{r.decisionNote&&<p className="mt-1 font-semibold text-slate-400">Decision: {r.decisionNote}</p>}</td><td className="px-4 py-4"><Badge tone={r.status==="approved"?"green":r.status==="pending"?"amber":r.status==="rejected"?"rose":"slate"}>{r.status}</Badge></td><td className="px-5 py-4">{r.status==="pending"?<div className="flex justify-end gap-2"><SecondaryButton disabled={decisionState.isLoading} onClick={()=>void decision(idOf(r),"approved")}><Check className="h-3.5 w-3.5"/>Approve</SecondaryButton><SecondaryButton disabled={decisionState.isLoading} onClick={()=>void decision(idOf(r),"rejected")}><X className="h-3.5 w-3.5"/>Reject</SecondaryButton></div>:<span className="block text-right text-xs text-slate-400">Decided</span>}</td></tr>)}</tbody></table></div>:<Empty title="No leave requests" description="No requests match this status filter."/>}</Card>
 </>}
