"use client";
import {useMemo,useState} from "react";
import {CheckCircle2,CircleDashed,ClipboardList,UserRoundPlus} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useGetHROnboardingQuery,useSaveHROnboardingMutation} from "@/src/lib/features/hr-management/hr-management-api";
import type {HROnboarding} from "@/src/lib/features/hr-management/hr-management-types";
import {Badge,Card,CardHeader,Empty,ErrorBox,HRPageTitle,Metric,SecondaryButton,idOf,personName} from "./hr-ui";
function employeeIdOf(v:HROnboarding){return typeof v.employeeId==="string"?v.employeeId:idOf(v.employeeId)}
export function HROnboardingWorkspace(){const q=useGetHROnboardingQuery({page:1,limit:200});const [save,state]=useSaveHROnboardingMutation();const [feedback,setFeedback]=useState("");const [error,setError]=useState("");const rows=q.data?.data??[];const stats=useMemo(()=>({active:rows.filter(r=>r.status==="in-progress"||r.status==="not-started").length,completed:rows.filter(r=>r.status==="completed").length,blocked:rows.filter(r=>r.status==="blocked").length}),[rows]);
 async function updateTask(record:HROnboarding,index:number,next:string){setError("");const tasks=record.tasks.map((t,i)=>i===index?{...t,status:next}:t);try{await save({employeeId:employeeIdOf(record),status:record.status,buddyEmployeeId:typeof record.buddyEmployeeId==="string"?record.buddyEmployeeId:idOf(record.buddyEmployeeId),tasks,startedAt:record.startedAt,completedAt:record.completedAt}).unwrap();setFeedback("Onboarding checklist updated.")}catch(x){setError(getApiErrorMessage(x))}}
 return <><HRPageTitle eyebrow="Onboarding & Offboarding" title="Joiner readiness and" accent="task ownership." description="Every new employee receives a default onboarding checklist for HR documents, payroll/statutory setup, reporting manager, assets, IT/security induction, policy induction and manager check-in. Update each step as work is completed."/>{error&&<ErrorBox message={error}/>} {feedback&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{feedback}</div>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Active onboarding" value={stats.active} helper="Not started or in progress" icon={<UserRoundPlus className="h-5 w-5"/>} gradient="from-indigo-500 to-violet-500"/><Metric label="Completed" value={stats.completed} helper="All onboarding steps complete" icon={<CheckCircle2 className="h-5 w-5"/>} gradient="from-emerald-500 to-teal-500"/><Metric label="Blocked" value={stats.blocked} helper="Requires intervention" icon={<CircleDashed className="h-5 w-5"/>} gradient="from-rose-500 to-orange-500"/></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-2">{q.isLoading?<Card className="p-8 text-sm text-slate-400">Loading onboarding records…</Card>:rows.length?rows.map(record=>{const done=record.tasks.filter(t=>t.status==="completed").length;const pct=record.tasks.length?Math.round(done/record.tasks.length*100):0;return <Card key={idOf(record)}><CardHeader title={personName(record.employeeId)} description={`${done}/${record.tasks.length} tasks complete`} action={<Badge tone={record.status==="completed"?"green":record.status==="blocked"?"rose":record.status==="in-progress"?"blue":"slate"}>{record.status}</Badge>}/><div className="px-5 pt-5"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 via-violet-500 to-emerald-500" style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between text-[10px] font-bold text-slate-400"><span>{pct}% complete</span><span>{typeof record.employeeId==="object"?record.employeeId.department:""}</span></div></div><div className="divide-y divide-slate-100 px-5 py-3">{record.tasks.map((task,index)=><div key={task._id??`${task.title}-${index}`} className="flex items-start gap-3 py-3"><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg ${task.status==="completed"?"bg-emerald-50 text-emerald-600":task.status==="blocked"?"bg-rose-50 text-rose-600":"bg-slate-100 text-slate-500"}`}><ClipboardList className="h-3.5 w-3.5"/></span><div className="min-w-0 flex-1"><p className="text-xs font-black text-slate-700">{task.title}</p>{task.owner&&<p className="mt-1 text-[10px] text-slate-400">Owner: {task.owner}</p>}</div><select disabled={state.isLoading} value={task.status} onChange={e=>void updateTask(record,index,e.target.value)} className="h-8 rounded-lg border border-slate-200 bg-white px-2 text-[10px] font-black text-slate-600"><option value="pending">Pending</option><option value="in-progress">In progress</option><option value="completed">Completed</option><option value="blocked">Blocked</option></select></div>)}</div></Card>}):<Card className="xl:col-span-2"><Empty title="No onboarding records" description="Creating an employee automatically creates the default onboarding checklist."/></Card>}</div>
 <Card className="mt-6"><CardHeader title="Recommended offboarding flow" description="Use Employee Management + Documents + Assets to complete leaver processing."/><div className="grid gap-3 p-5 md:grid-cols-4">{["Record notice / exit date","Recover assigned assets and access","Issue relieving / experience documents","Mark final employee status as exited"].map((x,i)=><div key={x} className="rounded-xl bg-slate-50 p-4"><span className="text-[10px] font-black text-violet-600">STEP {i+1}</span><p className="mt-2 text-xs font-bold leading-5 text-slate-700">{x}</p></div>)}</div></Card>
 </>}
