"use client";
import {useMemo,useState,type FormEvent} from "react";
import {BadgeIndianRupee,Banknote,CheckCircle2,Plus} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useGetHREmployeesQuery,useGetHRPayrollQuery,useSaveHRPayrollMutation} from "@/src/lib/features/hr-management/hr-management-api";
import {Badge,Card,CardHeader,ColorButton,Empty,ErrorBox,Field,HRPageTitle,Metric,PrimaryButton,fmtDate,idOf,input,money,personName} from "./hr-ui";
const period=new Date().toISOString().slice(0,7);
const baseForm={employeeId:"",period,currency:"INR",baseSalary:0,allowances:0,bonus:0,reimbursements:0,deductions:0,tax:0,status:"draft",paymentReference:"",notes:""};
export function HRPayrollWorkspace(){const [filterPeriod,setFilterPeriod]=useState(period);const [show,setShow]=useState(false);const [form,setForm]=useState(baseForm);const [error,setError]=useState("");const [feedback,setFeedback]=useState("");const q=useGetHRPayrollQuery({page:1,limit:200,period:filterPeriod||undefined});const employees=useGetHREmployeesQuery({page:1,limit:200});const [save,state]=useSaveHRPayrollMutation();const rows=q.data?.data??[];const net=Math.max(0,form.baseSalary+form.allowances+form.bonus+form.reimbursements-form.deductions-form.tax);const totals=useMemo(()=>({net:rows.reduce((s,r)=>s+r.netPay,0),paid:rows.filter(r=>r.status==="paid").reduce((s,r)=>s+r.netPay,0),pending:rows.filter(r=>r.status!=="paid").length}),[rows]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await save({...form,netPay:net}).unwrap();setFeedback("Payroll record saved.");setShow(false);setForm({...baseForm,period:filterPeriod||period})}catch(x){setError(getApiErrorMessage(x))}}
 return <><HRPageTitle eyebrow="Payroll Management" title="Monthly earnings, deductions and" accent="payment status." description="Maintain payroll records per employee and period, including base salary, allowances, bonus, reimbursements, deductions, tax and computed net pay. Track draft, approved, hold and paid states." actions={<ColorButton onClick={()=>setShow(v=>!v)}><Plus className="h-4 w-4"/>Payroll entry</ColorButton>}/>{error&&<ErrorBox message={error}/>} {feedback&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{feedback}</div>}
 {show&&<Card className="mb-6"><CardHeader title="Create / update payroll" description="Saving the same employee and month updates the existing payroll record."/><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-5"><Field label="Employee"><select required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className={input}><option value="">Select employee</option>{employees.data?.data.map(e=><option key={idOf(e)} value={idOf(e)}>{e.employeeCode} · {e.firstName} {e.lastName}</option>)}</select></Field><Field label="Period"><input type="month" required value={form.period} onChange={e=>setForm({...form,period:e.target.value})} className={input}/></Field><Field label="Base salary"><input type="number" min={0} value={form.baseSalary} onChange={e=>setForm({...form,baseSalary:Number(e.target.value)})} className={input}/></Field><Field label="Allowances"><input type="number" min={0} value={form.allowances} onChange={e=>setForm({...form,allowances:Number(e.target.value)})} className={input}/></Field><Field label="Bonus"><input type="number" min={0} value={form.bonus} onChange={e=>setForm({...form,bonus:Number(e.target.value)})} className={input}/></Field><Field label="Reimbursements"><input type="number" min={0} value={form.reimbursements} onChange={e=>setForm({...form,reimbursements:Number(e.target.value)})} className={input}/></Field><Field label="Deductions"><input type="number" min={0} value={form.deductions} onChange={e=>setForm({...form,deductions:Number(e.target.value)})} className={input}/></Field><Field label="Tax"><input type="number" min={0} value={form.tax} onChange={e=>setForm({...form,tax:Number(e.target.value)})} className={input}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={input}><option value="draft">Draft</option><option value="approved">Approved</option><option value="hold">Hold</option><option value="paid">Paid</option></select></Field><Field label="Payment reference"><input value={form.paymentReference} onChange={e=>setForm({...form,paymentReference:e.target.value})} className={input}/></Field><div className="md:col-span-2 xl:col-span-4"><Field label="Notes"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className={input}/></Field></div><div className="rounded-xl bg-gradient-to-br from-emerald-50 to-teal-50 p-4"><p className="text-[10px] font-black uppercase tracking-wide text-emerald-600">Calculated net pay</p><p className="mt-2 text-xl font-black text-emerald-900">{money(net,form.currency)}</p></div><div className="md:col-span-2 xl:col-span-5 flex justify-end"><PrimaryButton type="submit" disabled={state.isLoading}>{state.isLoading?"Saving…":"Save payroll"}</PrimaryButton></div></form></Card>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Net payroll" value={money(totals.net)} helper={filterPeriod} icon={<BadgeIndianRupee className="h-5 w-5"/>} gradient="from-emerald-500 to-teal-500"/><Metric label="Paid amount" value={money(totals.paid)} helper={`${rows.filter(r=>r.status==="paid").length} payroll record(s) paid`} icon={<CheckCircle2 className="h-5 w-5"/>} gradient="from-blue-500 to-cyan-500"/><Metric label="Pending records" value={totals.pending} helper="Draft, approved or on hold" icon={<Banknote className="h-5 w-5"/>} gradient="from-amber-500 to-orange-500"/></div>
 <Card className="mt-6"><CardHeader title="Payroll register" description={`${q.data?.pagination.total??0} record(s)`} action={<input type="month" value={filterPeriod} onChange={e=>setFilterPeriod(e.target.value)} className={`${input} w-40`}/>} />{q.isLoading?<p className="p-6 text-sm text-slate-400">Loading payroll…</p>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Employee</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Base</th><th className="px-4 py-3">Earnings</th><th className="px-4 py-3">Deductions + tax</th><th className="px-4 py-3">Net pay</th><th className="px-4 py-3">Status</th><th className="px-5 py-3">Payment</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={idOf(r)}><td className="px-5 py-4"><b className="text-slate-800">{personName(r.employeeId)}</b>{typeof r.employeeId==="object"&&<p className="mt-1 text-xs text-slate-400">{r.employeeId.employeeCode} · {r.employeeId.department}</p>}</td><td className="px-4 py-4 text-xs font-bold text-slate-600">{r.period}</td><td className="px-4 py-4 text-xs text-slate-600">{money(r.baseSalary,r.currency)}</td><td className="px-4 py-4 text-xs text-emerald-700">+ {money(r.allowances+r.bonus+r.reimbursements,r.currency)}</td><td className="px-4 py-4 text-xs text-rose-600">- {money(r.deductions+r.tax,r.currency)}</td><td className="px-4 py-4 font-black text-slate-900">{money(r.netPay,r.currency)}</td><td className="px-4 py-4"><Badge tone={r.status==="paid"?"green":r.status==="approved"?"blue":r.status==="hold"?"rose":"amber"}>{r.status}</Badge></td><td className="px-5 py-4 text-xs text-slate-400">{r.paymentReference||"—"}{r.paidAt&&<p className="mt-1">{fmtDate(r.paidAt)}</p>}</td></tr>)}</tbody></table></div>:<Empty title="No payroll records" description="Add payroll entries for this period."/>}</Card>
 </>}
