"use client";
import {useMemo,useState,type FormEvent} from "react";
import {Plus,Star,Target,Trophy} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useGetHREmployeesQuery,useGetHRPerformanceQuery,useSaveHRPerformanceMutation} from "@/src/lib/features/hr-management/hr-management-api";
import {Badge,Card,CardHeader,ColorButton,Empty,ErrorBox,Field,HRPageTitle,Metric,PrimaryButton,idOf,input,personName} from "./hr-ui";
const defaultPeriod=`${new Date().getFullYear()} H${new Date().getMonth()<6?1:2}`;
export function HRPerformanceWorkspace(){const [show,setShow]=useState(false);const [form,setForm]=useState({employeeId:"",period:defaultPeriod,goalTitle:"",goalWeight:100,goalScore:3,competencyScore:3,overallRating:3,strengths:"",improvements:"",summary:"",status:"draft"});const [error,setError]=useState("");const [feedback,setFeedback]=useState("");const q=useGetHRPerformanceQuery({page:1,limit:200});const employees=useGetHREmployeesQuery({page:1,limit:200});const [save,state]=useSaveHRPerformanceMutation();const rows=q.data?.data??[];const avg=useMemo(()=>{const values=rows.map(r=>r.overallRating).filter((v):v is number=>typeof v==="number");return values.length?values.reduce((s,v)=>s+v,0)/values.length:0},[rows]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await save({employeeId:form.employeeId,period:form.period,goals:form.goalTitle?[{title:form.goalTitle,weight:form.goalWeight,score:form.goalScore}]:[],competencyScore:form.competencyScore,overallRating:form.overallRating,strengths:form.strengths,improvements:form.improvements,summary:form.summary,status:form.status}).unwrap();setFeedback("Performance review saved.");setShow(false);setForm({...form,employeeId:"",goalTitle:"",strengths:"",improvements:"",summary:""})}catch(x){setError(getApiErrorMessage(x))}}
 return <><HRPageTitle eyebrow="Performance Management" title="Goals, feedback and" accent="review cycles." description="Run employee performance reviews with weighted goals, goal score, competency score, overall rating, strengths, improvement areas and written summary. Re-saving the same employee and period updates the review." actions={<ColorButton onClick={()=>setShow(v=>!v)}><Plus className="h-4 w-4"/>New review</ColorButton>}/>{error&&<ErrorBox message={error}/>} {feedback&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{feedback}</div>}
 {show&&<Card className="mb-6"><CardHeader title="Performance review" description="Create a review or update an existing employee-period review."/><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Employee"><select required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className={input}><option value="">Select employee</option>{employees.data?.data.map(e=><option key={idOf(e)} value={idOf(e)}>{e.employeeCode} · {e.firstName} {e.lastName}</option>)}</select></Field><Field label="Review period"><input required value={form.period} onChange={e=>setForm({...form,period:e.target.value})} className={input}/></Field><Field label="Overall rating (0–5)"><input type="number" min={0} max={5} step="0.1" value={form.overallRating} onChange={e=>setForm({...form,overallRating:Number(e.target.value)})} className={input}/></Field><Field label="Competency score (0–5)"><input type="number" min={0} max={5} step="0.1" value={form.competencyScore} onChange={e=>setForm({...form,competencyScore:Number(e.target.value)})} className={input}/></Field><Field label="Primary goal"><input value={form.goalTitle} onChange={e=>setForm({...form,goalTitle:e.target.value})} className={input} placeholder="Ship Q3 customer portal"/></Field><Field label="Goal weight %"><input type="number" min={0} max={100} value={form.goalWeight} onChange={e=>setForm({...form,goalWeight:Number(e.target.value)})} className={input}/></Field><Field label="Goal score (0–5)"><input type="number" min={0} max={5} step="0.1" value={form.goalScore} onChange={e=>setForm({...form,goalScore:Number(e.target.value)})} className={input}/></Field><Field label="Review status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={input}><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="acknowledged">Acknowledged</option><option value="closed">Closed</option></select></Field><Field label="Strengths"><textarea value={form.strengths} onChange={e=>setForm({...form,strengths:e.target.value})} className={`${input} min-h-24 py-3`}/></Field><Field label="Improvement areas"><textarea value={form.improvements} onChange={e=>setForm({...form,improvements:e.target.value})} className={`${input} min-h-24 py-3`}/></Field><div className="md:col-span-2"><Field label="Review summary"><textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} className={`${input} min-h-24 py-3`}/></Field></div><div className="md:col-span-2 xl:col-span-4 flex justify-end"><PrimaryButton type="submit" disabled={state.isLoading}>Save review</PrimaryButton></div></form></Card>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label="Reviews" value={rows.length} helper="Current result set" icon={<Star className="h-5 w-5"/>} gradient="from-rose-500 to-pink-500"/><Metric label="Average rating" value={avg.toFixed(1)} helper="Across rated reviews" icon={<Trophy className="h-5 w-5"/>} gradient="from-amber-500 to-orange-500"/><Metric label="Closed reviews" value={rows.filter(r=>r.status==="closed").length} helper="Completed review cycles" icon={<Target className="h-5 w-5"/>} gradient="from-blue-500 to-violet-500"/></div>
 <Card className="mt-6"><CardHeader title="Performance review register" description={`${q.data?.pagination.total??0} review(s)`}/>{q.isLoading?<p className="p-6 text-sm text-slate-400">Loading reviews…</p>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Employee</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Rating</th><th className="px-4 py-3">Goals</th><th className="px-4 py-3">Summary</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={idOf(r)}><td className="px-5 py-4"><b className="text-slate-800">{personName(r.employeeId)}</b>{typeof r.employeeId==="object"&&<p className="mt-1 text-xs text-slate-400">{r.employeeId.employeeCode} · {r.employeeId.designation}</p>}</td><td className="px-4 py-4 text-xs font-bold text-slate-600">{r.period}</td><td className="px-4 py-4"><span className="font-black text-amber-600">★ {r.overallRating?.toFixed(1)??"—"}</span><p className="mt-1 text-[10px] text-slate-400">Competency {r.competencyScore?.toFixed(1)??"—"}</p></td><td className="px-4 py-4 text-xs text-slate-500">{r.goals.length}</td><td className="max-w-sm px-4 py-4 text-xs text-slate-500"><p className="line-clamp-2">{r.summary||r.strengths||"—"}</p></td><td className="px-5 py-4"><Badge tone={r.status==="closed"?"green":r.status==="acknowledged"?"blue":r.status==="submitted"?"violet":"slate"}>{r.status}</Badge></td></tr>)}</tbody></table></div>:<Empty title="No performance reviews" description="Create a review to start a performance cycle."/>}</Card>
 </>}
