"use client";
import {useState} from "react";
import {BadgeIndianRupee,BarChart3,CalendarCheck,Download,Users} from "lucide-react";
import {getApiErrorMessage} from "@/src/lib/api/error";
import {useGetHRReportsQuery} from "@/src/lib/features/hr-management/hr-management-api";
import {Card,CardHeader,ErrorBox,HRPageTitle,Metric,SecondaryButton,money} from "./hr-ui";
function BarList({items}:{items:Array<{label:string;value:number}>}){const max=Math.max(1,...items.map(i=>i.value));return <div className="space-y-4 p-5">{items.map(item=><div key={item.label}><div className="mb-1.5 flex justify-between text-xs"><b className="text-slate-700">{item.label||"Unspecified"}</b><span className="font-black text-slate-500">{item.value}</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 via-violet-500 to-rose-400" style={{width:`${Math.max(3,item.value/max*100)}%`}}/></div></div>)}</div>}
export function HRReportsWorkspace(){const [from,setFrom]=useState(new Date(Date.now()-29*86400000).toISOString().slice(0,10));const [to,setTo]=useState(new Date().toISOString().slice(0,10));const q=useGetHRReportsQuery({from,to});const d=q.data?.data;const headcount=(d?.departments??[]).reduce((s,x)=>s+x.count,0),attendance=(d?.attendance??[]).reduce((s,x)=>s+x.count,0),leaveDays=(d?.leaves??[]).reduce((s,x)=>s+x.days,0),payrollNet=(d?.payroll??[]).reduce((s,x)=>s+x.net,0);
 function exportCsv(){if(!d)return;const lines=["Quantum Finix HR Report",`Period,${from},${to}`,"","Department,Headcount",...d.departments.map(x=>`${JSON.stringify(x._id)},${x.count}`),"","Attendance Status,Count",...d.attendance.map(x=>`${x._id},${x.count}`),"","Leave Status,Requests,Days",...d.leaves.map(x=>`${x._id},${x.count},${x.days}`),"","Payroll Status,Records,Gross,Net",...d.payroll.map(x=>`${x._id},${x.count},${x.gross},${x.net}`)];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv"}));a.download=`quantum-finix-hr-report-${from}-to-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <><HRPageTitle eyebrow="HR Reports & Analytics" title="Operational insights and" accent="HR reporting." description="Review department headcount, attendance distribution, leave usage, payroll totals and headcount trend from live HRMS data. Filter the reporting date range and export the result for further analysis." actions={<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600"/><SecondaryButton onClick={exportCsv}><Download className="h-4 w-4"/>Export report</SecondaryButton></>}/>{q.error&&<ErrorBox message={getApiErrorMessage(q.error)}/>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Headcount" value={headcount} helper="Employees in department distribution" icon={<Users className="h-5 w-5"/>} gradient="from-emerald-500 to-teal-500"/><Metric label="Attendance entries" value={attendance} helper="Within selected period" icon={<CalendarCheck className="h-5 w-5"/>} gradient="from-blue-500 to-cyan-500"/><Metric label="Leave days" value={leaveDays} helper="Requests created in selected period" icon={<BarChart3 className="h-5 w-5"/>} gradient="from-amber-500 to-orange-500"/><Metric label="Payroll net" value={money(payrollNet)} helper="Across matching payroll records" icon={<BadgeIndianRupee className="h-5 w-5"/>} gradient="from-violet-500 to-fuchsia-500"/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><CardHeader title="Headcount by department" description="Current employee distribution"/><BarList items={(d?.departments??[]).map(x=>({label:x._id||"Unassigned",value:x.count}))}/></Card><Card><CardHeader title="Attendance distribution" description={`${from} to ${to}`}/><BarList items={(d?.attendance??[]).map(x=>({label:x._id,value:x.count}))}/></Card><Card><CardHeader title="Leave usage" description="Requests and requested days"/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Status</th><th className="px-4 py-3">Requests</th><th className="px-5 py-3">Days</th></tr></thead><tbody className="divide-y divide-slate-100">{d?.leaves.map(x=><tr key={x._id}><td className="px-5 py-4 font-bold text-slate-700">{x._id}</td><td className="px-4 py-4 text-slate-500">{x.count}</td><td className="px-5 py-4 font-black text-slate-700">{x.days}</td></tr>)}</tbody></table></div></Card><Card><CardHeader title="Payroll summary" description="Grouped by payroll status"/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Status</th><th className="px-4 py-3">Records</th><th className="px-4 py-3">Gross</th><th className="px-5 py-3">Net</th></tr></thead><tbody className="divide-y divide-slate-100">{d?.payroll.map(x=><tr key={x._id}><td className="px-5 py-4 font-bold text-slate-700">{x._id}</td><td className="px-4 py-4 text-slate-500">{x.count}</td><td className="px-4 py-4 text-slate-500">{money(x.gross)}</td><td className="px-5 py-4 font-black text-slate-800">{money(x.net)}</td></tr>)}</tbody></table></div></Card><Card className="xl:col-span-2"><CardHeader title="Joiner trend" description="Employee joining records by month"/><BarList items={(d?.headcountTrend??[]).map(x=>({label:x._id,value:x.joined}))}/></Card></div>
 </>}
