"use client";
import Link from "next/link";
import {CalendarClock,FileText,Mail,Settings,ShieldCheck,Users} from "lucide-react";
import {useGetMeQuery} from "@/src/lib/features/auth/auth-api";
import {Card,CardHeader,HRPageTitle} from "./hr-ui";

const items=[
 {href:"/hr-management/access",title:"HR roles & permissions",desc:"Create roles and assign least-privilege access for HR, payroll and hiring teams.",icon:ShieldCheck,permission:"roles.manage"},
 {href:"/hr-management/users",title:"User access",desc:"Create and manage platform accounts linked to employee records without leaving HRMS.",icon:Users,permission:"users.manage"},
 {href:"/hr-management/attendance",title:"Shifts & attendance rules",desc:"Configure active shifts, timings, grace periods, work days and weekly hours.",icon:CalendarClock,permission:"hr-management.attendance.manage"},
 {href:"/hr-management/documents",title:"Document templates & issuance",desc:"Configure HR letter templates, merge variables, acknowledgement forms and issue workflows.",icon:FileText,permission:"documents.manage"},
 {href:"/hr-management/communication?tab=bulk-email",title:"Email templates & delivery",desc:"Manage HR campaigns, templates, recipient lists, delivery queues and communication history.",icon:Mail,permission:"hr-management.communication.manage"},
];

export function HRSettingsWorkspace(){const me=useGetMeQuery();const user=me.data?.data;const can=(permission:string)=>user?.role==="super-admin"||Boolean(user?.permissions?.includes(permission));const visible=items.filter(x=>can(x.permission));return <><HRPageTitle eyebrow="HR Settings" title="Configure the" accent="HR operating model." description="People access, shifts, documents and communication remain inside the HRMS. Security-sensitive settings are shown only when the signed-in role has the required permission."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(x=><Link key={x.href} href={x.href} className="qf-surface qf-shadow qf-border group rounded-2xl border p-5 transition hover:border-blue-300"><span className="qf-status-info grid h-11 w-11 place-items-center rounded-xl border"><x.icon className="h-5 w-5"/></span><h3 className="qf-text mt-4 font-black group-hover:text-[var(--qf-primary-text)]">{x.title}</h3><p className="qf-muted mt-2 text-xs leading-5">{x.desc}</p></Link>)}</div><Card className="mt-6"><CardHeader title="HRMS coverage" description="Core workflows available from this workspace."/><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-3">{["Jobs & careers publishing","Application pipeline","External candidate management","Interview scheduling & scorecards","Candidate notifications","Employee master","Department dashboards","Reporting manager","Employment lifecycle","Shift management","Attendance / WFH / overtime","Employee self check-in/out","Holiday calendar","Timesheets & approvals","Expenses & reimbursements","HR helpdesk / grievance cases","Policy publishing & acknowledgements","Leave requests & approvals","Payroll & payment status","Onboarding checklist","Performance reviews","Employee asset allocation","HR announcements","Mass email campaigns","Delivery queues & notifications","HR document templates","Offer / appointment letters","Bulk document issuance","Acknowledgement / signature return","Print & download issued documents","Native file sharing","Roles & permissions","Audit activity","HR reports & CSV export"].map(x=><div key={x} className="qf-surface-muted qf-text-secondary flex items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-bold"><Settings className="h-3.5 w-3.5 text-[var(--qf-primary-text)]"/>{x}</div>)}</div></Card></>}
