"use client";
import { useMemo, useState, type FormEvent } from "react";
import { getApiErrorMessage } from "@/src/lib/api/error";
import {
  useAcknowledgeMyHRPolicyMutation,
  useCreateMyHRCaseMutation,
  useCreateMyHRExpenseMutation,
  useCreateMyHRTimesheetMutation,
  useGetMyHROperationsQuery,
} from "@/src/lib/features/hr-management/hr-operations-api";
import { Field, Panel, PanelHeader, PrimaryButton, SecondaryButton, StatusBadge, inputClass, textareaClass } from "./profile-ui";

export function ProfileHROperationsPanel(){
 const query=useGetMyHROperationsQuery();const data=query.data?.data;
 const [saveTime,timeState]=useCreateMyHRTimesheetMutation();const [saveExpense,expenseState]=useCreateMyHRExpenseMutation();const [saveCase,caseState]=useCreateMyHRCaseMutation();const [ack,ackState]=useAcknowledgeMyHRPolicyMutation();
 const [message,setMessage]=useState("");const [error,setError]=useState("");
 const [time,setTime]=useState({date:today(),project:"",task:"",hours:"8",billable:false,notes:""});
 const [expense,setExpense]=useState({expenseDate:today(),category:"Travel",amount:"",currency:"INR",description:"",receiptUrl:""});
 const [hrCase,setCase]=useState({category:"other",subject:"",description:"",priority:"normal",confidential:false});
 const acknowledged=useMemo(()=>new Set((data?.acknowledgements??[]).map(x=>String(x.policyId))),[data?.acknowledgements]);
 async function run(fn:()=>Promise<unknown>,ok:string){setError("");setMessage("");try{await fn();setMessage(ok);await query.refetch()}catch(e){setError(getApiErrorMessage(e))}}
 async function submitTime(e:FormEvent){e.preventDefault();await run(()=>saveTime({...time,hours:Number(time.hours)}).unwrap(),"Timesheet submitted to HR.")}
 async function submitExpense(e:FormEvent){e.preventDefault();await run(()=>saveExpense({...expense,amount:Number(expense.amount)}).unwrap(),"Expense claim submitted to HR.")}
 async function submitCase(e:FormEvent){e.preventDefault();await run(()=>saveCase(hrCase).unwrap(),"HR case created. HR can now track and respond to it.")}
 if(query.error||!data)return null;
 const upcoming=data.holidays.filter(x=>new Date(x.date)>=new Date(new Date().toDateString())).slice(0,8);
 return <div className="mt-6 space-y-6">
   {error?<div className="rounded-xl border border-rose-300/20 bg-rose-300/[0.06] px-4 py-3 text-sm text-rose-200">{error}</div>:null}{message?<div className="rounded-xl border border-emerald-300/20 bg-emerald-300/[0.06] px-4 py-3 text-sm text-emerald-100">{message}</div>:null}
   <Panel><PanelHeader title="Time, expenses & HR helpdesk" description="Submit operational HR requests without email threads or spreadsheets."/><div className="grid gap-6 p-5 lg:grid-cols-3 sm:p-6">
    <form onSubmit={submitTime} className="space-y-4 rounded-2xl border border-white/[0.08] p-4"><h3 className="font-bold text-white">Submit timesheet</h3><Field label="Date"><input className={inputClass} type="date" required value={time.date} onChange={e=>setTime({...time,date:e.target.value})}/></Field><Field label="Project"><input className={inputClass} value={time.project} onChange={e=>setTime({...time,project:e.target.value})} placeholder="Project / cost center"/></Field><Field label="Task"><input className={inputClass} value={time.task} onChange={e=>setTime({...time,task:e.target.value})}/></Field><Field label="Hours"><input className={inputClass} type="number" min="0.25" max="24" step="0.25" required value={time.hours} onChange={e=>setTime({...time,hours:e.target.value})}/></Field><label className="flex items-center gap-2 text-xs font-semibold text-slate-400"><input type="checkbox" checked={time.billable} onChange={e=>setTime({...time,billable:e.target.checked})}/>Billable time</label><PrimaryButton type="submit" disabled={timeState.isLoading}>{timeState.isLoading?"Submitting...":"Submit time"}</PrimaryButton></form>
    <form onSubmit={submitExpense} className="space-y-4 rounded-2xl border border-white/[0.08] p-4"><h3 className="font-bold text-white">Expense / reimbursement</h3><Field label="Expense date"><input className={inputClass} type="date" required value={expense.expenseDate} onChange={e=>setExpense({...expense,expenseDate:e.target.value})}/></Field><Field label="Category"><select className={inputClass} value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{["Travel","Meals","Internet","Office supplies","Training","Medical","Client expense","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><div className="grid grid-cols-[1fr_100px] gap-2"><Field label="Amount"><input className={inputClass} type="number" min="0" step="0.01" required value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></Field><Field label="Currency"><input className={inputClass} maxLength={3} required value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value.toUpperCase()})}/></Field></div><Field label="Description"><textarea className={`${textareaClass} min-h-20`} required value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})}/></Field><Field label="Receipt URL (optional)"><input className={inputClass} type="url" value={expense.receiptUrl} onChange={e=>setExpense({...expense,receiptUrl:e.target.value})}/></Field><PrimaryButton type="submit" disabled={expenseState.isLoading}>{expenseState.isLoading?"Submitting...":"Submit expense"}</PrimaryButton></form>
    <form onSubmit={submitCase} className="space-y-4 rounded-2xl border border-white/[0.08] p-4"><h3 className="font-bold text-white">HR helpdesk / grievance</h3><Field label="Category"><select className={inputClass} value={hrCase.category} onChange={e=>setCase({...hrCase,category:e.target.value})}>{["grievance","payroll","leave","policy","it","facilities","harassment","other"].map(x=><option key={x} value={x}>{title(x)}</option>)}</select></Field><Field label="Subject"><input className={inputClass} required value={hrCase.subject} onChange={e=>setCase({...hrCase,subject:e.target.value})}/></Field><Field label="Details"><textarea className={textareaClass} required value={hrCase.description} onChange={e=>setCase({...hrCase,description:e.target.value})}/></Field><Field label="Priority"><select className={inputClass} value={hrCase.priority} onChange={e=>setCase({...hrCase,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><label className="flex items-center gap-2 text-xs font-semibold text-slate-400"><input type="checkbox" checked={hrCase.confidential} onChange={e=>setCase({...hrCase,confidential:e.target.checked})}/>Mark case confidential</label><PrimaryButton type="submit" disabled={caseState.isLoading}>{caseState.isLoading?"Submitting...":"Create HR case"}</PrimaryButton></form>
   </div></Panel>
   <div className="grid gap-6 xl:grid-cols-2"><Panel><PanelHeader title="Policies & acknowledgements" description="Active Quantum Finix HR policies assigned to employees."/>{data.policies.length?<div className="divide-y divide-white/[0.07]">{data.policies.map(policy=>{const id=policy.id??policy._id??"";const done=acknowledged.has(id);return <div key={id} className="p-5 sm:px-6"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-white">{policy.title}</p><StatusBadge tone={done?"emerald":"amber"}>{done?"Acknowledged":policy.requiresAcknowledgement?"Action required":"Published"}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{policy.category} · v{policy.version} · effective {formatDate(policy.effectiveDate)}</p>{policy.summary?<p className="mt-3 text-sm leading-6 text-slate-400">{policy.summary}</p>:null}<details className="mt-3"><summary className="cursor-pointer text-xs font-bold text-cyan-300">Read full policy</summary><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-400">{policy.content}</p></details></div>{policy.requiresAcknowledgement&&!done?<SecondaryButton type="button" disabled={ackState.isLoading} onClick={()=>run(()=>ack(id).unwrap(),"Policy acknowledgement recorded.")}>Acknowledge</SecondaryButton>:null}</div></div>})}</div>:<div className="p-6 text-sm text-slate-500">No active policies have been published.</div>}</Panel>
   <Panel><PanelHeader title="Holiday calendar & recent requests" description="Upcoming holidays plus your latest operations requests."/><div className="p-5 sm:p-6"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Upcoming holidays</h3><div className="mt-3 space-y-2">{upcoming.length?upcoming.map(x=><div key={x.id??x._id} className="flex items-center justify-between rounded-xl border border-white/[0.08] p-3"><span><b className="text-sm text-white">{x.name}</b><span className="ml-2 text-xs text-slate-500">{formatDate(x.date)}</span></span><StatusBadge tone={x.isOptional?"amber":"cyan"}>{x.category}</StatusBadge></div>):<p className="text-sm text-slate-500">No upcoming holidays configured.</p>}</div><h3 className="mt-6 text-xs font-bold uppercase tracking-wider text-slate-500">Recent status</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><Mini label="Timesheets" value={`${data.timesheets.filter(x=>x.status==="submitted").length} pending`}/><Mini label="Expenses" value={`${data.expenses.filter(x=>x.status==="pending").length} pending`}/><Mini label="HR cases" value={`${data.cases.filter(x=>!["resolved","closed"].includes(x.status)).length} open`}/></div></div></Panel></div>
 </div>;
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[0.08] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>}
function today(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function title(value:string){return value.charAt(0).toUpperCase()+value.slice(1)}
function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString()}
