"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { downloadAdminFile } from "@/src/lib/download";
import { useGetDocumentTemplatesQuery } from "@/src/lib/features/documents/document-api";
import {
  useAdminBulkUpdateJobApplicationStatusMutation,
  useAdminDeleteJobApplicationMutation,
  useAdminGetJobApplicationQuery,
  useAdminListJobApplicationsQuery,
  useAdminReleaseApplicationDocumentsMutation,
  useAdminUpdateJobApplicationStatusMutation,
} from "@/src/lib/features/job-applications/job-application-api";
import type { ApplicationStatus, JobApplication, JobReference, PresentedAsset } from "@/src/lib/features/job-applications/job-application-types";
import { Button, Empty, ErrorNotice, Field, LoadingRows, Panel, PanelTitle, Pagination, StatusBadge, SuccessNotice, formatDate, inputClass, textareaClass } from "./admin-ui";

const statuses: Array<ApplicationStatus | ""> = ["", "Applied", "Reviewing", "Shortlisted", "Interview Scheduled", "Interviewed", "Offered", "Hired", "Rejected", "Withdrawn"];

export function ApplicationsPanel({ basePath = "/dashboard/application" }: { basePath?: string } = {}) {
  const [page,setPage]=useState(1),[status,setStatus]=useState<ApplicationStatus|"">(""),[search,setSearch]=useState(""),[fromDate,setFromDate]=useState(""),[toDate,setToDate]=useState("");
  const [selected,setSelected]=useState<string[]>([]),[bulkStatus,setBulkStatus]=useState<ApplicationStatus>("Reviewing"),[templateId,setTemplateId]=useState(""),[exporting,setExporting]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const query={page,limit:25,...(status?{status}:{}),...(search.trim()?{search:search.trim()}:{}),...(fromDate?{fromDate}:{}),...(toDate?{toDate}:{})};
  const list=useAdminListJobApplicationsQuery(query); const templates=useGetDocumentTemplatesQuery({page:1,limit:100,status:"active"});
  const [bulkUpdate,bulkState]=useAdminBulkUpdateJobApplicationStatusMutation(); const [releaseDocs,releaseState]=useAdminReleaseApplicationDocumentsMutation();
  const apps=list.data?.data??[]; const allCurrent=apps.length>0&&apps.every(a=>selected.includes(a.id));
  const busy=bulkState.isLoading||releaseState.isLoading||exporting;
  useEffect(()=>{setSelected(current=>current.filter(id=>apps.some(a=>a.id===id)))},[list.data?.pagination.page]);
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
  const toggleAll=()=>setSelected(current=>allCurrent?current.filter(id=>!apps.some(a=>a.id===id)):[...new Set([...current,...apps.map(a=>a.id)])]);
  async function bulk(){if(!selected.length)return;setError("");try{const r=await bulkUpdate({ids:selected,status:bulkStatus}).unwrap();setNotice(r.message||`${selected.length} applications updated.`);setSelected([])}catch(e){setError(getApiErrorMessage(e))}}
  async function release(){if(!selected.length||!templateId)return;setError("");try{const r=await releaseDocs({applicationIds:selected,templateId,sendEmail:true}).unwrap();setNotice(r.message||"Documents released.");setSelected([])}catch(e){setError(getApiErrorMessage(e))}}
  async function exportRows(){setExporting(true);setError("");try{await downloadAdminFile("/job-applications/admin/export","quantumfinix-applications.xlsx",{...(status?{status}:{}),...(search.trim()?{search:search.trim()}:{}),...(fromDate?{fromDate}:{}),...(toDate?{toDate}:{})})}catch(e){setError(getApiErrorMessage(e))}finally{setExporting(false)}}
  return <section><PageHeading eyebrow="Candidate pipeline" title="Applications" description="Search, filter by date, bulk-select candidates, change status, release documents, and export the current filtered pipeline." action={<Button secondary disabled={exporting} onClick={()=>void exportRows()}>{exporting?"Exporting…":"Export Excel"}</Button>}/>
    {error?<ErrorNotice message={error}/>:null}{notice?<SuccessNotice message={notice}/>:null}
    <Panel><PanelTitle eyebrow="Filters" title="Candidate applications"/><div className="grid gap-3 lg:grid-cols-5"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, email, phone, location" className={inputClass}/><select value={status} onChange={e=>{setStatus(e.target.value as ApplicationStatus|"");setPage(1)}} className={inputClass}>{statuses.map(x=><option key={x||"all"} value={x}>{x||"All statuses"}</option>)}</select><input aria-label="From date" type="date" value={fromDate} onChange={e=>{setFromDate(e.target.value);setPage(1)}} className={inputClass}/><input aria-label="To date" type="date" value={toDate} onChange={e=>{setToDate(e.target.value);setPage(1)}} className={inputClass}/><Button secondary onClick={()=>{setSearch("");setStatus("");setFromDate("");setToDate("");setPage(1)}}>Clear filters</Button></div>
    <div className="my-4 grid gap-3 rounded-2xl border border-white/8 bg-black/20 p-4 lg:grid-cols-[auto_220px_auto_1fr_auto]"><span className="self-center text-sm font-bold text-slate-300">{selected.length} selected</span><select value={bulkStatus} onChange={e=>setBulkStatus(e.target.value as ApplicationStatus)} className={inputClass}>{statuses.filter(Boolean).map(x=><option key={x} value={x}>{x}</option>)}</select><Button disabled={busy||!selected.length} onClick={()=>void bulk()}>Change status</Button><select value={templateId} onChange={e=>setTemplateId(e.target.value)} className={inputClass}><option value="">Choose active document template</option>{templates.data?.data.map(t=><option key={t.id??t._id} value={t.id??t._id}>{t.name}</option>)}</select><Button secondary disabled={busy||!selected.length||!templateId} onClick={()=>void release()}>Bulk release</Button></div>
    {list.isLoading?<LoadingRows/>:list.error?<ErrorNotice message={getApiErrorMessage(list.error)}/>:apps.length?<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3"><input aria-label="Select all visible applications" type="checkbox" checked={allCurrent} onChange={toggleAll}/></th><th className="pb-3">Candidate</th><th className="pb-3">Job</th><th className="pb-3">Applied</th><th className="pb-3">Status</th><th className="pb-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-white/8">{apps.map(a=><tr key={a.id}><td className="py-4"><input aria-label={`Select ${a.personalInfo.firstName}`} type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/></td><td className="py-4"><p className="font-bold">{a.personalInfo.firstName} {a.personalInfo.lastName}</p><p className="text-xs text-slate-500">{a.personalInfo.email}</p></td><td>{jobLabel(a.jobId)}</td><td className="text-xs text-slate-500">{formatDate(a.appliedAt)}</td><td><StatusBadge value={a.status}/></td><td className="text-right"><Link href={`${basePath}/${a.id}`} className="rounded-xl border border-cyan-300/20 px-4 py-2.5 text-xs font-bold text-cyan-200">Review</Link></td></tr>)}</tbody></table></div>:<Empty title="No applications found" description="Applications matching the selected filters will appear here."/>}<Pagination page={page} totalPages={list.data?.pagination.totalPages??1} onPageChange={setPage}/></Panel>
  </section>
}

export function ApplicationAdminDetail({applicationId,basePath="/dashboard/application"}:{applicationId:string;basePath?:string}){
 const router=useRouter();const detail=useAdminGetJobApplicationQuery(applicationId,{refetchOnMountOrArgChange:true});const selected=detail.data?.data;const[nextStatus,setNextStatus]=useState<ApplicationStatus>("Reviewing"),[notes,setNotes]=useState(""),[initializedId,setInitializedId]=useState(""),[notice,setNotice]=useState(""),[localError,setLocalError]=useState(""),[preview,setPreview]=useState<PresentedAsset|null>(null);const[updateStatus,updateState]=useAdminUpdateJobApplicationStatusMutation();const[removeApplication,removeState]=useAdminDeleteJobApplicationMutation();
 useEffect(()=>{if(!selected||initializedId===selected.id)return;setInitializedId(selected.id);setNextStatus(selected.status);setNotes(selected.recruiterNotes??"")},[initializedId,selected]);
 async function saveStatus(){setLocalError("");try{const r=await updateStatus({id:applicationId,status:nextStatus,...(notes.trim()?{recruiterNotes:notes.trim()}:{})}).unwrap();setNotice(r.message||"Application status updated.")}catch(e){setLocalError(getApiErrorMessage(e))}}
 async function remove(){if(!window.confirm("Delete this application and all stored documents?"))return;try{await removeApplication(applicationId).unwrap();router.replace(basePath)}catch(e){setLocalError(getApiErrorMessage(e))}}
 if(detail.isLoading)return <LoadingRows count={8}/>;if(detail.error||!selected)return <ErrorNotice message={getApiErrorMessage(detail.error??"Application unavailable")}/>;
 const docs=[selected.documents?.resume,selected.documents?.photo,selected.documents?.coverLetter].filter(Boolean) as PresentedAsset[];
 return <section><PageHeading eyebrow="Candidate record" title={`${selected.personalInfo.firstName} ${selected.personalInfo.lastName}`} description={`${jobLabel(selected.jobId)} · Applied ${formatDate(selected.appliedAt)}`} action={<div className="flex gap-2"><Button secondary onClick={()=>void detail.refetch()}>Refresh links</Button><Link href={basePath} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold">Back</Link></div>}/>{localError?<ErrorNotice message={localError}/>:null}{notice?<SuccessNotice message={notice}/>:null}<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><Panel><InfoGrid application={selected}/><Collection title="Education" items={selected.education.map(x=>`${x.degree} · ${x.schoolOrUniversity}`)}/><Collection title="Experience" items={selected.experience.map(x=>`${x.role} at ${x.companyName} · ${x.responsibilities}`)}/><Collection title="Screening answers" items={(selected.screeningAnswers??[]).map(x=>`${x.question}: ${Array.isArray(x.answer)?x.answer.join(", "):x.answer}`)}/><div className="mt-6 flex flex-wrap gap-3">{docs.map(d=><div key={d.originalName} className="flex gap-2"><Button secondary onClick={()=>setPreview(d)}>Preview {d.originalName}</Button><a href={d.downloadUrl??d.url} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold" download>Download</a></div>)}</div></Panel><aside><Panel><PanelTitle eyebrow="Decision" title="Application status"/><Field label="New status"><select value={nextStatus} onChange={e=>setNextStatus(e.target.value as ApplicationStatus)} className={inputClass}>{statuses.filter(Boolean).map(x=><option key={x} value={x}>{x}</option>)}</select></Field><div className="mt-4"><Field label="Recruiter notes"><textarea rows={9} value={notes} onChange={e=>setNotes(e.target.value)} className={textareaClass}/></Field></div><div className="mt-5 grid gap-3"><Button disabled={updateState.isLoading} onClick={()=>void saveStatus()}>Update status</Button>{nextStatus === "Interview Scheduled" || selected.status === "Interview Scheduled" ? <Link href={`/hr-management/interviews?applicationId=${applicationId}`} className="qf-primary-button rounded-xl px-4 py-3 text-center text-sm font-black">Configure candidate interview availability</Link> : null}{nextStatus === "Interview Scheduled" ? <p className="rounded-xl border border-cyan-300/15 bg-cyan-300/[0.05] px-4 py-3 text-xs leading-5 text-cyan-100/80">After saving this status, configure a fixed interview or let the candidate choose from restricted dates, weekdays and time slots. Reusable interviewer timetable templates are available in the scheduler.</p> : null}<Button danger disabled={removeState.isLoading} onClick={()=>void remove()}>Delete application</Button></div></Panel></aside></div>
 {preview?<div className="fixed inset-0 z-[80] grid place-items-center bg-black/80 p-4" onClick={()=>setPreview(null)}><div className="h-[90vh] w-full max-w-5xl rounded-2xl border border-white/10 bg-[#07101f] p-4" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between"><p className="font-black">{preview.originalName}</p><div className="flex gap-2"><a href={preview.downloadUrl??preview.url} download className="rounded-xl border border-white/10 px-3 py-2 text-sm font-bold">Download</a><Button secondary onClick={()=>setPreview(null)}>Close</Button></div></div>{preview.mimeType?.includes("pdf")?<iframe title={preview.originalName} src={preview.url} className="h-[calc(100%-56px)] w-full rounded-xl bg-white"/>:preview.mimeType?.startsWith("image/")?<img src={preview.url} alt={preview.originalName} className="h-[calc(100%-56px)] w-full object-contain"/>:<div className="grid h-[calc(100%-56px)] place-items-center text-slate-400">Preview unavailable for this format. Use Download.</div>}</div></div>:null}</section>
}
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">{eyebrow}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>}
function jobLabel(job:JobReference){return typeof job==="string"?job:job.title||job.id||job._id||"Job"}function InfoGrid({application}:{application:JobApplication}){const fields=[["Email",application.personalInfo.email],["Phone",application.personalInfo.phoneNumber],["Gender",application.personalInfo.gender],["Date of birth",application.personalInfo.dateOfBirth?.slice(0,10)],["Location",application.personalInfo.currentLocation],["Application ID",application.id]];return <div className="grid gap-3 sm:grid-cols-2">{fields.map(([l,v])=><div key={l} className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{l}</p><p className="mt-2 break-all text-sm font-semibold text-slate-200">{v||"—"}</p></div>)}</div>}function Collection({title,items}:{title:string;items:string[]}){return <div className="mt-6"><h3 className="text-sm font-black uppercase tracking-wider text-cyan-300">{title}</h3>{items.length?<ul className="mt-3 space-y-2">{items.map((x,i)=><li key={i} className="rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm text-slate-300">{x}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">No data provided.</p>}</div>}
