"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { Download, Filter, Mail, Plus, Search, UserRoundCheck, X } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { downloadAdminFile } from "@/src/lib/download";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useBulkAssignLeadsMutation, useBulkEmailLeadsMutation, useBulkRoundRobinLeadsMutation, useBulkUpdateLeadsMutation, useGetLeadAssigneesQuery, useGetLeadsQuery } from "@/src/lib/features/leads/lead-api";
import type { LeadListQuery, LeadPriority, LeadQualification, LeadSource, LeadStatus, LeadTemperature } from "@/src/lib/features/leads/lead-types";
import { Card, Empty, Field, LeadScore, PageHeader, StatusPill, formatDate, formatMoney, inputClass, ownerLabel, primaryButton, secondaryButton, textareaClass } from "./lead-ui";

const statuses: LeadStatus[]=["New","Attempting Contact","Contacted","Nurturing","Qualified","Proposal Sent","Negotiation","Converted","Lost","Spam"];
const qualifications: LeadQualification[]=["Unqualified","MQL","SQL","Disqualified"];
const temperatures: LeadTemperature[]=["Cold","Warm","Hot"];
const priorities: LeadPriority[]=["Low","Medium","High","Urgent"];
const sources: LeadSource[]=["Website Form","Contact Page","Landing Page","Referral","Social Media","Campaign","Email Campaign","Paid Ads","Organic Search","Webinar","Partner","Outbound","Import","Manual","Other"];

export function LeadListWorkspace(){
  const params=useSearchParams(); const view=params.get("view")||"all"; const me=useGetMeQuery(); const user=me.data?.data; const perms=user?.permissions??[]; const elevated=user?.role==="super-admin"||perms.includes("leads.manage");
  const canAssign=elevated||perms.includes("lead-management.assign"); const canEdit=elevated||perms.includes("lead-management.edit"); const canEmail=elevated||perms.includes("lead-management.communicate"); const canExport=elevated||perms.includes("lead-management.import-export");
  const [page,setPage]=useState(1),[search,setSearch]=useState(""),[status,setStatus]=useState<LeadStatus|"">(""),[qualification,setQualification]=useState<LeadQualification|"">(""),[temperature,setTemperature]=useState<LeadTemperature|"">(""),[priority,setPriority]=useState<LeadPriority|"">(""),[source,setSource]=useState<LeadSource|"">(""),[owner,setOwner]=useState(""),[scoreMin,setScoreMin]=useState(""),[selected,setSelected]=useState<string[]>([]),[showFilters,setShowFilters]=useState(false),[showEmail,setShowEmail]=useState(false),[subject,setSubject]=useState(""),[message,setMessage]=useState("");
  const assignees=useGetLeadAssigneesQuery(undefined,{skip:!canAssign}); const [bulkAssign,{isLoading:assigning}]=useBulkAssignLeadsMutation(); const [bulkRoundRobin,{isLoading:autoAssigning}]=useBulkRoundRobinLeadsMutation(); const [bulkUpdate,{isLoading:updating}]=useBulkUpdateLeadsMutation(); const [bulkEmail,{isLoading:emailing}]=useBulkEmailLeadsMutation();
  const query:LeadListQuery=useMemo(()=>({page,limit:25,sortBy:view==="hot"?"score":view==="followups"?"nextFollowUpAt":"createdAt",sortOrder:view==="followups"?"asc":"desc",...(search.trim()?{search:search.trim()}:{}),...(status?{status}:{}),...(qualification?{qualification}:{}),...(temperature?{temperature}:{}),...(priority?{priority}:{}),...(source?{source}:{}),...(owner?{assignedTo:owner}:{}),...(scoreMin?{scoreMin:Number(scoreMin)}:{}),...(view==="hot"?{temperature:"Hot" as const}:{}),...(view==="followups"?{followUpDue:true}:{}),...(view==="unassigned"?{unassigned:true}:{}),...(view==="my"&&user?.userId?{assignedTo:user.userId}:{})}),[page,view,search,status,qualification,temperature,priority,source,owner,scoreMin,user?.userId]);
  const list=useGetLeadsQuery(query); const rows=list.data?.data??[]; const pagination=list.data?.pagination; const all=rows.length>0&&rows.every((lead)=>selected.includes(lead._id));
  const title=view==="hot"?"High-opportunity leads":view==="followups"?"Follow-up queue":view==="unassigned"?"Unassigned leads":view==="my"?"My assigned leads":"Lead pipeline";
  const reset=()=>{setStatus("");setQualification("");setTemperature("");setPriority("");setSource("");setOwner("");setScoreMin("");setPage(1)};
  async function assign(value:string){try{const r=await bulkAssign({ids:selected,assignedTo:value||null}).unwrap();toast.success(`${r.data.updated} lead${r.data.updated===1?"":"s"} assigned`);setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  async function updateStatus(value:string){if(!value)return;try{const r=await bulkUpdate({ids:selected,status:value as LeadStatus}).unwrap();toast.success(`${r.data.updated} lead${r.data.updated===1?"":"s"} updated`);setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  async function autoBalance(){try{const r=await bulkRoundRobin({ids:selected}).unwrap();toast.success(`${r.data.updated} lead${r.data.updated===1?"":"s"} auto-assigned across the sales team`);setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  async function sendBulk(){if(!subject.trim()||!message.trim()||!selected.length)return;try{const r=await bulkEmail({ids:selected,subject:subject.trim(),message:message.trim()}).unwrap();toast.success(`${r.data.sent} email${r.data.sent===1?"":"s"} sent`);if(r.data.failed)toast.error(`${r.data.failed} delivery failure${r.data.failed===1?"":"s"}`);setShowEmail(false);setSubject("");setMessage("");setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  async function exportRows(){try{await downloadAdminFile("/lead/admin/export","quantumfinix-leads.xlsx",{format:"xlsx",...Object.fromEntries(Object.entries(query).filter(([,v])=>v!==undefined&&v!==""))});}catch(e){toast.error(getApiErrorMessage(e))}}
  return <><PageHeader title={title} description="Search, qualify, prioritize and manage lead ownership from one pipeline. Sales users are server-scoped to their assigned leads; managers can filter and rebalance ownership." actions={<>{canExport?<button className={secondaryButton} onClick={()=>void exportRows()}><Download className="h-4 w-4"/>Export</button>:null}{canEdit?<Link href="/lead-management/leads/new" className={primaryButton}><Plus className="h-4 w-4"/>New lead</Link>:null}</>}/>
    <Card className="mb-5 p-4"><div className="flex flex-col gap-3 xl:flex-row"><div className="relative min-w-0 flex-1"><Search className="qf-muted absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2"/><input className={`${inputClass} pl-10`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, company, email, phone, product, tag…"/></div><button className={secondaryButton} onClick={()=>setShowFilters(v=>!v)}><Filter className="h-4 w-4"/>Filters</button></div>
      {showFilters?<div className="qf-border mt-4 grid gap-3 border-t pt-4 sm:grid-cols-2 xl:grid-cols-7"><select className={inputClass} value={status} onChange={e=>{setStatus(e.target.value as LeadStatus|"");setPage(1)}}><option value="">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={qualification} onChange={e=>{setQualification(e.target.value as LeadQualification|"");setPage(1)}}><option value="">All qualification</option>{qualifications.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={temperature} onChange={e=>{setTemperature(e.target.value as LeadTemperature|"");setPage(1)}}><option value="">All temperatures</option>{temperatures.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={priority} onChange={e=>{setPriority(e.target.value as LeadPriority|"");setPage(1)}}><option value="">All priorities</option>{priorities.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={source} onChange={e=>{setSource(e.target.value as LeadSource|"");setPage(1)}}><option value="">All sources</option>{sources.map(v=><option key={v}>{v}</option>)}</select>{canAssign?<select className={inputClass} value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="">All owners</option>{assignees.data?.data.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select>:null}<div className="flex gap-2"><input className={inputClass} type="number" min="0" max="100" value={scoreMin} onChange={e=>setScoreMin(e.target.value)} placeholder="Min score"/><button aria-label="Reset filters" onClick={reset} className="qf-icon-button shrink-0"><X className="h-4 w-4"/></button></div></div>:null}
    </Card>
    {selected.length?<Card className="mb-5 p-3"><div className="flex flex-wrap items-center gap-3"><b className="qf-text px-2 text-sm">{selected.length} selected</b>{canAssign?<select disabled={assigning} className={`${inputClass} max-w-64`} defaultValue="" onChange={e=>{const value=e.target.value;void assign(value==="__unassigned__"?"":value);e.currentTarget.value=""}}><option value="" disabled>Assign to…</option><option value="__unassigned__">Unassign</option>{assignees.data?.data.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select>:null}{canAssign?<button disabled={autoAssigning||assigning} className={secondaryButton} onClick={()=>void autoBalance()}><UserRoundCheck className="h-4 w-4"/>{autoAssigning?"Balancing…":"Auto-balance"}</button>:null}{canEdit?<select disabled={updating} className={`${inputClass} max-w-56`} defaultValue="" onChange={e=>{void updateStatus(e.target.value);e.currentTarget.value=""}}><option value="" disabled>Change status…</option>{statuses.map(v=><option key={v}>{v}</option>)}</select>:null}{canEmail?<button className={secondaryButton} onClick={()=>setShowEmail(true)}><Mail className="h-4 w-4"/>Email selected</button>:null}<button className="qf-muted ml-auto text-xs font-bold" onClick={()=>setSelected([])}>Clear selection</button></div></Card>:null}
    <Card>{list.isLoading?<div className="p-8 text-center qf-muted">Loading leads…</div>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-xs"><thead className="qf-surface-muted qf-muted text-[10px] uppercase tracking-wide"><tr><th className="px-4 py-3"><input type="checkbox" checked={all} onChange={e=>setSelected(e.target.checked?rows.map(x=>x._id):[])}/></th><th className="px-4 py-3">Lead</th><th className="px-4 py-3">Opportunity</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Qualification</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Follow-up</th><th className="px-4 py-3">Source</th></tr></thead><tbody className="qf-border divide-y">{rows.map(lead=><tr key={lead._id} className="hover:bg-[var(--qf-surface-muted)]"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(lead._id)} onChange={e=>setSelected(v=>e.target.checked?[...v,lead._id]:v.filter(id=>id!==lead._id))}/></td><td className="px-4 py-3"><Link href={`/lead-management/leads/${lead._id}`} className="qf-text font-black hover:text-blue-600">{lead.name}</Link><p className="qf-muted mt-1 max-w-52 truncate">{lead.company||lead.email}</p><p className="qf-muted mt-0.5 max-w-52 truncate text-[10px]">{lead.productInterest||lead.phone}</p></td><td className="px-4 py-3"><LeadScore lead={lead} compact/></td><td className="px-4 py-3"><StatusPill value={lead.status}/><div className="mt-2"><StatusPill value={lead.priority}/></div></td><td className="px-4 py-3"><StatusPill value={lead.qualification}/></td><td className="qf-text-secondary max-w-48 truncate px-4 py-3">{ownerLabel(lead.assignedTo)}</td><td className="px-4 py-3"><b className="qf-text">{formatMoney(lead.estimatedValue)}</b><p className="qf-muted mt-1">{lead.probability||0}% probability</p></td><td className="px-4 py-3"><span className={lead.nextFollowUpAt&&new Date(lead.nextFollowUpAt)<new Date()?"font-bold text-amber-600":"qf-muted"}>{formatDate(lead.nextFollowUpAt)}</span></td><td className="px-4 py-3"><span className="qf-muted">{lead.source}</span><p className="qf-muted mt-1">{formatDate(lead.createdAt)}</p></td></tr>)}</tbody></table></div>:<Empty title="No leads match this view" description="Try clearing filters, changing the quick view, or create a new lead."/>}
      {pagination&&pagination.totalPages>1?<div className="qf-border flex items-center justify-between border-t p-4"><p className="qf-muted text-xs">Page {pagination.page} of {pagination.totalPages} · {pagination.total} leads</p><div className="flex gap-2"><button className={secondaryButton} disabled={!pagination.hasPrev} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><button className={secondaryButton} disabled={!pagination.hasNext} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>:null}</Card>
    {showEmail?<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4"><Card className="w-full max-w-2xl"><div className="qf-border flex items-center justify-between border-b p-5"><div><h2 className="qf-text font-black">Email {selected.length} selected lead{selected.length===1?"":"s"}</h2><p className="qf-muted mt-1 text-xs">One-to-many delivery with each message logged against its lead.</p></div><button className="qf-icon-button" onClick={()=>setShowEmail(false)}><X className="h-4 w-4"/></button></div><div className="space-y-4 p-5"><Field label="Subject"><input className={inputClass} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Follow-up from Quantum Finix"/></Field><Field label="Message"><textarea className={textareaClass} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write the email message…"/></Field><div className="flex justify-end gap-2"><button className={secondaryButton} onClick={()=>setShowEmail(false)}>Cancel</button><button className={primaryButton} disabled={emailing||!subject.trim()||!message.trim()} onClick={()=>void sendBulk()}>{emailing?"Sending…":"Send & log email"}</button></div></div></Card></div>:null}
  </>;
}
