import type { ReactNode } from "react";
import type { Lead, LeadTemperature } from "@/src/lib/features/leads/lead-types";

export const inputClass = "qf-input h-11 w-full rounded-xl px-3 text-sm outline-none";
export const textareaClass = "qf-input min-h-28 w-full rounded-xl px-3 py-3 text-sm outline-none";
export const primaryButton = "qf-primary-button inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-black disabled:cursor-not-allowed disabled:opacity-50";
export const secondaryButton = "qf-secondary-button inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-black disabled:cursor-not-allowed disabled:opacity-50";

export function PageHeader({ eyebrow="Sales CRM", title, description, actions }: { eyebrow?: string; title: string; description: string; actions?: ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">{eyebrow}</p><h1 className="qf-text mt-2 text-3xl font-black tracking-tight">{title}</h1><p className="qf-muted mt-2 max-w-3xl text-sm leading-6">{description}</p></div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div>; }
export function Card({ children, className="" }: { children: ReactNode; className?: string }) { return <section className={`qf-surface qf-shadow rounded-2xl border ${className}`}>{children}</section>; }
export function CardHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="qf-border flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="qf-text text-base font-black">{title}</h2>{description ? <p className="qf-muted mt-1 text-xs leading-5">{description}</p> : null}</div>{actions}</div>; }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block"><span className="qf-text-secondary mb-1.5 block text-[11px] font-black">{label}</span>{children}{hint ? <span className="qf-muted mt-1 block text-[10px]">{hint}</span> : null}</label>; }
export function Metric({ label, value, helper }: { label: string; value: ReactNode; helper?: string }) { return <Card className="p-5"><p className="qf-muted text-[10px] font-black uppercase tracking-[.14em]">{label}</p><div className="qf-text mt-2 text-2xl font-black">{value}</div>{helper ? <p className="qf-muted mt-1 text-[11px]">{helper}</p> : null}</Card>; }
export function Empty({ title, description }: { title: string; description?: string }) { return <div className="p-10 text-center"><p className="qf-text font-black">{title}</p>{description ? <p className="qf-muted mx-auto mt-2 max-w-lg text-sm leading-6">{description}</p> : null}</div>; }
export function Loading({ rows=5 }: { rows?: number }) { return <div className="space-y-3">{Array.from({length:rows}).map((_,i)=><div key={i} className="qf-surface-muted h-16 animate-pulse rounded-xl border"/>)}</div>; }
export function StatusPill({ value }: { value: string }) { const classes = value === "Converted" || value === "SQL" ? "qf-status-success" : value === "Lost" || value === "Spam" || value === "Disqualified" ? "qf-status-danger" : value === "Hot" || value === "Urgent" ? "qf-status-warning" : value === "Qualified" || value === "Proposal Sent" || value === "Negotiation" ? "qf-status-info" : "qf-status-neutral"; return <span className={`${classes} inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black`}>{value}</span>; }
export function LeadScore({ lead, compact=false }: { lead: Pick<Lead,"score"|"temperature">; compact?: boolean }) { const score = Number.isFinite(Number(lead.score)) ? Math.max(0, Math.min(100, Number(lead.score))) : 0; return <div className={`flex items-center gap-2 ${compact ? "" : "rounded-xl bg-[var(--qf-surface-muted)] p-3"}`}><div className={`grid ${compact ? "h-9 w-9 text-xs" : "h-12 w-12 text-sm"} place-items-center rounded-full border-4 ${temperatureRing(lead.temperature)} font-black`}>{Math.round(score)}</div><div><StatusPill value={lead.temperature || "Cold"}/>{!compact ? <p className="qf-muted mt-1 text-[10px]">Opportunity score / 100</p> : null}</div></div>; }
export function formatMoney(value?: number) { return new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:0 }).format(Number.isFinite(Number(value)) ? Number(value) : 0); }
export function formatDate(value?: string) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString(); }
export function ownerLabel(value: Lead["assignedTo"]) { if (!value) return "Unassigned"; if (typeof value === "string") return value; return value.email || value.id || value._id || "Assigned"; }
function temperatureRing(value: LeadTemperature) { return value === "Hot" ? "border-amber-500" : value === "Warm" ? "border-blue-500" : "border-slate-300"; }
