"use client";
import Link from "next/link";
import { ArrowRight, Clock3, Flame, Mail, Plus, Target, UserRoundCheck } from "lucide-react";
import { useGetLeadsQuery, useGetLeadStatisticsQuery } from "@/src/lib/features/leads/lead-api";
import { Card, CardHeader, Empty, LeadScore, Loading, Metric, PageHeader, StatusPill, formatDate, formatMoney, ownerLabel, primaryButton, secondaryButton } from "./lead-ui";

export function LeadOverview() {
  const statsQ=useGetLeadStatisticsQuery(); const hotQ=useGetLeadsQuery({page:1,limit:6,temperature:"Hot",sortBy:"score",sortOrder:"desc"}); const followQ=useGetLeadsQuery({page:1,limit:6,followUpDue:true,sortBy:"nextFollowUpAt",sortOrder:"asc"}); const stats=statsQ.data?.data;
  return <><PageHeader title="Lead Management" description="A focused sales workspace for qualification, ownership, communication, follow-up and conversion. Opportunity scoring surfaces the leads most likely to deserve attention." actions={<><Link className={secondaryButton} href="/lead-management/leads">Open pipeline</Link><Link className={primaryButton} href="/lead-management/leads/new"><Plus className="h-4 w-4"/>Create lead</Link></>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Open pipeline" value={formatMoney(stats?.pipelineValue)} helper="Estimated value"/><Metric label="Hot leads" value={stats?.hotLeads ?? "—"} helper="High opportunity"/><Metric label="Qualified" value={stats?.qualified ?? "—"} helper="MQL + SQL"/><Metric label="Overdue follow-ups" value={stats?.overdueFollowUps ?? "—"} helper="Needs action"/><Metric label="Conversion rate" value={`${stats?.conversionRate ?? 0}%`} helper={`Avg score ${stats?.averageScore ?? 0}`}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><CardHeader title="High-opportunity leads" description="Prioritized by CRM opportunity score." actions={<Link className="qf-text-secondary inline-flex items-center gap-1 text-xs font-black" href="/lead-management/leads?view=hot">View all <ArrowRight className="h-3.5 w-3.5"/></Link>}/>{hotQ.isLoading?<div className="p-5"><Loading/></div>:hotQ.data?.data.length?<div className="divide-y qf-border">{hotQ.data.data.map(lead=><Link key={lead._id} href={`/lead-management/leads/${lead._id}`} className="flex items-center gap-4 p-4 hover:bg-[var(--qf-surface-muted)]"><LeadScore lead={lead} compact/><div className="min-w-0 flex-1"><b className="qf-text block truncate text-sm">{lead.name}</b><p className="qf-muted truncate text-xs">{lead.company || lead.productInterest || lead.purpose}</p><p className="qf-muted mt-1 truncate text-[10px]">Owner: {ownerLabel(lead.assignedTo)}</p></div><div className="text-right"><StatusPill value={lead.status}/><p className="qf-muted mt-2 text-[10px]">{formatMoney(lead.estimatedValue)}</p></div></Link>)}</div>:<Empty title="No hot leads yet" description="As qualification and engagement data grows, high-opportunity leads will appear here."/>}</Card>
    <Card><CardHeader title="Follow-up queue" description="Overdue actions that should be handled next." actions={<Link className="qf-text-secondary inline-flex items-center gap-1 text-xs font-black" href="/lead-management/leads?view=followups">Open queue <ArrowRight className="h-3.5 w-3.5"/></Link>}/>{followQ.isLoading?<div className="p-5"><Loading/></div>:followQ.data?.data.length?<div className="divide-y qf-border">{followQ.data.data.map(lead=><Link key={lead._id} href={`/lead-management/leads/${lead._id}`} className="flex items-center gap-4 p-4 hover:bg-[var(--qf-surface-muted)]"><span className="qf-status-warning grid h-10 w-10 place-items-center rounded-xl border"><Clock3 className="h-4 w-4"/></span><div className="min-w-0 flex-1"><b className="qf-text block truncate text-sm">{lead.name}</b><p className="qf-muted truncate text-xs">{lead.email}</p><p className="mt-1 text-[10px] font-bold text-amber-600">Due {formatDate(lead.nextFollowUpAt)}</p></div><StatusPill value={lead.priority}/></Link>)}</div>:<Empty title="No overdue follow-ups" description="Your current queue is clear."/>}</Card></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><Link href="/lead-management/leads?view=hot" className="qf-surface qf-shadow group rounded-2xl border p-5"><Flame className="h-5 w-5 text-amber-500"/><b className="qf-text mt-4 block">Prioritize opportunity</b><p className="qf-muted mt-1 text-xs leading-5">Review hot leads, score breakdown and qualification stage.</p></Link><Link href="/lead-management/leads" className="qf-surface qf-shadow group rounded-2xl border p-5"><UserRoundCheck className="h-5 w-5 text-blue-600"/><b className="qf-text mt-4 block">Assign ownership</b><p className="qf-muted mt-1 text-xs leading-5">Managers can route leads to sales staff and rebalance workloads.</p></Link><Link href="/lead-management/leads" className="qf-surface qf-shadow group rounded-2xl border p-5"><Mail className="h-5 w-5 text-blue-600"/><b className="qf-text mt-4 block">Communicate & convert</b><p className="qf-muted mt-1 text-xs leading-5">Email leads, log activity, notes, tasks and next follow-ups in context.</p></Link></div>
  </>;
}
