"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, Mail, MessageSquareText, Phone, Plus, Save, Trash2, UserRoundCheck } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useAddLeadActivityMutation,useAddLeadNoteMutation,useAssignLeadMutation,useCommunicateWithLeadMutation,useDeleteLeadMutation,useGetLeadAssigneesQuery,useGetLeadByIdQuery,useGetLeadDuplicatesQuery,useUpdateLeadMutation } from "@/src/lib/features/leads/lead-api";
import type { LeadActivityType,LeadPriority,LeadQualification,LeadSource,LeadStatus } from "@/src/lib/features/leads/lead-types";
import { Card,CardHeader,Empty,Field,LeadScore,PageHeader,StatusPill,formatDate,formatMoney,inputClass,ownerLabel,primaryButton,secondaryButton,textareaClass } from "./lead-ui";

const statuses:LeadStatus[]=["New","Attempting Contact","Contacted","Nurturing","Qualified","Proposal Sent","Negotiation","Converted","Lost","Spam"];
const quals:LeadQualification[]=["Unqualified","MQL","SQL","Disqualified"];
const priorities:LeadPriority[]=["Low","Medium","High","Urgent"];
const sources:LeadSource[]=["Website Form","Contact Page","Landing Page","Referral","Social Media","Campaign","Email Campaign","Paid Ads","Organic Search","Webinar","Partner","Outbound","Import","Manual","Other"];
const activityTypes:LeadActivityType[]=["call","meeting","task","whatsapp","sms","demo","other"];

export function LeadDetailWorkspace({id}:{id:string}){
 const router=useRouter(),me=useGetMeQuery(),detail=useGetLeadByIdQuery(id),lead=detail.data?.data;const perms=me.data?.data.permissions??[],elevated=me.data?.data.role==="super-admin"||perms.includes("leads.manage"),canAssign=elevated||perms.includes("lead-management.assign"),canEdit=elevated||perms.includes("lead-management.edit"),canEmail=elevated||perms.includes("lead-management.communicate"),canDelete=elevated||perms.includes("lead-management.delete");
 const assignees=useGetLeadAssigneesQuery(undefined,{skip:!canAssign});const duplicates=useGetLeadDuplicatesQuery({email:lead?.email,phone:lead?.phone,excludeId:id},{skip:!lead});const[update,{isLoading:saving}]=useUpdateLeadMutation(),[assign]=useAssignLeadMutation(),[note,{isLoading:noting}]=useAddLeadNoteMutation(),[communicate,{isLoading:sending}]=useCommunicateWithLeadMutation(),[addActivity,{isLoading:logging}]=useAddLeadActivityMutation(),[remove]=useDeleteLeadMutation();
 const[form,setForm]=useState({status:"New" as LeadStatus,qualification:"Unqualified" as LeadQualification,priority:"Medium" as LeadPriority,source:"Manual" as LeadSource,company:"",jobTitle:"",industry:"",website:"",companySize:"",productInterest:"",budget:"",timeline:"",estimatedValue:"0",probability:"0",purpose:"",location:"",internalSummary:"",tags:"",nextFollowUpAt:"",lostReason:"",disqualifiedReason:""});const[noteText,setNoteText]=useState("");const[email,setEmail]=useState({subject:"",message:"",nextFollowUpAt:""});const[activity,setActivity]=useState({type:"call" as LeadActivityType,title:"",description:"",outcome:"",dueAt:""});
 useEffect(()=>{if(!lead)return;setForm({status:lead.status,qualification:lead.qualification,priority:lead.priority,source:lead.source,company:lead.company??"",jobTitle:lead.jobTitle??"",industry:lead.industry??"",website:lead.website??"",companySize:lead.companySize??"",productInterest:lead.productInterest??"",budget:lead.budget??"",timeline:lead.timeline??"",estimatedValue:String(lead.estimatedValue??0),probability:String(lead.probability??0),purpose:lead.purpose,location:lead.location,internalSummary:lead.internalSummary??"",tags:(lead.tags??[]).join(", "),nextFollowUpAt:localDateTime(lead.nextFollowUpAt),lostReason:lead.lostReason??"",disqualifiedReason:lead.disqualifiedReason??""})},[lead?._id,lead?.updatedAt]);
 const timeline=useMemo(()=>{if(!lead)return[];return [...(lead.communications??[]).map(x=>({date:x.sentAt,type:x.kind==="email"?"Email":"Follow-up",title:x.subject||"Follow-up",body:x.message})),...(lead.notes??[]).map(x=>({date:x.createdAt,type:"Note",title:"Internal note",body:x.text})),...(lead.activities??[]).map(x=>({date:x.createdAt,type:x.type,title:x.title,body:x.description||x.outcome||"Activity logged"}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime())},[lead]);
 const set=(k:keyof typeof form,v:string)=>setForm(s=>({...s,[k]:v}));
 async function save(){try{await update({id,body:{status:form.status,qualification:form.qualification,priority:form.priority,source:form.source,company:form.company||null,jobTitle:form.jobTitle||null,industry:form.industry||null,website:form.website||null,companySize:form.companySize||null,productInterest:form.productInterest||null,budget:form.budget||null,timeline:form.timeline||null,estimatedValue:Number(form.estimatedValue)||0,probability:Math.max(0,Math.min(100,Number(form.probability)||0)),purpose:form.purpose,location:form.location,internalSummary:form.internalSummary||null,tags:form.tags.split(/[,;]/).map(x=>x.trim()).filter(Boolean),nextFollowUpAt:form.nextFollowUpAt?new Date(form.nextFollowUpAt).toISOString():null,lostReason:form.status==="Lost"?form.lostReason||null:null,disqualifiedReason:form.qualification==="Disqualified"?form.disqualifiedReason||null:null}}).unwrap();toast.success("Lead saved")}catch(e){toast.error(getApiErrorMessage(e))}}
 async function addNote(){if(!noteText.trim())return;try{await note({id,text:noteText.trim()}).unwrap();setNoteText("");toast.success("Note added")}catch(e){toast.error(getApiErrorMessage(e))}}
 async function send(){if(!email.message.trim()||!email.subject.trim())return;try{await communicate({id,kind:"email",subject:email.subject.trim(),message:email.message.trim(),...(email.nextFollowUpAt?{nextFollowUpAt:new Date(email.nextFollowUpAt).toISOString()}:{})}).unwrap();setEmail({subject:"",message:"",nextFollowUpAt:""});toast.success("Email sent and logged")}catch(e){toast.error(getApiErrorMessage(e))}}
 async function log(){if(!activity.title.trim())return;try{await addActivity({id,type:activity.type,title:activity.title.trim(),description:activity.description.trim()||undefined,outcome:activity.outcome.trim()||undefined,dueAt:activity.dueAt?new Date(activity.dueAt).toISOString():undefined}).unwrap();setActivity({type:"call",title:"",description:"",outcome:"",dueAt:""});toast.success("Activity logged")}catch(e){toast.error(getApiErrorMessage(e))}}
 async function del(){if(!confirm("Delete this lead permanently?"))return;try{await remove(id).unwrap();toast.success("Lead deleted");router.replace("/lead-management/leads")}catch(e){toast.error(getApiErrorMessage(e))}}
 if(detail.isLoading)return <div className="qf-muted p-10 text-center">Loading lead…</div>;if(!lead)return <Empty title="Lead unavailable" description={getApiErrorMessage(detail.error??"Lead not found")}/>;
 return <><PageHeader eyebrow="Lead record" title={lead.name} description={`${lead.company||"Individual lead"} · ${lead.email} · ${lead.phone}`} actions={<><Link className={secondaryButton} href="/lead-management/leads"><ArrowLeft className="h-4 w-4"/>Pipeline</Link>{canEdit?<button className={primaryButton} disabled={saving} onClick={()=>void save()}><Save className="h-4 w-4"/>{saving?"Saving…":"Save changes"}</button>:null}</>}/>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-6"><Card><div className="grid gap-4 p-5 md:grid-cols-[auto_1fr] md:items-center"><LeadScore lead={lead}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Pipeline" value={lead.status}/><Info label="Qualification" value={lead.qualification}/><Info label="Estimated value" value={formatMoney(lead.estimatedValue)}/><Info label="Probability" value={`${lead.probability||0}%`}/></div></div>{duplicates.data?.data.length?<div className="border-t border-amber-200 bg-amber-50/70 p-4 text-xs text-amber-800"><b>Possible duplicate detected.</b> {duplicates.data.data.map(d=><Link className="ml-2 underline" key={d._id} href={`/lead-management/leads/${d._id}`}>{d.name} ({d.status})</Link>)}</div>:null}</Card>
 <Card><CardHeader title="Contact & opportunity" description="Commercial context used for qualification and prioritization."/><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3"><F label="Company" value={form.company} set={v=>set("company",v)}/><F label="Job title" value={form.jobTitle} set={v=>set("jobTitle",v)}/><F label="Industry" value={form.industry} set={v=>set("industry",v)}/><F label="Website" value={form.website} set={v=>set("website",v)}/><F label="Company size" value={form.companySize} set={v=>set("companySize",v)}/><F label="Location" value={form.location} set={v=>set("location",v)}/><F label="Product / service" value={form.productInterest} set={v=>set("productInterest",v)}/><F label="Budget" value={form.budget} set={v=>set("budget",v)}/><F label="Timeline" value={form.timeline} set={v=>set("timeline",v)}/><F label="Estimated value" value={form.estimatedValue} set={v=>set("estimatedValue",v)} type="number"/><F label="Probability %" value={form.probability} set={v=>set("probability",v)} type="number"/><F label="Tags" value={form.tags} set={v=>set("tags",v)}/><div className="md:col-span-2 xl:col-span-3"><Field label="Requirement / purpose"><textarea className={textareaClass} value={form.purpose} onChange={e=>set("purpose",e.target.value)}/></Field></div><div className="md:col-span-2 xl:col-span-3"><Field label="Internal summary"><textarea className={textareaClass} value={form.internalSummary} onChange={e=>set("internalSummary",e.target.value)}/></Field></div></div></Card>
 {canEmail?<Card><CardHeader title="Email communication" description="Send directly to this lead. Every delivery is retained in the CRM activity history." actions={<Mail className="h-5 w-5 text-blue-600"/>}/><div className="grid gap-4 p-5 md:grid-cols-2"><div className="md:col-span-2"><Field label="Subject"><input className={inputClass} value={email.subject} onChange={e=>setEmail(v=>({...v,subject:e.target.value}))}/></Field></div><div className="md:col-span-2"><Field label="Email message"><textarea className={textareaClass} value={email.message} onChange={e=>setEmail(v=>({...v,message:e.target.value}))}/></Field></div><Field label="Schedule next follow-up"><input type="datetime-local" className={inputClass} value={email.nextFollowUpAt} onChange={e=>setEmail(v=>({...v,nextFollowUpAt:e.target.value}))}/></Field><div className="flex items-end"><button className={primaryButton} disabled={sending||!email.subject.trim()||!email.message.trim()} onClick={()=>void send()}>{sending?"Sending…":"Send email & log"}</button></div></div></Card>:null}
 <Card><CardHeader title="Notes & sales activity" description="Keep calls, meetings, tasks, demos, messages and internal context on the same timeline."/><div className="grid gap-6 p-5 xl:grid-cols-2"><div><h3 className="qf-text mb-3 text-sm font-black">Internal note</h3><textarea className={textareaClass} value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Add context visible to your team…"/><button className={`${secondaryButton} mt-3`} disabled={noting||!noteText.trim()} onClick={()=>void addNote()}><MessageSquareText className="h-4 w-4"/>Add note</button></div><div><h3 className="qf-text mb-3 text-sm font-black">Log activity</h3><div className="grid gap-3 sm:grid-cols-2"><select className={inputClass} value={activity.type} onChange={e=>setActivity(v=>({...v,type:e.target.value as LeadActivityType}))}>{activityTypes.map(v=><option key={v}>{v}</option>)}</select><input className={inputClass} value={activity.title} onChange={e=>setActivity(v=>({...v,title:e.target.value}))} placeholder="Activity title"/><input className={inputClass} value={activity.outcome} onChange={e=>setActivity(v=>({...v,outcome:e.target.value}))} placeholder="Outcome"/><input type="datetime-local" className={inputClass} value={activity.dueAt} onChange={e=>setActivity(v=>({...v,dueAt:e.target.value}))}/><textarea className={`${textareaClass} sm:col-span-2`} value={activity.description} onChange={e=>setActivity(v=>({...v,description:e.target.value}))} placeholder="Description / next action"/><button className={secondaryButton} disabled={logging||!activity.title.trim()} onClick={()=>void log()}><Plus className="h-4 w-4"/>Log activity</button></div></div></div></Card>
 <Card><CardHeader title="Activity timeline" description="Newest communication and sales activity first."/><div className="divide-y qf-border">{timeline.length?timeline.map((item,i)=><div key={`${item.date}-${i}`} className="p-5"><div className="flex flex-wrap items-center gap-2"><StatusPill value={item.type}/><b className="qf-text text-sm">{item.title}</b><span className="qf-muted ml-auto text-[10px]">{formatDate(item.date)}</span></div><p className="qf-text-secondary mt-2 whitespace-pre-wrap text-xs leading-6">{item.body}</p></div>):<Empty title="No activity yet"/>}</div></Card></div>
 <aside className="space-y-6"><Card><CardHeader title="Pipeline controls"/><div className="space-y-4 p-5"><Select label="Status" value={form.status} values={statuses} set={v=>set("status",v)}/><Select label="Qualification" value={form.qualification} values={quals} set={v=>set("qualification",v)}/><Select label="Priority" value={form.priority} values={priorities} set={v=>set("priority",v)}/><Select label="Source" value={form.source} values={sources} set={v=>set("source",v)}/><Field label="Next follow-up"><input type="datetime-local" className={inputClass} value={form.nextFollowUpAt} onChange={e=>set("nextFollowUpAt",e.target.value)}/></Field>{form.status==="Lost"?<Field label="Lost reason"><textarea required className={textareaClass} value={form.lostReason} onChange={e=>set("lostReason",e.target.value)}/></Field>:null}{form.qualification==="Disqualified"?<Field label="Disqualification reason"><textarea required className={textareaClass} value={form.disqualifiedReason} onChange={e=>set("disqualifiedReason",e.target.value)}/></Field>:null}</div></Card>
 <Card><CardHeader title="Ownership" description="Manager-controlled routing to sales users."/><div className="p-5"><p className="qf-muted mb-3 text-xs">Current owner</p><p className="qf-text mb-4 text-sm font-black">{ownerLabel(lead.assignedTo)}</p>{canAssign?<Field label="Assign owner"><select className={inputClass} value={ownerId(lead.assignedTo)} onChange={async e=>{try{await assign({id,assignedTo:e.target.value||null}).unwrap();toast.success("Owner updated")}catch(err){toast.error(getApiErrorMessage(err))}}}><option value="">Unassigned</option>{assignees.data?.data.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></Field>:<p className="qf-muted text-xs">Only a manager or user with assignment permission can reassign ownership.</p>}</div></Card>
 <Card><CardHeader title="Lead intelligence"/><div className="space-y-3 p-5"><ScoreLine label="Fit" value={lead.scoreBreakdown?.fit}/><ScoreLine label="Intent" value={lead.scoreBreakdown?.intent}/><ScoreLine label="Recency" value={lead.scoreBreakdown?.recency}/><ScoreLine label="Engagement" value={lead.scoreBreakdown?.engagement}/><div className="qf-border border-t pt-3"><Info label="Created" value={formatDate(lead.createdAt)}/><div className="mt-3"><Info label="Last activity" value={formatDate(lead.lastActivityAt)}/></div></div></div></Card>
 {canDelete?<button className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 text-sm font-black text-rose-700" onClick={()=>void del()}><Trash2 className="h-4 w-4"/>Delete lead</button>:null}</aside></div></>;
}
function Info({label,value}:{label:string;value:string}){return <div><p className="qf-muted text-[10px] font-black uppercase tracking-wide">{label}</p><p className="qf-text mt-1 text-sm font-bold">{value}</p></div>}
function F({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <Field label={label}><input type={type} className={inputClass} value={value} onChange={e=>set(e.target.value)}/></Field>}
function Select({label,value,values,set}:{label:string;value:string;values:readonly string[];set:(v:string)=>void}){return <Field label={label}><select className={inputClass} value={value} onChange={e=>set(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></Field>}
function ScoreLine({label,value}:{label:string;value?:number}){const safe=Number.isFinite(Number(value))?Number(value):0;return <div><div className="mb-1 flex justify-between text-[10px] font-bold"><span className="qf-text-secondary">{label}</span><span className="qf-muted">{safe}</span></div><div className="qf-surface-muted h-2 overflow-hidden rounded-full"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(0,Math.min(100,safe/30*100))}%`}}/></div></div>}
function ownerId(value:unknown){if(!value)return"";if(typeof value==="string")return value;const v=value as {_id?:string;id?:string};return v.id??v._id??""}
function localDateTime(value?:string){if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?"":new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
