"use client";
import { useState } from "react";
import { Download, FileSpreadsheet, Upload } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { downloadAdminFile } from "@/src/lib/download";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useGetLeadAssigneesQuery, useImportLeadsMutation } from "@/src/lib/features/leads/lead-api";
import type { LeadSource } from "@/src/lib/features/leads/lead-types";
import { Card, CardHeader, Field, PageHeader, inputClass, primaryButton, secondaryButton } from "./lead-ui";

const sources:LeadSource[]=["Website Form","Contact Page","Landing Page","Referral","Social Media","Campaign","Email Campaign","Paid Ads","Organic Search","Webinar","Partner","Outbound","Import","Manual","Other"];
export function LeadImportExport(){const me=useGetMeQuery();const perms=me.data?.data.permissions??[],elevated=me.data?.data.role==="super-admin"||perms.includes("leads.manage"),canAssign=elevated||perms.includes("lead-management.assign");const assignees=useGetLeadAssigneesQuery(undefined,{skip:!canAssign});const[runImport,{isLoading}]=useImportLeadsMutation();const[file,setFile]=useState<File|null>(null),[assignedTo,setAssignedTo]=useState(""),[source,setSource]=useState<LeadSource>("Import"),[skipDuplicates,setSkipDuplicates]=useState(true),[result,setResult]=useState<{totalRows:number;created:number;skippedDuplicates:number;invalid:number;errors:Array<{row:number;message:string}>}|null>(null);
async function submit(){if(!file)return;try{const fd=new FormData();fd.append("file",file);fd.append("source",source);fd.append("skipDuplicates",String(skipDuplicates));if(assignedTo)fd.append("assignedTo",assignedTo);const r=await runImport(fd).unwrap();setResult(r.data);toast.success(`${r.data.created} leads imported`)}catch(e){toast.error(getApiErrorMessage(e))}}
function template(){const csv="name,email,phone,company,job title,industry,product interest,budget,timeline,estimated value,status,priority,source,qualification,tags,location,purpose\nJane Doe,jane@example.com,+919999999999,Example Co,Head of Operations,Technology,HRMS,500000,30 days,500000,New,High,Import,MQL,enterprise;demo,Mumbai,Interested in enterprise HRMS\n";const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="quantumfinix-lead-import-template.csv";a.click();URL.revokeObjectURL(url)}
async function exp(format:"xlsx"|"csv"|"json"){try{await downloadAdminFile("/lead/admin/export",`quantumfinix-leads.${format}`,{format})}catch(e){toast.error(getApiErrorMessage(e))}}
return <><PageHeader title="Import & Export" description="Move lead data in and out of the CRM with ownership and duplicate controls. Imports support spreadsheet and structured-text formats without changing the public lead-capture flow."/>
<div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader title="Import leads" description="Supported: XLSX, CSV, TSV, JSON, NDJSON / JSONL. Maximum 5,000 rows and 10 MB per import." actions={<Upload className="h-5 w-5 text-blue-600"/>}/><div className="space-y-4 p-5"><Field label="Lead file"><label className="qf-surface-muted flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed p-5 text-center"><FileSpreadsheet className="h-7 w-7 text-blue-600"/><b className="qf-text mt-3 text-sm">{file?.name||"Choose lead file"}</b><span className="qf-muted mt-1 text-xs">.xlsx .csv .tsv .json .ndjson .jsonl</span><input type="file" accept=".xlsx,.csv,.tsv,.json,.ndjson,.jsonl" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/></label></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Default source"><select className={inputClass} value={source} onChange={e=>setSource(e.target.value as LeadSource)}>{sources.map(v=><option key={v}>{v}</option>)}</select></Field>{canAssign?<Field label="Assign imported leads"><select className={inputClass} value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Keep unassigned</option>{assignees.data?.data.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></Field>:null}</div><label className="qf-text-secondary flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={skipDuplicates} onChange={e=>setSkipDuplicates(e.target.checked)}/>Skip possible duplicates by email or phone</label><div className="flex flex-wrap gap-2"><button className={secondaryButton} onClick={template}><Download className="h-4 w-4"/>Download CSV template</button><button className={primaryButton} disabled={!file||isLoading} onClick={()=>void submit()}>{isLoading?"Importing…":"Import leads"}</button></div></div>{result?<div className="qf-border border-t p-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Rows",result.totalRows],["Created",result.created],["Duplicates",result.skippedDuplicates],["Invalid",result.invalid]].map(([label,value])=><div key={String(label)} className="qf-surface-muted rounded-xl border p-3"><p className="qf-muted text-[10px] font-black uppercase">{label}</p><b className="qf-text mt-1 block text-xl">{value}</b></div>)}</div>{result.errors.length?<div className="mt-4 max-h-44 overflow-auto rounded-xl border border-rose-200 bg-rose-50/60 p-3 text-xs text-rose-700">{result.errors.map((e,i)=><p key={i}>Row {e.row}: {e.message}</p>)}</div>:null}</div>:null}</Card>
<Card><CardHeader title="Export CRM data" description="Create portable snapshots for analysis, backup or downstream tools." actions={<Download className="h-5 w-5 text-blue-600"/>}/><div className="space-y-4 p-5"><ExportOption title="Excel workbook" description="Best for managers and spreadsheet analysis." action="Export .xlsx" onClick={()=>void exp("xlsx")}/><ExportOption title="CSV" description="Universal tabular format for CRM migrations and data tools." action="Export .csv" onClick={()=>void exp("csv")}/><ExportOption title="JSON" description="Structured format for integrations, data engineering and archives." action="Export .json" onClick={()=>void exp("json")}/><div className="qf-surface-muted rounded-xl border p-4"><p className="qf-text text-sm font-black">Import mapping</p><p className="qf-muted mt-2 text-xs leading-6">The importer recognizes common CRM column names such as lead name, email, mobile, company, job title, industry, product/service, deal value, status, priority, source, qualification and tags. Name, email and phone are required.</p></div></div></Card></div></>}
function ExportOption({title,description,action,onClick}:{title:string;description:string;action:string;onClick:()=>void}){return <div className="qf-surface-muted flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><b className="qf-text text-sm">{title}</b><p className="qf-muted mt-1 text-xs">{description}</p></div><button className={secondaryButton} onClick={onClick}>{action}</button></div>}
