"use client";

import { useEffect, useState } from "react";
import { GripVertical, Layers3, Plus, Search, X } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useBulkPMTasksMutation, useGetPMProjectQuery, useGetPMSprintsQuery, useGetPMTasksQuery, useReorderPMTasksMutation } from "@/src/lib/features/product-management/product-management-api";
import type { PMTask, PMUser } from "@/src/lib/features/product-management/product-management-types";
import { AsyncUserPicker, Card, Empty, PageHeader, Pagination, PriorityBadge, StatusBadge, inputClass, primaryButton, secondaryButton, userLabel } from "./pm-ui";
import { WorkItemDrawer } from "./work-item-drawer";

type BacklogFilters={search:string;type:string;priority:string;label:string;assignee?:string};

export function PMBacklogPage({projectId}:{projectId:string}){
  const me=useGetMeQuery().data?.data;const canManage=!!me&&(me.role==="super-admin"||me.role==="product-admin"||(me.permissions??[]).includes("product-management.work.manage"));
  const projectQ=useGetPMProjectQuery(projectId),sprintsQ=useGetPMSprintsQuery(projectId);
  const [search,setSearch]=useState(""),[debounced,setDebounced]=useState(""),[priority,setPriority]=useState(""),[type,setType]=useState(""),[label,setLabel]=useState(""),[assignee,setAssignee]=useState<PMUser|undefined>();
  const [selected,setSelected]=useState<string[]>([]),[taskId,setTaskId]=useState(""),[newItem,setNewItem]=useState(false);
  const [bulk]=useBulkPMTasksMutation();
  const statuses=projectQ.data?.data.workflow?.statuses??[];
  useEffect(()=>{const id=setTimeout(()=>setDebounced(search.trim()),250);return()=>clearTimeout(id)},[search]);
  const filters:BacklogFilters={search:debounced,type,priority,label,assignee:assignee?._id};
  async function doBulk(updates:Record<string,unknown>){try{await bulk({taskIds:selected,updates}).unwrap();toast.success("Backlog updated");setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  const hasFilters=Boolean(search||type||priority||label||assignee);
  return <>
    <PageHeader eyebrow="Project / Planning" title="Backlog" description="Server-paged epics, unscheduled work and planned sprint scope with drag ranking, advanced filters, quick create and bulk planning." actions={canManage?<button className={primaryButton} onClick={()=>setNewItem(true)}><Plus className="h-4 w-4"/>Quick create</button>:undefined}/>
    <Card className="mb-4 p-4"><div className="grid gap-3 xl:grid-cols-[1fr_200px_180px_190px_240px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search key, title, description or label"/></div><select className={inputClass} value={type} onChange={e=>setType(e.target.value)}><option value="">All work types</option>{["Epic","Story","Task","Bug","Subtask"].map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{["Low","Medium","High","Urgent","Critical"].map(v=><option key={v}>{v}</option>)}</select><input className={inputClass} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Label"/><AsyncUserPicker projectId={projectId} value={assignee?._id} onChange={(_,u)=>setAssignee(u)} label="All assignees"/></div>{hasFilters&&<button className="mt-3 inline-flex items-center gap-1 text-xs font-black text-rose-600" onClick={()=>{setSearch("");setDebounced("");setType("");setPriority("");setLabel("");setAssignee(undefined)}}><X className="h-3.5 w-3.5"/>Clear filters</button>}</Card>
    {canManage&&selected.length>0&&<BacklogBulk projectId={projectId} selected={selected} statuses={statuses} sprints={sprintsQ.data?.data??[]} apply={doBulk} clear={()=>setSelected([])}/>} 
    <EpicStrip projectId={projectId} filters={filters} onOpen={setTaskId}/>
    <div className="mt-5 grid gap-5 2xl:grid-cols-2"><BacklogList projectId={projectId} title="Unscheduled backlog" description="Prioritized work with no sprint assignment." sprintState="backlog" filters={filters} selected={selected} setSelected={setSelected} canManage={canManage} onOpen={setTaskId}/><BacklogList projectId={projectId} title="Planned sprint work" description="Work already committed to a planned or active sprint." sprintState="planned" filters={filters} selected={selected} setSelected={setSelected} canManage={canManage} onOpen={setTaskId}/></div>
    <WorkItemDrawer projectId={projectId} taskId={taskId||undefined} newItem={newItem} onClose={()=>{setTaskId("");setNewItem(false)}}/>
  </>;
}

function EpicStrip({projectId,filters,onOpen}:{projectId:string;filters:BacklogFilters;onOpen:(id:string)=>void}){
  const q=useGetPMTasksQuery({projectId,type:"Epic",search:filters.search||undefined,priority:filters.priority||undefined,label:filters.label||undefined,assignee:filters.assignee,archived:false,page:1,limit:20,sort:"rank",order:"asc"});
  const rows=q.data?.data??[];
  return <Card><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><h2 className="flex items-center gap-2 font-black"><Layers3 className="h-4 w-4 text-violet-600"/>Epics</h2><p className="mt-1 text-xs text-slate-500">High-level backlog containers and their planning status.</p></div><span className="text-[10px] font-black text-slate-400">{q.data?.pagination?.total??rows.length} total</span></div><div className="flex gap-3 overflow-x-auto p-4">{rows.map(t=><button key={t._id} onClick={()=>onOpen(t._id)} className="min-w-64 rounded-xl border border-violet-100 bg-violet-50/60 p-3 text-left"><div className="flex items-center justify-between"><b className="text-[10px] text-violet-700">{t.key}</b><PriorityBadge value={t.priority}/></div><p className="mt-2 line-clamp-2 text-xs font-black text-slate-800">{t.title}</p><div className="mt-3 flex items-center justify-between text-[10px] text-slate-500"><span>{t.storyPoints} pts</span><StatusBadge value={t.status}/></div></button>)}{!rows.length&&<div className="w-full"><Empty title="No epics match these filters"/></div>}</div></Card>;
}

function BacklogList({projectId,title,description,sprintState,filters,selected,setSelected,canManage,onOpen}:{projectId:string;title:string;description:string;sprintState:"backlog"|"planned";filters:BacklogFilters;selected:string[];setSelected:(v:string[])=>void;canManage:boolean;onOpen:(id:string)=>void}){
  const [page,setPage]=useState(1),[dragId,setDragId]=useState("");
  useEffect(()=>setPage(1),[filters.search,filters.type,filters.priority,filters.label,filters.assignee,sprintState]);
  const q=useGetPMTasksQuery({projectId,sprintState,search:filters.search||undefined,type:filters.type||undefined,priority:filters.priority||undefined,label:filters.label||undefined,assignee:filters.assignee,archived:false,page,limit:50,sort:"rank",order:"asc"});
  const rows=q.data?.data??[],pg=q.data?.pagination,[reorder]=useReorderPMTasksMutation();
  async function move(drag:string,target:string){if(!drag||drag===target)return;const ids=rows.map(x=>x._id),from=ids.indexOf(drag),to=ids.indexOf(target);if(from<0||to<0)return;ids.splice(to,0,...ids.splice(from,1));try{await reorder({projectId,orderedTaskIds:ids}).unwrap();toast.success("Backlog rank updated")}catch(e){toast.error(getApiErrorMessage(e))}}
  const pageSelected=rows.length>0&&rows.every(r=>selected.includes(r._id));
  return <Card><div className="flex items-start justify-between gap-3 border-b border-slate-100 p-4"><div><h2 className="font-black">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p></div>{canManage&&<label className="flex items-center gap-2 text-[10px] font-black text-slate-500"><input type="checkbox" checked={pageSelected} onChange={()=>setSelected(pageSelected?selected.filter(id=>!rows.some(r=>r._id===id)):[...new Set([...selected,...rows.map(r=>r._id)])])}/>Select page · {pg?.total??rows.length}</label>}</div>{rows.length?<div className="divide-y divide-slate-100">{rows.map(t=><div key={t._id} draggable={canManage} onDragStart={()=>{if(canManage)setDragId(t._id)}} onDragOver={e=>{if(canManage)e.preventDefault()}} onDrop={()=>{if(canManage)void move(dragId,t._id)}} className="grid grid-cols-[24px_22px_1fr_auto] items-center gap-2 px-3 py-3 hover:bg-slate-50">{canManage?<><GripVertical className="h-4 w-4 cursor-grab text-slate-300"/><input type="checkbox" checked={selected.includes(t._id)} onChange={()=>setSelected(selected.includes(t._id)?selected.filter(x=>x!==t._id):[...selected,t._id])}/></>:<><span/><span/></>}<button onClick={()=>onOpen(t._id)} className="min-w-0 text-left"><b className="block truncate text-xs text-slate-900">{t.key} · {t.title}</b><span className="mt-1 flex flex-wrap items-center gap-2 text-[10px] text-slate-400"><span>{t.type}</span><span>{userLabel(t.assignee)}</span><span>{t.storyPoints} pts</span>{t.labels?.slice(0,2).map(l=><span key={l} className="rounded bg-violet-50 px-1.5 py-.5 text-violet-600">{l}</span>)}</span></button><div className="flex items-center gap-2"><PriorityBadge value={t.priority}/><StatusBadge value={t.status}/></div></div>)}</div>:<Empty title={q.isLoading?"Loading…":"Nothing here"}/>} {pg&&pg.totalPages>1&&<Pagination page={pg.page} totalPages={pg.totalPages} onPage={setPage}/>}</Card>;
}

function BacklogBulk({projectId,selected,statuses,sprints,apply,clear}:{projectId:string;selected:string[];statuses:string[];sprints:Array<{_id:string;name:string;status?:string}>;apply:(u:Record<string,unknown>)=>Promise<void>;clear:()=>void}){const [assignee,setAssignee]=useState<PMUser|undefined>();return <Card className="mb-4 border-blue-200 bg-blue-50/60 p-3"><div className="flex flex-wrap items-center gap-2"><b className="mr-2 text-xs text-blue-800">{selected.length} selected</b><select className={`${inputClass} w-48`} defaultValue="" onChange={e=>e.target.value&&void apply({status:e.target.value})}><option value="">Bulk status…</option>{statuses.map(v=><option key={v}>{v}</option>)}</select><select className={`${inputClass} w-48`} defaultValue="" onChange={e=>void apply({sprintId:e.target.value||null})}><option value="">Move to backlog</option>{sprints.filter(s=>s.status!=="completed").map(v=><option key={v._id} value={v._id}>{v.name}</option>)}</select><div className="min-w-60"><AsyncUserPicker projectId={projectId} value={assignee?._id} onChange={(_,u)=>setAssignee(u)} label="Bulk assignee"/></div><button className={secondaryButton} disabled={!assignee} onClick={()=>void apply({assignee:assignee?._id})}>Assign</button><button className={secondaryButton} onClick={clear}><X className="h-4 w-4"/>Clear</button></div></Card>}
