"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, FolderKanban, Plus, Trash2, Users, Workflow } from "lucide-react";
import toast from "react-hot-toast";
import { useCreatePMProjectMutation } from "@/src/lib/features/product-management/product-management-api";
import type { PMCustomFieldDefinition, PMUser, PMWorkflowTransition } from "@/src/lib/features/product-management/product-management-types";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { AsyncUserPicker, Card, Field, PageHeader, inputClass, primaryButton, secondaryButton, textareaClass } from "./pm-ui";
const steps=['Basics','Team','Workflow','Custom fields'];
const defaults=['Backlog','To Do','In Progress','In Review','QA','Blocked','Ready for Release','Done'];
const defaultTransitions:PMWorkflowTransition[]=[['Backlog','To Do'],['To Do','In Progress'],['In Progress','In Review'],['In Review','QA'],['QA','Ready for Release'],['Ready for Release','Done']].map(([from,to])=>({from,to,rules:{}}));
export function PMCreateProjectPage(){
 const router=useRouter(),[create,{isLoading}]=useCreatePMProjectMutation();const [step,setStep]=useState(0),[members,setMembers]=useState<PMUser[]>([]),[statuses,setStatuses]=useState(defaults),[transitions,setTransitions]=useState<PMWorkflowTransition[]>(defaultTransitions),[customFields,setCustomFields]=useState<PMCustomFieldDefinition[]>([]),[newStatus,setNewStatus]=useState('');
 const [form,setForm]=useState({name:'',key:'',description:'',lead:'',productOwner:'',projectManager:'',teamLead:'',projectType:'scrum',visibility:'team',startDate:'',targetDate:'',clientName:''});
 const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();if(step<steps.length-1){setStep(v=>v+1);return}try{const res=await create({name:form.name,key:form.key.toUpperCase(),description:form.description||undefined,lead:form.projectManager||form.lead||undefined,productOwner:form.productOwner||undefined,projectManager:form.projectManager||undefined,teamLead:form.teamLead||undefined,members:members.map(x=>x._id),projectType:form.projectType,visibility:form.visibility,startDate:form.startDate||undefined,targetDate:form.targetDate||undefined,clientName:form.clientName||undefined,workflow:{statuses,transitions},customFields}).unwrap();toast.success('Project created');router.push(`/product-management/projects/${res.data._id}`)}catch(err){toast.error(getApiErrorMessage(err))}}
 function addField(){setCustomFields(v=>[...v,{key:`field_${v.length+1}`,name:`Custom field ${v.length+1}`,type:'text'}])}
 return <><PageHeader eyebrow="Projects / New" title="Create project" description="A complete project wizard for methodology, ownership, team, workflow, visibility and custom fields."/><div className="mx-auto max-w-5xl"><div className="mb-5 grid grid-cols-2 gap-2 md:grid-cols-4">{steps.map((s,i)=><button type="button" key={s} onClick={()=>i<step&&setStep(i)} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black ${i===step?'border-blue-200 bg-blue-50 text-blue-700':i<step?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-white text-slate-400'}`}>{i<step?<Check className="h-4 w-4"/>:<span className="grid h-5 w-5 place-items-center rounded-full border border-current text-[9px]">{i+1}</span>}{s}</button>)}</div><form onSubmit={submit}><Card className="p-6">
 {step===0&&<div><Section icon={FolderKanban} title="Basic information" text="Identity, schedule, methodology and client context."/><div className="grid gap-4 md:grid-cols-2"><Field label="Project name" required><input required className={inputClass} value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Customer Portal V3"/></Field><Field label="Project key" required hint="2–12 letters/numbers, starts with a letter."><input required maxLength={12} pattern="[A-Za-z][A-Za-z0-9]{1,11}" className={inputClass} value={form.key} onChange={e=>set('key',e.target.value.toUpperCase())} placeholder="CPV3"/></Field><div className="md:col-span-2"><Field label="Description"><textarea className={textareaClass} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Outcome, scope, success criteria and important constraints…"/></Field></div><Field label="Project type"><select className={inputClass} value={form.projectType} onChange={e=>set('projectType',e.target.value)}><option value="scrum">Scrum</option><option value="kanban">Kanban</option><option value="general">General project</option></select></Field><Field label="Visibility"><select className={inputClass} value={form.visibility} onChange={e=>set('visibility',e.target.value)}><option value="private">Private</option><option value="team">Team</option><option value="organization">Organization</option><option value="client">Client-visible</option></select></Field><Field label="Start date"><input type="date" className={inputClass} value={form.startDate} onChange={e=>set('startDate',e.target.value)}/></Field><Field label="Target completion"><input type="date" min={form.startDate||undefined} className={inputClass} value={form.targetDate} onChange={e=>set('targetDate',e.target.value)}/></Field><div className="md:col-span-2"><Field label="Client / customer (optional)"><input className={inputClass} value={form.clientName} onChange={e=>set('clientName',e.target.value)} placeholder="Linked customer or account"/></Field></div></div></div>}
 {step===1&&<div><Section icon={Users} title="Project team" text="Search server-side by name/email. Plain user accounts and ineligible roles are excluded by the backend."/><div className="grid gap-5 md:grid-cols-2"><Field label="Product owner"><AsyncUserPicker value={form.productOwner} onChange={id=>set('productOwner',id)} label="Search product owner"/></Field><Field label="Project manager"><AsyncUserPicker value={form.projectManager} onChange={id=>{set('projectManager',id);set('lead',id)}} label="Search project manager"/></Field><Field label="Team lead"><AsyncUserPicker value={form.teamLead} onChange={id=>set('teamLead',id)} label="Search team lead"/></Field><Field label="Members"><AsyncUserPicker multiple values={members} onValuesChange={setMembers} label="Search and select members"/></Field></div></div>}
 {step===2&&<div><Section icon={Workflow} title="Workflow" text="Define project-specific statuses, transitions and transition rules before the first work item is created."/><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div><Field label="Statuses"><div className="space-y-2">{statuses.map((s,i)=><div key={`${s}-${i}`} className="flex gap-2"><input className={inputClass} value={s} onChange={e=>setStatuses(v=>v.map((x,j)=>j===i?e.target.value:x))}/><button type="button" disabled={statuses.length<=1} onClick={()=>{setStatuses(v=>v.filter((_,j)=>j!==i));setTransitions(v=>v.filter(t=>t.from!==s&&t.to!==s))}} className="grid h-11 w-11 place-items-center rounded-xl border border-rose-200 text-rose-500 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="mt-2 flex gap-2"><input className={inputClass} value={newStatus} onChange={e=>setNewStatus(e.target.value)} placeholder="New status"/><button type="button" className={secondaryButton} onClick={()=>{const s=newStatus.trim();if(s&&!statuses.includes(s)){setStatuses(v=>[...v,s]);setNewStatus('')}}}><Plus className="h-4 w-4"/>Add</button></div></Field></div><div><Field label="Allowed transitions"><div className="space-y-2">{transitions.map((t,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><select className={inputClass} value={t.from} onChange={e=>setTransitions(v=>v.map((x,j)=>j===i?{...x,from:e.target.value}:x))}>{statuses.map(s=><option key={s}>{s}</option>)}</select><select className={inputClass} value={t.to} onChange={e=>setTransitions(v=>v.map((x,j)=>j===i?{...x,to:e.target.value}:x))}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button type="button" onClick={()=>setTransitions(v=>v.filter((_,j)=>j!==i))} className="grid h-11 w-11 place-items-center rounded-xl border border-rose-200 text-rose-500"><Trash2 className="h-4 w-4"/></button></div>)}</div><button type="button" className={`${secondaryButton} mt-2`} onClick={()=>setTransitions(v=>[...v,{from:statuses[0],to:statuses[Math.min(1,statuses.length-1)],rules:{}}])}><Plus className="h-4 w-4"/>Transition</button></Field></div></div><p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Fine-grained rules such as required reviewer, estimate, acceptance, allowed roles and release authority can be edited in Project Settings after creation.</p></div>}
 {step===3&&<div><Section icon={Plus} title="Custom work fields" text="Optional project-specific fields are validated server-side when work items are created or updated."/><div className="space-y-3">{customFields.map((f,i)=><div key={i} className="grid gap-2 rounded-xl border border-slate-200 p-3 md:grid-cols-[1fr_1fr_170px_auto]"><input className={inputClass} value={f.name} onChange={e=>setCustomFields(v=>v.map((x,j)=>j===i?{...x,name:e.target.value}:x))} placeholder="Field label"/><input className={inputClass} value={f.key} onChange={e=>setCustomFields(v=>v.map((x,j)=>j===i?{...x,key:e.target.value.replace(/\s+/g,'_')}:x))} placeholder="field_key"/><select className={inputClass} value={f.type} onChange={e=>setCustomFields(v=>v.map((x,j)=>j===i?{...x,type:e.target.value as PMCustomFieldDefinition['type']}:x))}><option value="text">Text</option><option value="number">Number</option><option value="date">Date</option><option value="select">Select</option><option value="multi-select">Multi-select</option><option value="boolean">Boolean</option><option value="url">URL</option></select><button type="button" onClick={()=>setCustomFields(v=>v.filter((_,j)=>j!==i))} className="grid h-11 w-11 place-items-center rounded-xl border border-rose-200 text-rose-500"><Trash2 className="h-4 w-4"/></button><label className="md:col-span-4 flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={!!f.required} onChange={e=>setCustomFields(v=>v.map((x,j)=>j===i?{...x,required:e.target.checked}:x))}/>Required field</label></div>)}{!customFields.length&&<div className="rounded-xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-400">No custom fields. They can also be added later.</div>}</div><button type="button" className={`${secondaryButton} mt-3`} onClick={addField}><Plus className="h-4 w-4"/>Add custom field</button></div>}
 <div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-5"><button type="button" onClick={()=>step?setStep(v=>v-1):router.back()} className={secondaryButton}><ArrowLeft className="h-4 w-4"/>{step?'Back':'Cancel'}</button><button disabled={isLoading} className={primaryButton}>{step<steps.length-1?'Continue':'Create project'}{step<steps.length-1?<ArrowRight className="h-4 w-4"/>:<Check className="h-4 w-4"/>}</button></div>
 </Card></form></div></>
}
function Section({icon:Icon,title,text}:{icon:typeof FolderKanban;title:string;text:string}){return <div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon className="h-5 w-5"/></span><div><h2 className="font-black">{title}</h2><p className="text-xs text-slate-500">{text}</p></div></div>}
