"use client";

import Link from "next/link";
import { Activity, ArrowRight, CalendarClock, MessageSquareText, Plus, Rocket, ShieldAlert, Sparkles, Target, Users, Zap } from "lucide-react";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useGetPMOverviewQuery, useGetPMPerformanceQuery } from "@/src/lib/features/product-management/product-management-api";
import { Card, CardHeader, Empty, PageHeader, Progress, Stat, StatusBadge } from "./pm-ui";

export function PMOverviewPage(){
  const q=useGetPMOverviewQuery(),me=useGetMeQuery().data?.data,d=q.data?.data,isClient=me?.role==="client-viewer";
  const perfQ=useGetPMPerformanceQuery(undefined,{skip:isClient});
  const permissions=me?.permissions??[],full=me?.role==="super-admin"||me?.role==="product-admin";
  const has=(p:string)=>full||permissions.includes(p);
  const firstProject=d?.projects?.[0];
  if(q.isLoading)return <Loading/>;

  if(isClient)return <><PageHeader title="Product Management" description="Your permitted client-facing projects, published release information, delivery approvals and project communication." actions={<Link href="/product-management/chat" className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><MessageSquareText className="h-4 w-4"/>Open chat</Link>}/><div className="grid gap-4 sm:grid-cols-3"><Stat label="Accessible projects" value={d?.projectCount??0} detail="Client-visible scope" tone="violet"/><Stat label="Approvals pending" value={d?.deliveries.length??0} detail="Delivery decisions" tone="amber"/><Stat label="Published releases" value={d?.releases.length??0} detail="Release pipeline" tone="blue"/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><ProjectsCard projects={d?.projects??[]}/><ReleaseCard releases={d?.releases??[]}/></div></>;

  return <>
    <PageHeader title="Product Management" description="A focused light-theme command center for your work, project health, sprint delivery, release risk and role-appropriate performance—not an overloaded all-in-one page." actions={<QuickActions projectId={firstProject?._id} has={has}/>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Assigned to me" value={d?.myWork.assigned??0} detail={`${d?.myWork.dueToday??0} due today`} tone="blue"/><Stat label="Overdue" value={d?.myWork.overdue??0} detail="Needs attention" tone="rose"/><Stat label="Waiting review" value={d?.myWork.waitingReview??0} detail="Review queue" tone="amber"/><Stat label="Active projects" value={d?.projectCount??0} detail="Role-filtered workspace" tone="violet"/><Stat label="Projects at risk" value={d?.projectsAtRisk??0} detail="Blocked, overdue or late" tone="rose"/><Stat label="Upcoming deadlines" value={d?.upcomingDeadlines?.length??0} detail="Nearest project targets" tone="teal"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><ProjectsCard projects={d?.projects??[]}/><Card><CardHeader title="Active sprint" description="Committed, completed and remaining sprint work."/><div className="p-5">{d?.sprint?<SprintSummary sprint={d.sprint}/>:<Empty title="No active sprint" description="Start a sprint from a project sprint page."/>}</div></Card></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><DeadlineCard projects={d?.upcomingDeadlines??[]}/><PerformanceCard data={perfQ.data?.data}/><Card><CardHeader title="Attention required" description="Signals that can affect delivery."/><div className="grid gap-3 p-5"><Signal icon={ShieldAlert} title="Overdue work" value={d?.myWork.overdue??0} tone="rose"/><Signal icon={Users} title="Client approvals pending" value={d?.deliveries.length??0} tone="amber"/><Signal icon={CalendarClock} title="Review queue" value={d?.myWork.waitingReview??0} tone="blue"/></div></Card></div>
    <div className="mt-6"><ReleaseCard releases={d?.releases??[]}/></div>
  </>;
}

function QuickActions({projectId,has}:{projectId?:string;has:(p:string)=>boolean}){return <div className="flex flex-wrap gap-2">{has("product-management.projects.manage")&&<Link href="/product-management/projects/new" className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>Create project</Link>}{projectId&&has("product-management.work.manage")&&<Link href={`/product-management/projects/${projectId}/tasks?new=1`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 text-sm font-black text-emerald-700"><Zap className="h-4 w-4"/>Create work item</Link>}{projectId&&has("product-management.sprints.manage")&&<Link href={`/product-management/projects/${projectId}/sprints`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-violet-200 bg-violet-50 px-4 text-sm font-black text-violet-700"><Target className="h-4 w-4"/>Sprints</Link>}{projectId&&has("product-management.releases.manage")&&<Link href={`/product-management/projects/${projectId}/releases`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 text-sm font-black text-amber-700"><Rocket className="h-4 w-4"/>Releases</Link>}<Link href="/product-management/my-work" className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700"><Target className="h-4 w-4"/>My Work</Link>{has("product-management.chat.use")&&<Link href="/product-management/chat" className="inline-flex h-11 items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 text-sm font-black text-sky-700"><MessageSquareText className="h-4 w-4"/>Chat</Link>}</div>}
function ProjectsCard({projects}:{projects:Array<{_id:string;key:string;name:string;projectType?:string;targetDate?:string}>}){return <Card><CardHeader title="Recently active projects" description="Recently opened/active permitted projects and target dates." action={<Link href="/product-management/projects" className="text-xs font-black text-blue-600">View all</Link>}/><div className="divide-y divide-slate-100">{projects.length?projects.map(p=><Link key={p._id} href={`/product-management/projects/${p._id}`} className="flex items-center gap-4 px-5 py-4 hover:bg-slate-50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-sm font-black text-violet-700">{p.key.slice(0,2)}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-slate-900">{p.name}</b><span className="mt-1 block text-xs text-slate-400">{p.key} · {p.projectType??"project"}{p.targetDate?` · target ${new Date(p.targetDate).toLocaleDateString()}`:""}</span></span><ArrowRight className="h-4 w-4 text-slate-300"/></Link>):<Empty title="No permitted projects"/>}</div></Card>}
function DeadlineCard({projects}:{projects:Array<{_id:string;key:string;name:string;targetDate?:string}>}){return <Card><CardHeader title="Upcoming project deadlines" description="Nearest target completion dates."/><div className="divide-y divide-slate-100">{projects.slice(0,6).map(p=><Link href={`/product-management/projects/${p._id}`} key={p._id} className="flex items-center gap-3 p-4 hover:bg-slate-50"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><CalendarClock className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{p.key} · {p.name}</b><span className="text-[10px] text-slate-400">{p.targetDate?new Date(p.targetDate).toLocaleDateString():"No target"}</span></span></Link>)}{!projects.length&&<Empty title="No upcoming project deadlines"/>}</div></Card>}
function PerformanceCard({data}:{data?:{delivery:{completionPercentage:number;onTimeCompletion:number};quality:{firstPassAcceptance:number};flow:{cycleTimeHours:number}}}){return <Card><CardHeader title="My performance" description="Only your role-permitted personal performance snapshot; detailed analytics live on Performance." action={<Link href="/product-management/performance" className="text-xs font-black text-blue-600">Open</Link>}/>{data?<div className="grid grid-cols-2 gap-3 p-5"><Mini label="Completion" value={`${data.delivery.completionPercentage}%`}/><Mini label="On time" value={`${data.delivery.onTimeCompletion}%`}/><Mini label="First pass" value={`${data.quality.firstPassAcceptance}%`}/><Mini label="Cycle time" value={`${data.flow.cycleTimeHours}h`}/></div>:<Empty title="No performance data yet"/>}</Card>}
function ReleaseCard({releases}:{releases:Array<{_id:string;projectId:string;name:string;status:string;targetDate?:string}>}){return <Card><CardHeader title="Delivery & releases" description="Upcoming release and client-delivery signals."/><div className="divide-y divide-slate-100">{releases.length?releases.slice(0,8).map(r=><Link href={`/product-management/projects/${r.projectId}/releases`} key={r._id} className="flex items-center gap-3 px-5 py-4 hover:bg-slate-50"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-700"><Sparkles className="h-4 w-4"/></span><span className="flex-1"><b className="block text-sm">{r.name}</b><span className="text-xs text-slate-400">{r.targetDate?new Date(r.targetDate).toLocaleDateString():"No target date"}</span></span><StatusBadge value={r.status}/></Link>):<Empty title="No upcoming releases"/>}</div></Card>}
function Signal({icon:Icon,title,value,tone}:{icon:typeof Target;title:string;value:number;tone:"rose"|"amber"|"blue"}){const c={rose:"bg-rose-50 text-rose-700",amber:"bg-amber-50 text-amber-700",blue:"bg-blue-50 text-blue-700"}[tone];return <div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className={`grid h-9 w-9 place-items-center rounded-lg ${c}`}><Icon className="h-4 w-4"/></span><span className="flex-1 text-sm font-bold text-slate-700">{title}</span><b className="text-lg text-slate-950">{value}</b></div>}
function SprintSummary({sprint}:{sprint:Record<string,unknown>}){const total=Number(sprint.totalPoints??0),done=Number(sprint.completedPoints??0),pct=total?Math.round(done/total*100):0;return <div><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-900">{String(sprint.name??"Active sprint")}</p><p className="mt-1 text-xs text-slate-400">{String(sprint.goal??"No sprint goal")}</p></div><StatusBadge value="active"/></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>{done} / {total} points</span><span>{pct}%</span></div><Progress value={pct}/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Mini label="Committed" value={Number(sprint.total??0)}/><Mini label="Done" value={Number(sprint.done??0)}/><Mini label="Remaining" value={Math.max(0,Number(sprint.total??0)-Number(sprint.done??0))}/></div></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><b className="block text-lg">{value}</b><span className="text-[10px] font-bold uppercase text-slate-400">{label}</span></div>}
function Loading(){return <div className="grid min-h-[50vh] place-items-center text-sm font-bold text-slate-400">Loading workspace overview…</div>}
