"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Archive, CalendarClock, FolderKanban, Plus, Search, ShieldAlert, Users } from "lucide-react";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useGetPMProjectsQuery } from "@/src/lib/features/product-management/product-management-api";
import { Card, Empty, PageHeader, Pagination, Progress, StatusBadge, inputClass, shortDate } from "./pm-ui";
export function PMProjectsPage(){
 const me=useGetMeQuery().data?.data,isClient=me?.role==='client-viewer',canCreate=me?.role==='super-admin'||(me?.permissions??[]).includes('product-management.projects.manage');
 const [query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[type,setType]=useState(''),[risk,setRisk]=useState('all'),[archived,setArchived]=useState(false),[page,setPage]=useState(1);
 useEffect(()=>{const id=setTimeout(()=>{setDebounced(query.trim());setPage(1)},250);return()=>clearTimeout(id)},[query]);
 const q=useGetPMProjectsQuery({query:debounced||undefined,type:type||undefined,risk:!isClient&&risk!=='all'?risk:undefined,archived:!isClient&&archived,page,limit:18});const rows=q.data?.data??[],pg=q.data?.pagination;
 return <><PageHeader title="Projects" description={isClient?'Projects explicitly shared with your client role.':'Server-filtered Product Management projects with health, delivery risk, sprint and release signals.'} actions={canCreate?<Link href="/product-management/projects/new" className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>Create project</Link>:undefined}/>
 <Card className="mb-5 p-4"><div className={`grid gap-3 ${isClient?'lg:grid-cols-[1fr_180px]':'lg:grid-cols-[1fr_180px_180px_auto]'}`}><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-9`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search key, project name or description"/></div><select className={inputClass} value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All project types</option><option value="scrum">Scrum</option><option value="kanban">Kanban</option><option value="general">General</option></select>{!isClient&&<><select className={inputClass} value={risk} onChange={e=>{setRisk(e.target.value);setPage(1)}}><option value="all">All health states</option><option value="at-risk">At risk</option><option value="healthy">Healthy</option></select><label className="flex h-11 cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setPage(1)}}/>Archived</label></>}</div></Card>
 {q.isLoading?<Card><div className="p-10 text-center text-sm font-bold text-slate-400">Loading projects…</div></Card>:rows.length?<><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{rows.map(p=><Link key={p._id} href={`/product-management/projects/${p._id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,.03)] transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-900/5"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-100 to-blue-100 text-xs font-black text-violet-700">{p.key.slice(0,2)}</span><div className="flex items-center gap-2">{p.archivedAt&&<Archive className="h-4 w-4 text-slate-400"/>}<StatusBadge value={p.projectType??'scrum'}/></div></div><h2 className="mt-4 text-lg font-black text-slate-950 group-hover:text-blue-700">{p.name}</h2><p className="mt-1 text-xs font-bold text-slate-400">{p.key} · {p.visibility??'team'}</p><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{p.description||'No project description yet.'}</p>{!isClient&&p.health&&<div className="mt-4 rounded-xl bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between text-[10px] font-black"><span className="text-slate-500">Delivery progress</span><span className={p.health.risk==='at-risk'?'text-rose-600':'text-emerald-600'}>{p.health.completion}% · {p.health.risk}</span></div><Progress value={p.health.completion}/><div className="mt-2 flex gap-3 text-[10px] text-slate-400"><span>{p.health.total} work</span><span>{p.health.blocked} blocked</span><span>{p.health.overdue} overdue</span></div></div>}<div className={`mt-4 grid gap-2 border-t border-slate-100 pt-4 text-xs text-slate-500 ${isClient?'grid-cols-2':'grid-cols-2'}`}>{!isClient&&<><span className="flex items-center gap-2"><Users className="h-3.5 w-3.5 text-teal-500"/>{p.members?.length??0} members</span><span className="flex items-center gap-2"><ShieldAlert className="h-3.5 w-3.5 text-rose-500"/>{p.activeSprint?.name??'No active sprint'}</span></>}<span className="flex items-center gap-2"><CalendarClock className="h-3.5 w-3.5 text-amber-500"/>{shortDate(p.targetDate)}</span><span>{p.openReleases??0} visible releases</span></div></Link>)}</div>{pg&&<Card className="mt-5"><Pagination page={pg.page} totalPages={pg.totalPages} onPage={setPage}/></Card>}</>:<Card><Empty title="No matching projects" description={isClient?'No projects are currently shared with this account.':'Create a project or adjust the server-side filters.'}/></Card>}</>
}
