"use client";

import Link from "next/link";
import { AlertTriangle, CalendarClock, CheckCircle2, CircleDot, Gauge, ListTodo, Milestone, Plus, Rocket, Users } from "lucide-react";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useGetPMProjectQuery } from "@/src/lib/features/product-management/product-management-api";
import { Card, CardHeader, Empty, Loading, PageHeader, Progress, Stat, StatusBadge, shortDate, userLabel } from "./pm-ui";

export function PMProjectOverviewPage({ projectId }: { projectId: string }) {
  const meQ = useGetMeQuery();
  const q = useGetPMProjectQuery(projectId);
  const p = q.data?.data;
  const me = meQ.data?.data;
  const isClient = me?.role === "client-viewer";
  const canManageWork = me?.role === "super-admin" || me?.role === "product-admin" || me?.permissions?.includes("product-management.work.manage");

  if (q.isLoading) return <Loading label="Loading project…" />;
  if (!p) return <Card><Empty title="Project unavailable" description="You may not have permission to access this project." /></Card>;

  if (isClient) {
    return <>
      <PageHeader eyebrow={`${p.key} / Client workspace`} title={p.name} description={p.description || "Approved roadmap, release and client-delivery information for this project."} actions={<Link href={`/product-management/projects/${projectId}/releases`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Rocket className="h-4 w-4"/>Delivery</Link>} />
      <div className="grid gap-4 md:grid-cols-3">
        <Stat label="Published milestones" value={p.milestones.length} detail="Client-visible roadmap" tone="violet" icon={Milestone}/>
        <Stat label="Visible releases" value={p.releases.length} detail="Approved delivery pipeline" tone="amber" icon={Rocket}/>
        <Stat label="Target date" value={shortDate(p.targetDate)} detail={p.clientName || "Client project"} tone="blue" icon={CalendarClock}/>
      </div>
      <div className="mt-6 grid gap-6 xl:grid-cols-2">
        <Card><CardHeader title="Published roadmap" description="Milestones explicitly shared with client stakeholders."/><div className="divide-y divide-slate-100">{p.milestones.map(m=><div key={m._id} className="flex items-center gap-3 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-700"><Milestone className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{m.name}</b><span className="text-[10px] text-slate-400">{shortDate(m.startDate)} → {shortDate(m.dueDate)}</span></span><StatusBadge value={m.status}/></div>)}{!p.milestones.length&&<Empty title="No published milestones" description="Nothing has been published to the client roadmap yet."/>}</div><Link href={`/product-management/projects/${projectId}/timeline`} className="m-4 inline-flex text-xs font-black text-violet-600">Open roadmap →</Link></Card>
        <Card><CardHeader title="Release & delivery pipeline" description="Only client-visible release stages are shown."/><div className="divide-y divide-slate-100">{p.releases.map(r=><div key={r._id} className="flex items-center gap-3 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-700"><Rocket className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{r.name}</b><span className="text-[10px] text-slate-400">Target {shortDate(r.targetDate)}</span></span><StatusBadge value={r.status}/></div>)}{!p.releases.length&&<Empty title="No client-visible releases"/>}</div><Link href={`/product-management/projects/${projectId}/releases`} className="m-4 inline-flex text-xs font-black text-amber-600">Review delivery →</Link></Card>
      </div>
      <Card className="mt-6"><CardHeader title="Project information"/><div className="grid gap-3 p-5 sm:grid-cols-3"><Info label="Project type" value={p.projectType ?? "General"}/><Info label="Start" value={shortDate(p.startDate)}/><Info label="Target" value={shortDate(p.targetDate)}/></div></Card>
    </>;
  }

  const pct = p.stats.total ? Math.round(p.stats.done / p.stats.total * 100) : 0;
  return <>
    <PageHeader eyebrow={`${p.key} / Project`} title={p.name} description={p.description || "Project overview, health, ownership, timeline and delivery readiness."} actions={<>{canManageWork&&<Link href={`/product-management/projects/${projectId}/tasks?new=1`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>Work item</Link>}<Link href={`/product-management/projects/${projectId}/board`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700">Open board</Link></>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Work items" value={p.stats.total} detail={`${p.stats.done} completed`} icon={ListTodo}/><Stat label="Completion" value={`${pct}%`} detail={`${p.stats.donePoints}/${p.stats.points} points`} tone="emerald" icon={CheckCircle2}/><Stat label="Blocked" value={p.stats.blocked} detail="Delivery blockers" tone="rose" icon={AlertTriangle}/><Stat label="Overdue" value={p.stats.overdue} detail="Past due date" tone="amber" icon={CalendarClock}/><Stat label="Open releases" value={p.releases.filter(r=>!["Released","Delivered"].includes(r.status)).length} detail="Release pipeline" tone="violet" icon={Rocket}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Project health" description="Work progress and delivery signals."/><div className="p-5"><div className="mb-2 flex justify-between text-sm font-bold"><span className="text-slate-600">Delivery completion</span><span>{pct}%</span></div><Progress value={pct}/><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Method" value={p.projectType??"scrum"}/><Info label="Visibility" value={p.visibility??"team"}/><Info label="Client" value={p.clientName||"Internal"}/><Info label="Start" value={shortDate(p.startDate)}/><Info label="Target" value={shortDate(p.targetDate)}/><Info label="Updated" value={shortDate(p.updatedAt)}/></div></div></Card><Card><CardHeader title="Ownership" description="Project leadership and team."/><div className="space-y-3 p-5"><Person label="Product owner" value={userLabel(p.productOwner)}/><Person label="Project manager" value={userLabel(p.projectManager||p.lead)}/><Person label="Team lead" value={userLabel(p.teamLead)}/><Link href={`/product-management/projects/${projectId}/team`} className="flex items-center justify-between rounded-xl bg-teal-50 p-3 text-xs font-black text-teal-700"><span className="flex items-center gap-2"><Users className="h-4 w-4"/>{p.members.length} project members</span><span>Manage →</span></Link></div></Card></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><Card><CardHeader title="Active sprint"/><div className="p-5">{p.activeSprint?<><div className="flex items-center justify-between"><b>{p.activeSprint.name}</b><StatusBadge value={p.activeSprint.status}/></div><p className="mt-2 text-xs leading-5 text-slate-500">{p.activeSprint.goal||"No sprint goal set."}</p><div className="mt-4 text-xs text-slate-500">{shortDate(p.activeSprint.startDate)} → {shortDate(p.activeSprint.endDate)}</div><Link href={`/product-management/projects/${projectId}/sprints`} className="mt-4 inline-flex text-xs font-black text-blue-600">Manage sprint →</Link></>:<Empty title="No active sprint" description="Create or start a sprint from Sprint Management."/>}</div></Card><Card><CardHeader title="Milestones"/><div className="divide-y divide-slate-100">{p.milestones.slice(0,4).map(m=><div key={m._id} className="flex items-center gap-3 px-5 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-50 text-violet-700"><Milestone className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{m.name}</b><span className="text-[10px] text-slate-400">{shortDate(m.dueDate)}</span></span><StatusBadge value={m.status}/></div>)}{!p.milestones.length&&<Empty title="No milestones"/>}</div><Link href={`/product-management/projects/${projectId}/timeline`} className="m-4 inline-flex text-xs font-black text-violet-600">Open roadmap →</Link></Card><Card><CardHeader title="Release pipeline"/><div className="divide-y divide-slate-100">{p.releases.slice(0,4).map(r=><div key={r._id} className="flex items-center gap-3 px-5 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-amber-50 text-amber-700"><Rocket className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{r.name}</b><span className="text-[10px] text-slate-400">{shortDate(r.targetDate)}</span></span><StatusBadge value={r.status}/></div>)}{!p.releases.length&&<Empty title="No releases"/>}</div><Link href={`/product-management/projects/${projectId}/releases`} className="m-4 inline-flex text-xs font-black text-amber-600">Manage delivery →</Link></Card></div>
    <Card className="mt-6"><CardHeader title="Workflow" description="Current project-specific lifecycle."/><div className="flex flex-wrap items-center gap-2 p-5">{(p.workflow?.statuses??[]).map((s,i)=><span key={s} className="flex items-center gap-2"><span className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-black text-slate-700">{s}</span>{i<(p.workflow?.statuses.length??0)-1&&<CircleDot className="h-3 w-3 text-slate-300"/>}</span>)}</div></Card>
  </>;
}

function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><span className="block text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</span><b className="mt-1 block truncate text-xs text-slate-700">{value}</b></div>}
function Person({label,value}:{label:string;value:string}){return <div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-blue-700"><Gauge className="h-4 w-4"/></span><span><span className="block text-[10px] font-bold uppercase text-slate-400">{label}</span><b className="text-xs text-slate-800">{value}</b></span></div>}
