"use client";

import { useState } from "react";
import { CheckCircle2, Circle, PackageCheck, Plus, Rocket, ShieldCheck, XCircle } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useCreatePMDeliveryMutation, useCreatePMReleaseMutation, useDecidePMDeliveryMutation, useDecidePMReleaseMutation, useGetPMDeliveriesQuery, useGetPMReleaseReadinessQuery, useGetPMReleasesQuery, useTransitionPMReleaseMutation, useUpdatePMDeliveryMutation, useUpdatePMReleaseMutation } from "@/src/lib/features/product-management/product-management-api";
import type { PMDelivery, PMRelease, PMTask, PMUser } from "@/src/lib/features/product-management/product-management-types";
import { AsyncUserPicker, AsyncWorkItemPicker, Card, CardHeader, Empty, Field, MultiValueInput, PageHeader, Progress, StatusBadge, inputClass, primaryButton, secondaryButton, shortDate, textareaClass, userLabel } from "./pm-ui";

const releaseStatuses=["Draft","Planning","Development","QA","Internal Approval","Ready for Client","Client Review","Approved","Released","Delivered"];
const deliveryStatuses=["Development Complete","Internal QA","Internal Approval","Client Review","Change Requested","Approved","Delivered","Closed"];

export function PMReleasesPage({projectId}:{projectId:string}){
  const meQ=useGetMeQuery();
  const me=meQ.data?.data;
  const isClient=me?.role==="client-viewer";
  const fullAdmin=me?.role==="super-admin"||me?.role==="product-admin";
  const canRelease=Boolean(fullAdmin||me?.permissions?.includes("product-management.releases.manage"));
  const canDelivery=Boolean(fullAdmin||me?.permissions?.includes("product-management.client-delivery.manage"));
  const releasesQ=useGetPMReleasesQuery(projectId);
  const deliveriesQ=useGetPMDeliveriesQuery(projectId);
  const [showRelease,setShowRelease]=useState(false),[showDelivery,setShowDelivery]=useState(false),[createRelease]=useCreatePMReleaseMutation(),[createDelivery]=useCreatePMDeliveryMutation();
  const [r,setR]=useState({name:"",description:"",targetDate:"",owner:"",environment:"",client:"",releaseNotes:"",clientDeliverablesPrepared:false,workItems:[] as PMTask[],approvers:[] as PMUser[]});
  const [d,setD]=useState({title:"",client:"",releaseId:"",deliveryDate:"",deliverables:[] as string[],notes:"",internalApprover:"",clientApprover:""});
  async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();toast.success(msg)}catch(e){toast.error(getApiErrorMessage(e))}}

  return <>
    <PageHeader eyebrow="Project / Delivery" title="Releases & Client Delivery" description={isClient?"Review approved release information, client deliverables and decisions assigned to you.":"Manage the full journey from development through QA, internal approval, client review, release, final delivery and closure."} actions={<>{canRelease&&<button className={primaryButton} onClick={()=>setShowRelease(v=>!v)}><Plus className="h-4 w-4"/>Release</button>}{canDelivery&&<button className={secondaryButton} onClick={()=>setShowDelivery(v=>!v)}><PackageCheck className="h-4 w-4"/>Client delivery</button>}</>}/>
    {showRelease&&canRelease&&<Card className="mb-5"><CardHeader title="Create release" description="Define scope, owner, approvers, environment and release notes."/><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Release / version" required><input className={inputClass} value={r.name} onChange={e=>setR(v=>({...v,name:e.target.value}))}/></Field><Field label="Target date"><input type="date" className={inputClass} value={r.targetDate} onChange={e=>setR(v=>({...v,targetDate:e.target.value}))}/></Field><Field label="Environment"><input className={inputClass} value={r.environment} onChange={e=>setR(v=>({...v,environment:e.target.value}))} placeholder="Production / Staging"/></Field><Field label="Release owner"><AsyncUserPicker projectId={projectId} value={r.owner} onChange={id=>setR(v=>({...v,owner:id}))}/></Field><Field label="Approvers"><AsyncUserPicker projectId={projectId} multiple values={r.approvers} onValuesChange={approvers=>setR(v=>({...v,approvers}))}/></Field><Field label="Client"><input className={inputClass} value={r.client} onChange={e=>setR(v=>({...v,client:e.target.value}))}/></Field><div className="md:col-span-2 xl:col-span-3"><Field label="Description"><textarea className={textareaClass} value={r.description} onChange={e=>setR(v=>({...v,description:e.target.value}))}/></Field></div><div className="md:col-span-2 xl:col-span-3"><Field label="Included work items" hint="Search is server-side and paged; select visible results or keep searching without preloading the project."><AsyncWorkItemPicker projectId={projectId} multiple values={r.workItems} onValuesChange={workItems=>setR(v=>({...v,workItems}))} label="Search release scope by key or title"/></Field></div><div className="md:col-span-2 xl:col-span-3"><Field label="Release notes"><textarea className={textareaClass} value={r.releaseNotes} onChange={e=>setR(v=>({...v,releaseNotes:e.target.value}))}/></Field></div>{r.client&&<label className="md:col-span-2 xl:col-span-3 flex items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 p-3 text-xs font-black text-blue-800"><input type="checkbox" checked={r.clientDeliverablesPrepared} onChange={e=>setR(v=>({...v,clientDeliverablesPrepared:e.target.checked}))}/>Client deliverables are prepared and verified</label>}</div><div className="flex justify-end border-t border-slate-100 p-5"><button disabled={!r.name||!r.owner} className={primaryButton} onClick={()=>void run(async()=>{await createRelease({projectId,name:r.name,description:r.description||undefined,targetDate:r.targetDate||undefined,owner:r.owner,environment:r.environment||undefined,client:r.client||undefined,releaseNotes:r.releaseNotes||undefined,clientDeliverablesPrepared:r.clientDeliverablesPrepared,workItems:r.workItems.map(x=>x._id),approvers:r.approvers.map(x=>x._id)}).unwrap();setShowRelease(false)},"Release created")}>Create release</button></div></Card>}
    {showDelivery&&canDelivery&&<Card className="mb-5"><CardHeader title="Create client delivery" description="Delivery is an explicit stage after development; it does not stop at Done."/><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Delivery title" required><input className={inputClass} value={d.title} onChange={e=>setD(v=>({...v,title:e.target.value}))}/></Field><Field label="Client" required><input className={inputClass} value={d.client} onChange={e=>setD(v=>({...v,client:e.target.value}))}/></Field><Field label="Release"><select className={inputClass} value={d.releaseId} onChange={e=>setD(v=>({...v,releaseId:e.target.value}))}><option value="">No linked release</option>{(releasesQ.data?.data??[]).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></Field><Field label="Delivery date"><input type="date" className={inputClass} value={d.deliveryDate} onChange={e=>setD(v=>({...v,deliveryDate:e.target.value}))}/></Field><Field label="Internal approver"><AsyncUserPicker projectId={projectId} value={d.internalApprover} onChange={id=>setD(v=>({...v,internalApprover:id}))}/></Field><Field label="Client approver"><AsyncUserPicker projectId={projectId} includeClients value={d.clientApprover} onChange={id=>setD(v=>({...v,clientApprover:id}))}/></Field><div className="md:col-span-2 xl:col-span-3"><Field label="Deliverables"><MultiValueInput values={d.deliverables} onChange={deliverables=>setD(v=>({...v,deliverables}))} placeholder="Add deliverable and press Enter"/></Field></div><div className="md:col-span-2 xl:col-span-3"><Field label="Delivery notes"><textarea className={textareaClass} value={d.notes} onChange={e=>setD(v=>({...v,notes:e.target.value}))}/></Field></div></div><div className="flex justify-end border-t border-slate-100 p-5"><button disabled={!d.title||!d.client} className={primaryButton} onClick={()=>void run(async()=>{await createDelivery({projectId,...d,releaseId:d.releaseId||undefined,deliveryDate:d.deliveryDate||undefined,internalApprover:d.internalApprover||undefined,clientApprover:d.clientApprover||undefined}).unwrap();setShowDelivery(false)},"Delivery created")}>Create delivery</button></div></Card>}
    <div className="grid gap-6 2xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader title="Release pipeline" description={isClient?"Client-visible release stages and notes.":"Readiness gates prevent unsafe transitions to client/released states."}/><div className="space-y-4 p-4">{(releasesQ.data?.data??[]).map(rel=><ReleaseCard key={rel._id} release={rel} currentUserId={me?.userId} canManage={canRelease} isClient={isClient}/>)}{!(releasesQ.data?.data??[]).length&&<Empty title="No releases"/>}</div></Card><Card><CardHeader title="Client delivery" description={isClient?"Review deliverables and record approval or requested changes when assigned.":"Internal QA → approval → client review → change requested/approved → delivered → closed."}/><div className="space-y-3 p-4">{(deliveriesQ.data?.data??[]).map(del=><DeliveryCard key={del._id} delivery={del} currentUserId={me?.userId} canManage={canDelivery} fullAdmin={fullAdmin}/>)}{!(deliveriesQ.data?.data??[]).length&&<Empty title="No delivery records"/>}</div></Card></div>
  </>;
}

function ReleaseCard({release,currentUserId,canManage,isClient}:{release:PMRelease;currentUserId?:string;canManage:boolean;isClient:boolean}){
  const readyQ=useGetPMReleaseReadinessQuery(release._id,{skip:isClient});
  const [transition]=useTransitionPMReleaseMutation(),[decision]=useDecidePMReleaseMutation(),[update]=useUpdatePMReleaseMutation();
  const readiness=release.readiness??readyQ.data?.data,idx=releaseStatuses.indexOf(release.status),next=releaseStatuses[idx+1];
  const ownApproval=release.approvals?.find(a=>entityId(a.userId)===currentUserId);
  const canDecide=Boolean((ownApproval&&ownApproval.status==="pending")||(canManage&&release.status==="Internal Approval"));
  async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();toast.success(msg)}catch(e){toast.error(getApiErrorMessage(e))}}
  const checks=readiness?.checks??{};
  return <article className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-700"><Rocket className="h-4 w-4"/></span><div><b className="block text-sm">{release.name}</b><span className="text-[10px] text-slate-400">{release.environment||"Environment not set"} · target {shortDate(release.targetDate)}</span></div></div></div><StatusBadge value={release.status}/></div>
    {!isClient&&<><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(checks).map(([key,ok])=><div key={key} className={`flex items-center gap-2 rounded-lg px-2 py-2 text-[10px] font-bold ${ok?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{ok?<CheckCircle2 className="h-3.5 w-3.5"/>:<Circle className="h-3.5 w-3.5"/>}{key.replaceAll(/([A-Z])/g," $1")}</div>)}</div><div className="mt-3"><div className="mb-1 flex justify-between text-[10px] font-bold text-slate-400"><span>Readiness</span><span>{readiness?.ready?"Ready":"Not ready"}</span></div><Progress value={Object.keys(checks).length?Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100:0}/></div></>}
    {release.releaseNotes&&<p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-slate-500">{release.releaseNotes}</p>}
    <div className="mt-4 flex flex-wrap gap-2">{canManage&&next&&<button className={primaryButton} disabled={["Ready for Client","Client Review","Approved","Released","Delivered"].includes(next)&&!readiness?.ready} onClick={()=>void run(()=>transition({id:release._id,status:next}).unwrap(),`Release moved to ${next}`)}>Advance → {next}</button>}{canDecide&&release.status==="Internal Approval"&&<><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-600 px-3 text-xs font-black text-white" onClick={()=>void run(()=>decision({id:release._id,decision:"approved"}).unwrap(),"Release approved")}><ShieldCheck className="h-4 w-4"/>Approve</button><button className="inline-flex h-10 items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-3 text-xs font-black text-rose-700" onClick={()=>void run(()=>decision({id:release._id,decision:"rejected",note:prompt("Rejection note")||undefined}).unwrap(),"Release rejected")}><XCircle className="h-4 w-4"/>Reject</button></>}{canManage&&<button className={secondaryButton} onClick={()=>void run(()=>update({id:release._id,body:{releaseNotes:prompt("Release notes",release.releaseNotes??"")??release.releaseNotes}}).unwrap(),"Release notes updated")}>Edit notes</button>}{canManage&&release.client&&<button className={secondaryButton} onClick={()=>void run(()=>update({id:release._id,body:{clientDeliverablesPrepared:!release.clientDeliverablesPrepared}}).unwrap(),release.clientDeliverablesPrepared?"Client deliverables marked not ready":"Client deliverables marked prepared")}>{release.clientDeliverablesPrepared?"Mark deliverables not ready":"Mark client deliverables prepared"}</button>}</div>
    {!isClient&&release.approvals?.length?<div className="mt-3 flex flex-wrap gap-2">{release.approvals.map((a,i)=><span key={i} className="rounded-full bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-500">{userLabel(a.userId)} · {a.status}</span>)}</div>:null}
  </article>;
}

function DeliveryCard({delivery,currentUserId,canManage,fullAdmin}:{delivery:PMDelivery;currentUserId?:string;canManage:boolean;fullAdmin:boolean}){
  const [update]=useUpdatePMDeliveryMutation(),[decision]=useDecidePMDeliveryMutation();
  const idx=deliveryStatuses.indexOf(delivery.status),next=deliveryStatuses[idx+1];
  const isAssignedClient=Boolean(currentUserId&&entityId(delivery.clientApprover)===currentUserId);
  const canClientDecide=(fullAdmin||isAssignedClient)&&["Client Review","Change Requested"].includes(delivery.status);
  async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();toast.success(msg)}catch(e){toast.error(getApiErrorMessage(e))}}
  return <article className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">{delivery.title}</b><p className="mt-1 text-[10px] text-slate-400">{delivery.client} · {shortDate(delivery.deliveryDate)}</p></div><StatusBadge value={delivery.status}/></div><div className="mt-3 flex flex-wrap gap-1">{delivery.deliverables.map(v=><span key={v} className="rounded-lg bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{v}</span>)}</div>{delivery.notes&&<p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-slate-500">{delivery.notes}</p>}{delivery.rejectionReason&&<p className="mt-3 rounded-lg bg-rose-50 p-2 text-[10px] text-rose-700">{delivery.rejectionReason}</p>}<div className="mt-3 flex flex-wrap gap-2">{canManage&&next&&<button className={secondaryButton} onClick={()=>void run(()=>update({id:delivery._id,body:{status:next}}).unwrap(),`Delivery moved to ${next}`)}>Advance → {next}</button>}{canClientDecide&&<><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-600 px-3 text-xs font-black text-white" onClick={()=>void run(()=>decision({id:delivery._id,decision:"approved"}).unwrap(),"Client delivery approved")}><CheckCircle2 className="h-4 w-4"/>Approve</button><button className="inline-flex h-10 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 text-xs font-black text-amber-700" onClick={()=>void run(()=>decision({id:delivery._id,decision:"changes-requested",reason:prompt("Requested changes")||undefined}).unwrap(),"Changes requested")}>Request changes</button><button className="inline-flex h-10 items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-3 text-xs font-black text-rose-700" onClick={()=>void run(()=>decision({id:delivery._id,decision:"rejected",reason:prompt("Rejection reason")||undefined}).unwrap(),"Delivery rejected")}>Reject</button></>}</div></article>;
}

function entityId(value:unknown){if(!value)return "";if(typeof value==="string")return value;if(typeof value==="object"&&"_id" in value)return String((value as {_id:unknown})._id);return String(value)}
