"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Clock3, Flame, Gauge, Layers3, Rocket, Target, TrendingUp, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useGetPMPerformanceQuery, useGetPMProjectsQuery, useGetPMReportQuery } from "@/src/lib/features/product-management/product-management-api";
import type { PMReport, PMUser } from "@/src/lib/features/product-management/product-management-types";
import { AsyncUserPicker, Card, CardHeader, Empty, PageHeader, Progress, Stat, StatusBadge, inputClass } from "./pm-ui";
const reportOptions=[
  ['health','Project Health',Gauge],['sprint-burndown','Sprint Burndown',Flame],['sprint-burnup','Sprint Burnup',TrendingUp],['velocity','Velocity',BarChart3],
  ['cumulative-flow','Cumulative Flow',Activity],['cycle-time','Cycle Time',Clock3],['lead-time','Lead Time',Clock3],['created','Work Created vs Completed',TrendingUp],
  ['workload-assignee','Workload by Assignee',Users],['workload-team','Workload by Team',Users],['overdue','Overdue Work',Clock3],['priority-distribution','Priority Distribution',BarChart3],['status-distribution','Status Distribution',BarChart3],
  ['epics','Epic Progress',Layers3],['release-progress','Release Progress',Rocket],['release-burndown','Release Burndown',Flame],['team-performance','Team Performance',Users],['individual-performance','Individual Performance',Target],['delivery','Delivery Performance',Target],
] as const;
type ReportId=typeof reportOptions[number][0];
export function PMReportsPage({projectId}:{projectId?:string}){const projectsQ=useGetPMProjectsQuery({limit:100}),[selected,setSelected]=useState(projectId??''),[report,setReport]=useState<ReportId>('health');useEffect(()=>{if(projectId)setSelected(projectId)},[projectId]);const q=useGetPMReportQuery(selected,{skip:!selected}),d=q.data?.data;return <><PageHeader title={projectId?'Project Reports':'Reports'} description="Role-scoped delivery analytics with dedicated report modes for sprint, flow, workload, overdue work, distributions, epics, releases, health and client delivery."/><Card className="mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(260px,420px)_1fr]"><select disabled={!!projectId} className={inputClass} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a permitted project</option>{(projectsQ.data?.data??[]).map(p=><option key={p._id} value={p._id}>{p.key} · {p.name}</option>)}</select><div className="flex flex-wrap gap-2">{reportOptions.map(([id,label,Icon])=><button key={id} onClick={()=>setReport(id)} className={`inline-flex h-10 items-center gap-2 rounded-xl px-3 text-[10px] font-black ${report===id?'bg-slate-900 text-white':'border border-slate-200 bg-white text-slate-600'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div></Card>{!selected?<Card><Empty title="Select a project" description="Reports never expose projects outside your permitted scope."/></Card>:!d?<Card><Empty title={q.isLoading?'Loading report…':'No report data'}/></Card>:<><div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Work items" value={d.summary.total} detail={`${d.summary.done} completed`} icon={Target}/><Stat label="Completion" value={`${d.summary.completionRate}%`} detail={`${d.summary.donePoints}/${d.summary.points} points`} tone="emerald"/><Stat label="Overdue" value={d.summary.overdue} detail="Open past due" tone="rose"/><Stat label="Blocked" value={d.summary.blocked} detail="Needs intervention" tone="amber"/><Stat label="Health" value={d.summary.health} detail="Current project signal" tone="violet"/></div><ReportBody id={report} data={d} projectId={selected}/></>}</>}
function ReportBody({id,data:d,projectId}:{id:ReportId;data:PMReport;projectId:string}){
 if(id==='health')return <Card><CardHeader title="Project Health" description="Completion, blocked work and delivery risk."/><div className="p-5"><div className="mb-2 flex justify-between text-xs font-bold"><span>Completion</span><span>{d.summary.completionRate}%</span></div><Progress value={d.summary.completionRate}/><div className="mt-5 grid grid-cols-3 gap-3 text-center"><Mini label="Open" value={d.summary.total-d.summary.done}/><Mini label="Overdue" value={d.summary.overdue}/><Mini label="Blocked" value={d.summary.blocked}/></div></div></Card>;
 if(id==='overdue')return <Card><CardHeader title="Overdue Work" description="Open work items whose due dates have passed."/><div className="divide-y divide-slate-100">{d.overdue.map(t=><div key={t._id} className="flex items-center justify-between gap-2 p-4"><span className="min-w-0"><b className="block truncate text-xs">{t.key} · {t.title}</b><span className="text-[10px] text-slate-400">{t.priority} · {t.type}</span></span><StatusBadge value={t.status}/></div>)}{!d.overdue.length&&<Empty title="No overdue work"/>}</div></Card>;
 if(id==='sprint-burndown')return <ChartCard title="Sprint Burndown" description="Remaining points versus the ideal line."><LineChart data={d.burndown}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="remaining" stroke="#ef4444" strokeWidth={2}/><Line type="monotone" dataKey="ideal" stroke="#94a3b8" strokeDasharray="5 5"/></LineChart></ChartCard>;
 if(id==='sprint-burnup')return <ChartCard title="Sprint Burnup" description="Completed points against committed scope."><LineChart data={d.burnup}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="completed" stroke="#10b981" strokeWidth={2}/><Line type="monotone" dataKey="scope" stroke="#6366f1" strokeWidth={2}/></LineChart></ChartCard>;
 if(id==='velocity')return <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><ChartCard title="Velocity" description="Delivered points by completed sprint."><BarChart data={d.velocity}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="sprint"/><YAxis/><Tooltip/><Bar dataKey="points" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ChartCard><Card><CardHeader title="Sprint History" description="Commitment, delivery and carry-over."/><div className="divide-y divide-slate-100">{d.sprints.map((s,i)=><div key={i} className="grid grid-cols-4 gap-2 p-3 text-center text-xs"><span className="col-span-4 text-left font-black">{String(s.name??`Sprint ${i+1}`)}</span><Mini label="Committed" value={Number(s.committedPoints??0)}/><Mini label="Delivered" value={Number(s.deliveredPoints??0)}/><Mini label="Carryover" value={Number(s.carryoverPoints??0)}/><Mini label="Ratio" value={`${Number(s.completionRatio??0)}%`}/></div>)}</div></Card></div>;
 if(id==='cumulative-flow'){const flow=normalizeFlow(d.cumulativeFlow);return <ChartCard title="Cumulative Flow" description="Work in each status by day."><AreaChart data={flow}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Legend/>{flowKeys(flow).map((k,i)=><Area key={k} type="monotone" dataKey={k} stackId="1" fill={['#3b82f6','#8b5cf6','#14b8a6','#f59e0b','#ef4444','#10b981'][i%6]} stroke="transparent"/>)}</AreaChart></ChartCard>}
 if(id==='cycle-time')return <Card><CardHeader title="Cycle Time" description="Average elapsed execution time from active work to completion."/><div className="grid gap-4 p-5 sm:grid-cols-3"><Metric label="Cycle time" value={`${d.flowDurations.cycleTimeHours}h`} icon={Activity}/><Metric label="Review time" value={`${d.flowDurations.reviewTimeHours}h`} icon={Target}/><Metric label="Blocked work" value={d.summary.blocked} icon={Clock3}/></div></Card>;
 if(id==='lead-time')return <Card><CardHeader title="Lead Time" description="Average elapsed time from work creation to completion."/><div className="grid gap-4 p-5 sm:grid-cols-3"><Metric label="Lead time" value={`${d.flowDurations.leadTimeHours}h`} icon={Clock3}/><Metric label="Cycle time" value={`${d.flowDurations.cycleTimeHours}h`} icon={Activity}/><Metric label="Completion" value={`${d.summary.completionRate}%`} icon={Gauge}/></div></Card>;
 if(id==='created')return <ChartCard title="Work Created vs Completed" description="30-day demand versus throughput trend."><BarChart data={d.workCreatedVsCompleted}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Legend/><Bar dataKey="created" fill="#3b82f6" radius={[5,5,0,0]}/><Bar dataKey="completed" fill="#10b981" radius={[5,5,0,0]}/></BarChart></ChartCard>;
 if(id==='workload-assignee')return <Card><CardHeader title="Workload by Assignee" description="Assigned items, delivered points and overdue load."/><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-3">Person</th><th className="p-3">Assigned</th><th className="p-3">Done</th><th className="p-3">Points</th><th className="p-3">Delivered</th><th className="p-3">Overdue</th></tr></thead><tbody className="divide-y divide-slate-100">{d.byAssignee.map(a=><tr key={a.userId}><td className="p-3"><b>{a.email??a.userId}</b><span className="ml-2 text-[10px] text-slate-400">{a.role}</span></td><td className="p-3">{a.assigned}</td><td className="p-3">{a.done}</td><td className="p-3">{a.points}</td><td className="p-3">{a.deliveredPoints}</td><td className="p-3 font-black text-rose-600">{a.overdue}</td></tr>)}</tbody></table></div></Card>;
 if(id==='workload-team')return <Card><CardHeader title="Workload by Team" description="Capacity, allocation and delivery load grouped by project role."/><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-3">Team segment</th><th className="p-3">Members</th><th className="p-3">Capacity</th><th className="p-3">Assigned</th><th className="p-3">Done</th><th className="p-3">Overdue</th></tr></thead><tbody className="divide-y divide-slate-100">{d.workloadByTeam.map(t=><tr key={t.team}><td className="p-3 font-black">{t.team.replaceAll('-', ' ')}</td><td className="p-3">{t.members}</td><td className="p-3">{t.capacity}h · {t.allocationPct}% alloc.</td><td className="p-3">{t.assigned}</td><td className="p-3">{t.done}</td><td className="p-3 font-black text-rose-600">{t.overdue}</td></tr>)}</tbody></table></div></Card>;
 if(id==='status-distribution')return <ChartCard title="Status Distribution"><BarChart data={d.byStatus}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="_id"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#3b82f6" radius={[6,6,0,0]}/></BarChart></ChartCard>;
 if(id==='priority-distribution')return <ChartCard title="Priority Distribution"><BarChart data={d.byPriority}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="_id"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#f59e0b" radius={[6,6,0,0]}/></BarChart></ChartCard>;
 if(id==='epics')return <Card><CardHeader title="Epic Progress"/><div className="space-y-3 p-5">{d.epicProgress.map((e,i)=>{const total=Number(e.total??0),done=Number(e.done??0),pct=total?done/total*100:0;return <div key={String(e._id??i)} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-2"><b className="text-sm">{String(e.key??'EPIC')} · {String(e.title??'Epic')}</b><span className="text-xs font-black">{Math.round(pct)}%</span></div><div className="mt-3"><Progress value={pct}/></div><p className="mt-2 text-[10px] text-slate-400">{done}/{total} items · {Number(e.donePoints??0)}/{Number(e.points??0)} points</p></div>})}{!d.epicProgress.length&&<Empty title="No epics"/>}</div></Card>;
 if(id==='release-progress')return <Card><CardHeader title="Release Progress" description="Scope completion and readiness status for each release."/><div className="grid gap-3 p-5">{d.releaseProgress.map((r,i)=><div key={String(r._id??i)} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><b className="text-sm">{String(r.name??'Release')}</b><StatusBadge value={String(r.status??'Draft')}/></div><div className="mt-3"><Progress value={Number(r.progress??r.completion??0)}/></div><p className="mt-2 text-[10px] text-slate-400">{Number(r.done??0)}/{Number(r.total??0)} items · {Boolean(r.ready)?'ready':'not ready'}</p></div>)}</div></Card>;
 if(id==='release-burndown')return <ChartCard title={`Release Burndown${d.releaseBurndown.releaseName?` · ${d.releaseBurndown.releaseName}`:''}`} description="Remaining release scope against the target-date ideal line."><LineChart data={d.releaseBurndown.series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="remaining" stroke="#f97316" strokeWidth={2}/><Line type="monotone" dataKey="ideal" stroke="#94a3b8" strokeDasharray="5 5"/></LineChart></ChartCard>;
 if(id==='team-performance')return <Card><CardHeader title="Team Performance" description="Balanced delivery view by assignee. This uses delivery and overdue signals, not message volume or raw activity counts."/><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-3">Person</th><th className="p-3">Assigned</th><th className="p-3">Completed</th><th className="p-3">Completion</th><th className="p-3">Delivered points</th><th className="p-3">Overdue</th></tr></thead><tbody className="divide-y divide-slate-100">{d.byAssignee.map(a=><tr key={a.userId}><td className="p-3 font-black">{a.email??a.userId}</td><td className="p-3">{a.assigned}</td><td className="p-3">{a.done}</td><td className="p-3">{a.assigned?Math.round(a.done/a.assigned*100):0}%</td><td className="p-3 font-black text-emerald-700">{a.deliveredPoints}</td><td className="p-3 font-black text-rose-600">{a.overdue}</td></tr>)}</tbody></table></div></Card>;
 if(id==='individual-performance')return <IndividualPerformanceReport projectId={projectId}/>;
 return <Card><CardHeader title="Delivery Performance" description="Client approval and final delivery outcomes."/><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Deliveries" value={d.deliveryPerformance.total} icon={Target}/><Metric label="Approved" value={d.deliveryPerformance.approved} icon={Gauge}/><Metric label="Changes" value={d.deliveryPerformance.changesRequested} icon={Activity}/><Metric label="Rejected" value={d.deliveryPerformance.rejected} icon={BarChart3}/><Metric label="Delivered" value={d.deliveryPerformance.delivered} icon={Rocket}/></div></Card>
}
function IndividualPerformanceReport({projectId}:{projectId:string}){const [person,setPerson]=useState<PMUser|undefined>();const q=useGetPMPerformanceQuery({projectId,userId:person?._id},{skip:!person});const d=q.data?.data;return <div className="grid gap-5"><Card className="p-4"><div className="max-w-xl"><AsyncUserPicker projectId={projectId} value={person?._id} onChange={(_,u)=>setPerson(u)} label="Select project member"/></div></Card>{!person?<Card><Empty title="Select a person" description="Choose an eligible project member to inspect role-authorized individual performance."/></Card>:!d?<Card><Empty title={q.isLoading?"Loading individual performance…":"No performance data"}/></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Completion" value={`${d.delivery.completionPercentage}%`} detail={`${d.delivery.completed}/${d.delivery.assigned} completed`} tone="emerald"/><Stat label="On time" value={`${d.delivery.onTimeCompletion}%`} detail={`${d.delivery.overdue} overdue`} tone="blue"/><Stat label="First pass" value={`${d.quality.firstPassAcceptance}%`} detail={`${d.quality.rejectionCount} rejected`} tone="violet"/><Stat label="Cycle time" value={`${d.flow.cycleTimeHours}h`} detail={`${d.flow.blockedTimeHours}h blocked`} tone="amber"/><Stat label="Velocity" value={d.sprint.velocity} detail={`${d.sprint.carryover} carry-over pts`} tone="teal"/></div>}</div>}
function ChartCard({title,description,children}:{title:string;description?:string;children:import("react").ReactElement}){return <Card><CardHeader title={title} description={description}/><div className="h-[360px] p-4"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></Card>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><b className="block text-lg">{value}</b><span className="text-[9px] font-black uppercase text-slate-400">{label}</span></div>}
function Metric({label,value,icon:Icon}:{label:string;value:string|number;icon:typeof Target}){return <div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</span><Icon className="h-4 w-4 text-blue-500"/></div><b className="mt-2 block text-2xl">{value}</b></div>}
function normalizeFlow(rows:Array<{_id:{status:string;day:string};count:number}>){const m=new Map<string,Record<string,string|number>>();for(const r of rows){const row=m.get(r._id.day)??{day:r._id.day};row[r._id.status]=r.count;m.set(r._id.day,row)}return [...m.values()].sort((a,b)=>String(a.day).localeCompare(String(b.day)))}
function flowKeys(rows:Array<Record<string,string|number>>){return [...new Set(rows.flatMap(r=>Object.keys(r).filter(k=>k!=='day')))]}
