"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ChevronDown, ChevronUp, Plus, Search, X } from "lucide-react";
import toast from "react-hot-toast";
import { getApiErrorMessage } from "@/src/lib/api/error";
import { useGetMeQuery } from "@/src/lib/features/auth/auth-api";
import { useBulkPMTasksMutation, useCreatePMSavedViewMutation, useGetPMProjectQuery, useGetPMReleasesQuery, useGetPMSavedViewsQuery, useGetPMSprintsQuery, useGetPMTasksQuery } from "@/src/lib/features/product-management/product-management-api";
import type { PMPriority, PMUser, PMWorkType } from "@/src/lib/features/product-management/product-management-types";
import { AsyncUserPicker, Card, Empty, Field, PageHeader, Pagination, PriorityBadge, StatusBadge, inputClass, primaryButton, secondaryButton, shortDate, userLabel } from "./pm-ui";
import { WorkItemDrawer } from "./work-item-drawer";

const priorities:PMPriority[]=["Low","Medium","High","Urgent","Critical"];
const types:PMWorkType[]=["Epic","Story","Task","Bug","Subtask"];

export function PMWorkItemsPage({projectId}:{projectId:string}){
  const router=useRouter(),sp=useSearchParams();
  const me=useGetMeQuery().data?.data;const canManage=!!me&&(me.role==="super-admin"||me.role==="product-admin"||(me.permissions??[]).includes("product-management.work.manage"));
  const projectQ=useGetPMProjectQuery(projectId),sprintsQ=useGetPMSprintsQuery(projectId),releasesQ=useGetPMReleasesQuery(projectId);
  const [search,setSearch]=useState(""),[debounced,setDebounced]=useState("");
  const [status,setStatus]=useState(""),[priority,setPriority]=useState(""),[type,setType]=useState(""),[sprintId,setSprint]=useState(""),[releaseId,setRelease]=useState("");
  const [assignee,setAssignee]=useState<PMUser|undefined>(),[reporter,setReporter]=useState<PMUser|undefined>(),[reviewer,setReviewer]=useState<PMUser|undefined>();
  const [epicId,setEpicId]=useState(""),[label,setLabel]=useState("");
  const [createdFrom,setCreatedFrom]=useState(""),[createdTo,setCreatedTo]=useState(""),[updatedFrom,setUpdatedFrom]=useState(""),[updatedTo,setUpdatedTo]=useState(""),[dueFrom,setDueFrom]=useState(""),[dueTo,setDueTo]=useState("");
  const [overdue,setOverdue]=useState(false),[blocked,setBlocked]=useState(false),[unassigned,setUnassigned]=useState(false),[archived,setArchived]=useState(false),[advanced,setAdvanced]=useState(false);
  const [sort,setSort]=useState("rank"),[order,setOrder]=useState("asc"),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([]);
  const [drawerTask,setDrawerTask]=useState(sp.get("task")??""),[newItem,setNewItem]=useState(sp.get("new")==="1");
  const statuses=projectQ.data?.data.workflow?.statuses??[];
  useEffect(()=>{const id=setTimeout(()=>{setDebounced(search.trim());setPage(1)},250);return()=>clearTimeout(id)},[search]);

  const q=useGetPMTasksQuery({projectId,search:debounced||undefined,status:status||undefined,priority:priority||undefined,type:type||undefined,sprintId:sprintId||undefined,releaseId:releaseId||undefined,assignee:assignee?._id,reporter:reporter?._id,reviewer:reviewer?._id,epicId:epicId||undefined,label:label.trim()||undefined,createdFrom:createdFrom||undefined,createdTo:createdTo||undefined,updatedFrom:updatedFrom||undefined,updatedTo:updatedTo||undefined,dueFrom:dueFrom||undefined,dueTo:dueTo||undefined,overdue:overdue||undefined,blocked:blocked||undefined,unassigned:unassigned||undefined,archived,page,limit:50,sort,order});
  const epicsQ=useGetPMTasksQuery({projectId,type:"Epic",archived:false,page:1,limit:100,sort:"rank",order:"asc"});
  const rows=q.data?.data??[],pg=q.data?.pagination;
  const [bulk,{isLoading:bulkLoading}]=useBulkPMTasksMutation();
  const savedQ=useGetPMSavedViewsQuery({scope:"tasks",projectId}),[saveView]=useCreatePMSavedViewMutation();

  const filters={search,status,priority,type,sprintId,releaseId,assignee:assignee?._id,reporter:reporter?._id,reviewer:reviewer?._id,epicId,label,createdFrom,createdTo,updatedFrom,updatedTo,dueFrom,dueTo,overdue,blocked,unassigned,archived,sort,order};
  const activeCount=[search,status,priority,type,sprintId,releaseId,assignee?._id,reporter?._id,reviewer?._id,epicId,label,createdFrom,createdTo,updatedFrom,updatedTo,dueFrom,dueTo,overdue,blocked,unassigned,archived].filter(Boolean).length;

  function clearFilters(){setSearch("");setStatus("");setPriority("");setType("");setSprint("");setRelease("");setAssignee(undefined);setReporter(undefined);setReviewer(undefined);setEpicId("");setLabel("");setCreatedFrom("");setCreatedTo("");setUpdatedFrom("");setUpdatedTo("");setDueFrom("");setDueTo("");setOverdue(false);setBlocked(false);setUnassigned(false);setArchived(false);setSort("rank");setOrder("asc");setPage(1)}
  async function doBulk(updates:Record<string,unknown>){try{await bulk({taskIds:selected,updates}).unwrap();toast.success(`${selected.length} work item${selected.length===1?"":"s"} updated`);setSelected([])}catch(e){toast.error(getApiErrorMessage(e))}}
  async function createSaved(){const name=prompt("Saved view name");if(!name)return;try{await saveView({projectId,scope:"tasks",name,filters,columns:["key","title","type","status","priority","assignee","reviewer","sprint","release","points","dueDate"],shared:false}).unwrap();toast.success("View saved")}catch(e){toast.error(getApiErrorMessage(e))}}
  function applySaved(v:Record<string,unknown>){setSearch(String(v.search??""));setStatus(String(v.status??""));setPriority(String(v.priority??""));setType(String(v.type??""));setSprint(String(v.sprintId??""));setRelease(String(v.releaseId??""));setEpicId(String(v.epicId??""));setLabel(String(v.label??""));setCreatedFrom(String(v.createdFrom??""));setCreatedTo(String(v.createdTo??""));setUpdatedFrom(String(v.updatedFrom??""));setUpdatedTo(String(v.updatedTo??""));setDueFrom(String(v.dueFrom??""));setDueTo(String(v.dueTo??""));setOverdue(Boolean(v.overdue));setBlocked(Boolean(v.blocked));setUnassigned(Boolean(v.unassigned));setArchived(Boolean(v.archived));setSort(String(v.sort??"rank"));setOrder(String(v.order??"asc"));setAssignee(v.assignee?{_id:String(v.assignee),email:"Selected assignee",role:""}:undefined);setReporter(v.reporter?{_id:String(v.reporter),email:"Selected reporter",role:""}:undefined);setReviewer(v.reviewer?{_id:String(v.reviewer),email:"Selected reviewer",role:""}:undefined);setAdvanced(true);setPage(1)}

  const allSelected=rows.length>0&&rows.every(r=>selected.includes(r._id));
  return <>
    <PageHeader eyebrow="Project / Work Items" title="All Work Items" description="Server-side advanced filters, saved views and bulk operations across Epics, Stories, Tasks, Bugs and Subtasks—with full detail, dependencies, estimates, review, work logs and audit history." actions={canManage?<button className={primaryButton} onClick={()=>setNewItem(true)}><Plus className="h-4 w-4"/>Create work item</button>:undefined}/>
    <Card className="mb-4 p-4">
      <div className="grid gap-3 xl:grid-cols-[1fr_repeat(5,150px)]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search key, title, description or label"/></div><select className={inputClass} value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All types</option>{types.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="">All priorities</option>{priorities.map(v=><option key={v}>{v}</option>)}</select><select className={inputClass} value={sprintId} onChange={e=>{setSprint(e.target.value);setPage(1)}}><option value="">All sprints</option>{(sprintsQ.data?.data??[]).map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select><select className={inputClass} value={releaseId} onChange={e=>{setRelease(e.target.value);setPage(1)}}><option value="">All releases</option>{(releasesQ.data?.data??[]).map(r=><option key={r._id} value={r._id}>{r.name}</option>)}</select></div>
      <div className="mt-3 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={overdue} onChange={e=>{setOverdue(e.target.checked);setPage(1)}}/>Overdue</label><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={blocked} onChange={e=>{setBlocked(e.target.checked);setPage(1)}}/>Blocked</label><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={unassigned} onChange={e=>{setUnassigned(e.target.checked);setPage(1)}}/>Unassigned</label><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setPage(1)}}/>Archived</label><button className="inline-flex items-center gap-1 text-xs font-black text-indigo-600" onClick={()=>setAdvanced(v=>!v)}>{advanced?<ChevronUp className="h-3.5 w-3.5"/>:<ChevronDown className="h-3.5 w-3.5"/>}Advanced filters</button>{activeCount>0&&<button className="text-xs font-black text-rose-600" onClick={clearFilters}>Clear {activeCount} filters</button>}<button className="text-xs font-black text-blue-600" onClick={()=>void createSaved()}>Save current view</button>{(savedQ.data?.data??[]).map(v=><button key={v._id} className="rounded-lg bg-violet-50 px-2 py-1 text-[10px] font-black text-violet-700" onClick={()=>applySaved(v.filters)}>{v.name}</button>)}</div>
      {advanced&&<div className="mt-4 border-t border-slate-100 pt-4"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FilterUser label="Assignee" value={assignee} projectId={projectId} onChange={setAssignee}/><FilterUser label="Reporter" value={reporter} projectId={projectId} onChange={setReporter}/><FilterUser label="Reviewer" value={reviewer} projectId={projectId} onChange={setReviewer}/><Field label="Epic"><select className={inputClass} value={epicId} onChange={e=>{setEpicId(e.target.value);setPage(1)}}><option value="">All epics</option>{(epicsQ.data?.data??[]).map(e=><option key={e._id} value={e._id}>{e.key} · {e.title}</option>)}</select></Field><Field label="Label"><input className={inputClass} value={label} onChange={e=>{setLabel(e.target.value);setPage(1)}} placeholder="Exact label"/></Field><Field label="Created from"><input type="date" className={inputClass} value={createdFrom} onChange={e=>{setCreatedFrom(e.target.value);setPage(1)}}/></Field><Field label="Created to"><input type="date" className={inputClass} value={createdTo} onChange={e=>{setCreatedTo(e.target.value);setPage(1)}}/></Field><Field label="Updated from"><input type="date" className={inputClass} value={updatedFrom} onChange={e=>{setUpdatedFrom(e.target.value);setPage(1)}}/></Field><Field label="Updated to"><input type="date" className={inputClass} value={updatedTo} onChange={e=>{setUpdatedTo(e.target.value);setPage(1)}}/></Field><Field label="Due from"><input type="date" className={inputClass} value={dueFrom} onChange={e=>{setDueFrom(e.target.value);setPage(1)}}/></Field><Field label="Due to"><input type="date" className={inputClass} value={dueTo} onChange={e=>{setDueTo(e.target.value);setPage(1)}}/></Field><Field label="Sort"><div className="grid grid-cols-2 gap-2"><select className={inputClass} value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="rank">Rank</option><option value="updated">Updated</option><option value="created">Created</option><option value="due">Due</option><option value="priority">Priority</option></select><select className={inputClass} value={order} onChange={e=>{setOrder(e.target.value);setPage(1)}}><option value="asc">Ascending</option><option value="desc">Descending</option></select></div></Field></div></div>}
    </Card>
    {canManage&&selected.length>0&&<BulkBar count={selected.length} projectId={projectId} statuses={statuses} sprints={sprintsQ.data?.data??[]} releases={releasesQ.data?.data??[]} loading={bulkLoading} onApply={doBulk} onClear={()=>setSelected([])}/>} 
    <Card>{rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[1320px] text-left text-xs"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-400"><tr><th className="px-4 py-3">{canManage&&<input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?selected.filter(id=>!rows.some(r=>r._id===id)):[...new Set([...selected,...rows.map(r=>r._id)])])}/>}</th><th className="px-4 py-3">Key / work</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Assignee</th><th className="px-4 py-3">Reviewer</th><th className="px-4 py-3">Points</th><th className="px-4 py-3">Sprint</th><th className="px-4 py-3">Release</th><th className="px-4 py-3">Due</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(t=><tr key={t._id} className="group hover:bg-slate-50"><td className="px-4 py-3">{canManage&&<input type="checkbox" checked={selected.includes(t._id)} onChange={()=>setSelected(v=>v.includes(t._id)?v.filter(x=>x!==t._id):[...v,t._id])}/>}</td><td className="max-w-md px-4 py-3"><button className="text-left" onClick={()=>setDrawerTask(t._id)}><b className="block text-slate-900 group-hover:text-blue-700">{t.key} · {t.title}</b><span className="mt-1 block truncate text-[10px] text-slate-400">{t.description||"No description"}</span></button></td><td className="px-4 py-3 font-bold text-slate-500">{t.type}</td><td className="px-4 py-3"><StatusBadge value={t.status}/></td><td className="px-4 py-3"><PriorityBadge value={t.priority}/></td><td className="px-4 py-3">{userLabel(t.assignee)}</td><td className="px-4 py-3">{userLabel(t.reviewer)}</td><td className="px-4 py-3 font-black">{t.storyPoints}</td><td className="px-4 py-3">{(sprintsQ.data?.data??[]).find(s=>s._id===t.sprintId)?.name??"Backlog"}</td><td className="px-4 py-3">{(releasesQ.data?.data??[]).find(r=>r._id===t.releaseId)?.name??"—"}</td><td className={`px-4 py-3 font-bold ${t.dueDate&&new Date(t.dueDate)<new Date()&&t.status!=="Done"?"text-rose-600":"text-slate-500"}`}>{shortDate(t.dueDate)}</td></tr>)}</tbody></table></div>:<Empty title="No work items" description="Create work, change filters, or restore archived items."/>}{pg&&<Pagination page={pg.page} totalPages={pg.totalPages} onPage={setPage}/>}</Card>
    <WorkItemDrawer projectId={projectId} taskId={drawerTask||undefined} newItem={newItem} onClose={()=>{setDrawerTask("");setNewItem(false);router.replace(`/product-management/projects/${projectId}/tasks`)}}/>
  </>;
}

function FilterUser({label,value,projectId,onChange}:{label:string;value?:PMUser;projectId:string;onChange:(v:PMUser|undefined)=>void}){return <Field label={label}><div className="flex gap-2"><div className="min-w-0 flex-1"><AsyncUserPicker projectId={projectId} value={value?._id} onChange={(_,u)=>{onChange(u);}} label={`All ${label.toLowerCase()}s`}/></div>{value&&<button className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={()=>onChange(undefined)} title={`Clear ${label}`}><X className="h-4 w-4"/></button>}</div></Field>}

function BulkBar({count,projectId,statuses,sprints,releases,loading,onApply,onClear}:{count:number;projectId:string;statuses:string[];sprints:Array<{_id:string;name:string}>;releases:Array<{_id:string;name:string}>;loading:boolean;onApply:(u:Record<string,unknown>)=>Promise<void>;onClear:()=>void}){
  const [action,setAction]=useState("status"),[value,setValue]=useState(""),[user,setUser]=useState<PMUser|undefined>();
  const render=action==="assignee"?<div className="min-w-64"><AsyncUserPicker projectId={projectId} value={user?._id} onChange={(_,u)=>setUser(u)} label="Bulk assignee"/></div>:action==="status"?<select className={`${inputClass} w-48`} value={value} onChange={e=>setValue(e.target.value)}><option value="">Select status</option>{statuses.map(v=><option key={v}>{v}</option>)}</select>:action==="priority"?<select className={`${inputClass} w-44`} value={value} onChange={e=>setValue(e.target.value)}><option value="">Select priority</option>{priorities.map(v=><option key={v}>{v}</option>)}</select>:action==="sprint"?<select className={`${inputClass} w-52`} value={value} onChange={e=>setValue(e.target.value)}><option value="">Move to backlog</option>{sprints.map(v=><option key={v._id} value={v._id}>{v.name}</option>)}</select>:action==="release"?<select className={`${inputClass} w-52`} value={value} onChange={e=>setValue(e.target.value)}><option value="">Remove release</option>{releases.map(v=><option key={v._id} value={v._id}>{v.name}</option>)}</select>:action==="label"?<input className={`${inputClass} w-52`} placeholder="Label" value={value} onChange={e=>setValue(e.target.value)}/>:<input type="date" className={`${inputClass} w-44`} value={value} onChange={e=>setValue(e.target.value)}/>;
  const apply=()=>{const val=action==="assignee"?user?._id??null:action==="sprint"||action==="release"?value||null:action==="dueDate"?value||null:value;if(action!=="assignee"&&!value&&!["sprint","release","dueDate"].includes(action))return;void onApply({[action==="sprint"?"sprintId":action==="release"?"releaseId":action==="label"?"addLabel":action]:val})};
  return <Card className="mb-4 border-blue-200 bg-blue-50/50 p-3"><div className="flex flex-wrap items-center gap-2"><b className="mr-2 text-xs text-blue-800">{count} selected</b><select className={`${inputClass} w-44`} value={action} onChange={e=>{setAction(e.target.value);setValue("");setUser(undefined)}}><option value="status">Status</option><option value="assignee">Assignee</option><option value="priority">Priority</option><option value="sprint">Sprint</option><option value="release">Release</option><option value="label">Label</option><option value="dueDate">Due date</option></select>{render}<button className={primaryButton} disabled={loading||(action==="assignee"&&!user)} onClick={apply}>Apply</button><button className={secondaryButton} onClick={onClear}><X className="h-4 w-4"/>Clear</button></div></Card>;
}
