import { baseApi } from "@/src/lib/api/base-api";
import type { ApplicationStatus } from "../job-applications/job-application-types";
import type { ExternalApplication, ExternalListQuery, ExternalSource } from "./external-application-types";
export const externalApplicationApi=baseApi.injectEndpoints({endpoints:(b)=>({
 listExternalApplications:b.query<{success:boolean;data:ExternalApplication[];columns:string[];pagination:{page:number;limit:number;total:number;totalPages:number}},ExternalListQuery|void>({query:(params)=>({url:"/external-applications",params:params||undefined}),providesTags:[{type:"ExternalApplication",id:"LIST"}]}),
 createExternalApplication:b.mutation<{success:boolean;data:ExternalApplication},{fields:Record<string,string>;sourceLabel?:string}>({query:(body)=>({url:"/external-applications/manual",method:"POST",body}),invalidatesTags:[{type:"ExternalApplication",id:"LIST"}]}),
 importExternalApplications:b.mutation<{success:boolean;data:{imported:number;columns:string[]}},{source:Exclude<ExternalSource,"Manual">;file?:File;sheetUrl?:string;sourceLabel?:string}>({query:(input)=>{const body=new FormData();body.set("source",input.source);if(input.sheetUrl)body.set("sheetUrl",input.sheetUrl);if(input.sourceLabel)body.set("sourceLabel",input.sourceLabel);if(input.file)body.set("file",input.file);return{url:"/external-applications/import",method:"POST",body}},invalidatesTags:[{type:"ExternalApplication",id:"LIST"}]}),
 bulkExternalStatus:b.mutation<{success:boolean;data:{matched:number;updated:number;email:{attempted:number;sent:number;skipped:number;failed:number;noEmail:number}}},{ids:string[];status:ApplicationStatus}>({query:(body)=>({url:"/external-applications/bulk-status",method:"PATCH",body}),invalidatesTags:[{type:"ExternalApplication",id:"LIST"}]}),
 releaseExternalDocuments:b.mutation<{success:boolean;data:{released:number;failed:number;emailFailed:number}},{applicationIds:string[];templateId:string;sendEmail:boolean}>({query:(body)=>({url:"/external-applications/release-documents",method:"POST",body})}),
})});
export const {useListExternalApplicationsQuery,useCreateExternalApplicationMutation,useImportExternalApplicationsMutation,useBulkExternalStatusMutation,useReleaseExternalDocumentsMutation}=externalApplicationApi;
