import {baseApi} from '@/src/lib/api/base-api';
import type {PMActivityEntry,PMComment,PMConversation,PMDelivery,PMMessage,PMMilestone,PMNotification,PMOverview,PMPerformance,PMProject,PMProjectDetail,PMProjectMember,PMRelease,PMReport,PMSavedView,PMSprint,PMSprintSummary,PMTask,PMUser,PMWorklog} from './product-management-types';
type E<T>={success:boolean;data:T};type P<T>={success:boolean;data:T[];pagination:{page:number;limit:number;total:number;totalPages:number}};
export const productManagementApi=baseApi.injectEndpoints({endpoints:b=>({
  getPMOverview:b.query<E<PMOverview>,void>({query:()=>'/product-management/overview',providesTags:['ProductOverview']}),
  getPMProjects:b.query<P<PMProject>,{query?:string;type?:string;visibility?:string;risk?:string;page?:number;limit?:number;archived?:boolean}|void>({query:params=>({url:'/product-management/projects',params:params||{}}),providesTags:[{type:'ProductProject',id:'LIST'}]}),
  getPMProject:b.query<E<PMProjectDetail>,string>({query:id=>`/product-management/projects/${id}`,providesTags:(_r,_e,id)=>[{type:'ProductProject',id}]}),
  createPMProject:b.mutation<E<PMProject>,Record<string,unknown>>({query:body=>({url:'/product-management/projects',method:'POST',body}),invalidatesTags:[{type:'ProductProject',id:'LIST'},'ProductOverview']}),
  updatePMProject:b.mutation<E<PMProject>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/projects/${id}`,method:'PATCH',body}),invalidatesTags:(_r,_e,a)=>[{type:'ProductProject',id:a.id},{type:'ProductProject',id:'LIST'},'ProductOverview','ProductTimeline']}),
  archivePMProject:b.mutation<E<PMProject>,{id:string;archive:boolean}>({query:({id,archive})=>({url:`/product-management/projects/${id}/archive`,method:'POST',body:{archive}}),invalidatesTags:[{type:'ProductProject',id:'LIST'},'ProductOverview']}),
  searchPMUsers:b.query<P<PMUser>,{query?:string;projectId?:string;includeClients?:boolean;page?:number;limit?:number}>({query:params=>({url:'/product-management/users/search',params}),providesTags:['ProductUsers']}),

  getPMSprints:b.query<E<PMSprint[]>,string>({query:projectId=>({url:'/product-management/sprints',params:{projectId}}),providesTags:[{type:'ProductSprint',id:'LIST'}]}),
  getPMSprintSummary:b.query<E<PMSprintSummary>,string>({query:id=>`/product-management/sprints/${id}/summary`,providesTags:[{type:'ProductSprint',id:'LIST'},{type:'ProductTask',id:'LIST'}]}),
  createPMSprint:b.mutation<E<PMSprint>,Record<string,unknown>>({query:body=>({url:'/product-management/sprints',method:'POST',body}),invalidatesTags:[{type:'ProductSprint',id:'LIST'},'ProductOverview']}),
  updatePMSprint:b.mutation<E<PMSprint>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/sprints/${id}`,method:'PATCH',body}),invalidatesTags:[{type:'ProductSprint',id:'LIST'},{type:'ProductTask',id:'LIST'},'ProductOverview']}),
  startPMSprint:b.mutation<E<PMSprint>,string>({query:id=>({url:`/product-management/sprints/${id}/start`,method:'POST'}),invalidatesTags:[{type:'ProductSprint',id:'LIST'},'ProductOverview']}),
  completePMSprint:b.mutation<E<PMSprint>,{id:string;destinationSprintId?:string}>({query:({id,...body})=>({url:`/product-management/sprints/${id}/complete`,method:'POST',body}),invalidatesTags:[{type:'ProductSprint',id:'LIST'},{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),

  getPMTasks:b.query<P<PMTask>,Record<string,string|number|boolean|undefined>>({query:params=>({url:'/product-management/tasks',params}),providesTags:[{type:'ProductTask',id:'LIST'}]}),
  getPMTask:b.query<E<PMTask>,string>({query:id=>`/product-management/tasks/${id}`,providesTags:(_r,_e,id)=>[{type:'ProductTask',id}]}),
  createPMTask:b.mutation<E<PMTask>,Record<string,unknown>>({query:body=>({url:'/product-management/tasks',method:'POST',body}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  updatePMTask:b.mutation<E<PMTask>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/tasks/${id}`,method:'PATCH',body}),invalidatesTags:(_r,_e,a)=>[{type:'ProductTask',id:a.id},{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport','ProductTimeline']}),
  transitionPMTask:b.mutation<E<PMTask>,{id:string;status:string;comment?:string}>({query:({id,...body})=>({url:`/product-management/tasks/${id}/transition`,method:'POST',body}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  duplicatePMTask:b.mutation<E<PMTask>,{id:string;body?:Record<string,unknown>}>({query:({id,body={}})=>({url:`/product-management/tasks/${id}/duplicate`,method:'POST',body}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview']}),
  movePMTask:b.mutation<E<PMTask>,{id:string;projectId:string}>({query:({id,projectId})=>({url:`/product-management/tasks/${id}/move`,method:'POST',body:{projectId}}),invalidatesTags:[{type:'ProductTask',id:'LIST'},{type:'ProductProject',id:'LIST'},'ProductOverview','ProductTimeline','ProductRelease','ProductActivity']}),
  addPMDependency:b.mutation<E<PMTask>,{id:string;type:'depends-on'|'blocks'|'relates-to';targetTaskId:string}>({query:({id,...body})=>({url:`/product-management/tasks/${id}/dependencies`,method:'POST',body}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductTimeline']}),
  reorderPMTasks:b.mutation<E<{updated:number}>,{projectId:string;orderedTaskIds:string[]}>({query:({projectId,...body})=>({url:'/product-management/tasks/reorder',method:'POST',params:{projectId},body}),invalidatesTags:[{type:'ProductTask',id:'LIST'}]}),
  archivePMTask:b.mutation<E<PMTask>,{id:string;archive:boolean}>({query:({id,archive})=>({url:`/product-management/tasks/${id}/archive`,method:'POST',body:{archive}}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  reopenPMTask:b.mutation<E<PMTask>,string>({query:id=>({url:`/product-management/tasks/${id}/reopen`,method:'POST'}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  deletePMTask:b.mutation<{success:boolean;message:string},string>({query:id=>({url:`/product-management/tasks/${id}`,method:'DELETE'}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  addPMTaskAttachments:b.mutation<E<PMTask>,{id:string;files:File[]}>({query:({id,files})=>{const body=new FormData();files.forEach(file=>body.append('attachments',file));return{url:`/product-management/tasks/${id}/attachments`,method:'POST',body}},invalidatesTags:(_r,_e,a)=>[{type:'ProductTask',id:a.id},{type:'ProductTask',id:'LIST'}]}),
  removePMTaskAttachment:b.mutation<E<PMTask>,{id:string;storageKey:string}>({query:({id,storageKey})=>({url:`/product-management/tasks/${id}/attachments`,method:'DELETE',params:{storageKey}}),invalidatesTags:(_r,_e,a)=>[{type:'ProductTask',id:a.id},{type:'ProductTask',id:'LIST'}]}),
  submitPMTask:b.mutation<E<PMTask>,string>({query:id=>({url:`/product-management/tasks/${id}/submit`,method:'POST'}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview']}),
  acceptPMTask:b.mutation<E<PMTask>,string>({query:id=>({url:`/product-management/tasks/${id}/accept`,method:'POST'}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  rejectPMTask:b.mutation<E<PMTask>,{id:string;reason:string}>({query:({id,reason})=>({url:`/product-management/tasks/${id}/reject`,method:'POST',body:{reason}}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  bulkPMTasks:b.mutation<E<{updated:number}>,{taskIds:string[];updates:Record<string,unknown>}>({query:body=>({url:'/product-management/tasks/bulk',method:'POST',body}),invalidatesTags:[{type:'ProductTask',id:'LIST'},'ProductOverview','ProductReport']}),
  getPMMyWork:b.query<P<PMTask>,Record<string,string|number|boolean|undefined>>({query:params=>({url:'/product-management/my-work',params}),providesTags:[{type:'ProductTask',id:'MY'}]}),

  getPMComments:b.query<P<PMComment>,{taskId:string;page?:number;limit?:number}>({query:({taskId,...params})=>({url:`/product-management/tasks/${taskId}/comments`,params}),providesTags:['ProductActivity']}),
  createPMComment:b.mutation<E<PMComment>,{taskId:string;text:string}>({query:({taskId,...body})=>({url:`/product-management/tasks/${taskId}/comments`,method:'POST',body}),invalidatesTags:['ProductActivity','ProductNotification']}),
  updatePMComment:b.mutation<E<PMComment>,{id:string;text:string}>({query:({id,...body})=>({url:`/product-management/comments/${id}`,method:'PATCH',body}),invalidatesTags:['ProductActivity']}),
  deletePMComment:b.mutation<E<PMComment>,string>({query:id=>({url:`/product-management/comments/${id}`,method:'DELETE'}),invalidatesTags:['ProductActivity']}),
  getPMWorklogs:b.query<P<PMWorklog>,{taskId:string;page?:number;limit?:number}>({query:({taskId,...params})=>({url:`/product-management/tasks/${taskId}/worklogs`,params}),providesTags:['ProductActivity']}),
  createPMWorklog:b.mutation<E<PMWorklog>,{taskId:string;minutes:number;note?:string;workDate?:string;remainingEstimate?:number}>({query:({taskId,...body})=>({url:`/product-management/tasks/${taskId}/worklogs`,method:'POST',body}),invalidatesTags:['ProductActivity','ProductReport']}),
  updatePMWorklog:b.mutation<E<PMWorklog>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/worklogs/${id}`,method:'PATCH',body}),invalidatesTags:['ProductActivity','ProductReport']}),
  deletePMWorklog:b.mutation<E<{deleted:boolean}>,string>({query:id=>({url:`/product-management/worklogs/${id}`,method:'DELETE'}),invalidatesTags:['ProductActivity','ProductReport']}),

  getPMTimeline:b.query<E<{tasks:PMTask[];releases:PMRelease[];milestones:PMMilestone[]}>,string>({query:projectId=>({url:'/product-management/timeline',params:{projectId}}),providesTags:['ProductTimeline']}),
  getPMMilestones:b.query<E<PMMilestone[]>,string>({query:projectId=>({url:'/product-management/milestones',params:{projectId}}),providesTags:['ProductTimeline']}),
  createPMMilestone:b.mutation<E<PMMilestone>,Record<string,unknown>>({query:body=>({url:'/product-management/milestones',method:'POST',body}),invalidatesTags:['ProductTimeline']}),
  updatePMMilestone:b.mutation<E<PMMilestone>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/milestones/${id}`,method:'PATCH',body}),invalidatesTags:['ProductTimeline']}),
  deletePMMilestone:b.mutation<E<{deleted:boolean}>,string>({query:id=>({url:`/product-management/milestones/${id}`,method:'DELETE'}),invalidatesTags:['ProductTimeline']}),

  getPMReleases:b.query<E<PMRelease[]>,string>({query:projectId=>({url:'/product-management/releases',params:{projectId}}),providesTags:[{type:'ProductRelease',id:'LIST'}]}),
  createPMRelease:b.mutation<E<PMRelease>,Record<string,unknown>>({query:body=>({url:'/product-management/releases',method:'POST',body}),invalidatesTags:[{type:'ProductRelease',id:'LIST'},'ProductTimeline','ProductOverview']}),
  updatePMRelease:b.mutation<E<PMRelease>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/releases/${id}`,method:'PATCH',body}),invalidatesTags:[{type:'ProductRelease',id:'LIST'},'ProductTimeline','ProductOverview','ProductReport']}),
  transitionPMRelease:b.mutation<E<PMRelease>,{id:string;status:string;note?:string;force?:boolean}>({query:({id,...body})=>({url:`/product-management/releases/${id}/transition`,method:'POST',body}),invalidatesTags:[{type:'ProductRelease',id:'LIST'},'ProductTimeline','ProductOverview','ProductReport']}),
  getPMReleaseReadiness:b.query<E<{checks:Record<string,boolean>;ready:boolean}>,string>({query:id=>`/product-management/releases/${id}/readiness`,providesTags:[{type:'ProductRelease',id:'LIST'}]}),
  decidePMRelease:b.mutation<E<PMRelease>,{id:string;decision:'approved'|'rejected';note?:string}>({query:({id,...body})=>({url:`/product-management/releases/${id}/decision`,method:'POST',body}),invalidatesTags:[{type:'ProductRelease',id:'LIST'},'ProductOverview','ProductReport']}),
  getPMDeliveries:b.query<E<PMDelivery[]>,string>({query:projectId=>({url:'/product-management/deliveries',params:{projectId}}),providesTags:[{type:'ProductDelivery',id:'LIST'}]}),
  createPMDelivery:b.mutation<E<PMDelivery>,Record<string,unknown>>({query:body=>({url:'/product-management/deliveries',method:'POST',body}),invalidatesTags:[{type:'ProductDelivery',id:'LIST'},'ProductOverview','ProductReport']}),
  updatePMDelivery:b.mutation<E<PMDelivery>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/deliveries/${id}`,method:'PATCH',body}),invalidatesTags:[{type:'ProductDelivery',id:'LIST'},'ProductOverview','ProductReport']}),
  decidePMDelivery:b.mutation<E<PMDelivery>,{id:string;decision:'approved'|'rejected'|'changes-requested';reason?:string}>({query:({id,...body})=>({url:`/product-management/deliveries/${id}/decision`,method:'POST',body}),invalidatesTags:[{type:'ProductDelivery',id:'LIST'},'ProductOverview','ProductReport']}),

  getPMTeam:b.query<E<PMProjectMember[]>,string>({query:projectId=>({url:'/product-management/team',params:{projectId}}),providesTags:['ProductUsers']}),
  getPMGlobalTeam:b.query<E<Array<Record<string,unknown>>>,void>({query:()=>'/product-management/team/global',providesTags:['ProductUsers']}),
  addPMTeamMembers:b.mutation<E<PMProjectMember[]>,{projectId:string;body:Record<string,unknown>}>({query:({projectId,body})=>({url:`/product-management/projects/${projectId}/team`,method:'POST',body}),invalidatesTags:['ProductUsers',{type:'ProductProject',id:'LIST'}]}),
  updatePMTeamMember:b.mutation<E<PMProjectMember>,{projectId:string;userId:string;body:Record<string,unknown>}>({query:({projectId,userId,body})=>({url:`/product-management/projects/${projectId}/team/${userId}`,method:'PATCH',body}),invalidatesTags:['ProductUsers']}),
  removePMTeamMember:b.mutation<E<{removed:boolean}>,{projectId:string;userId:string}>({query:({projectId,userId})=>({url:`/product-management/projects/${projectId}/team/${userId}`,method:'DELETE'}),invalidatesTags:['ProductUsers',{type:'ProductProject',id:'LIST'}]}),
  getPMSavedViews:b.query<E<PMSavedView[]>,{scope?:string;projectId?:string}|void>({query:params=>({url:'/product-management/saved-views',params:params||{}}),providesTags:['ProductUsers']}),
  createPMSavedView:b.mutation<E<PMSavedView>,Record<string,unknown>>({query:body=>({url:'/product-management/saved-views',method:'POST',body}),invalidatesTags:['ProductUsers']}),
  updatePMSavedView:b.mutation<E<PMSavedView>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/saved-views/${id}`,method:'PATCH',body}),invalidatesTags:['ProductUsers']}),
  deletePMSavedView:b.mutation<E<{deleted:boolean}>,string>({query:id=>({url:`/product-management/saved-views/${id}`,method:'DELETE'}),invalidatesTags:['ProductUsers']}),

  getPMReport:b.query<E<PMReport>,string>({query:projectId=>({url:'/product-management/reports',params:{projectId}}),providesTags:['ProductReport']}),
  getPMPerformance:b.query<E<PMPerformance>,{projectId?:string;userId?:string;from?:string;to?:string}|void>({query:params=>({url:'/product-management/performance',params:params||{}}),providesTags:['ProductReport']}),
  getPMActivity:b.query<P<PMActivityEntry>,{projectId?:string;entityType?:string;entityId?:string;action?:string;page?:number;limit?:number}>({query:params=>({url:'/product-management/activity',params}),providesTags:['ProductActivity']}),
  globalPMSearch:b.query<E<{projects:PMProject[];tasks:PMTask[];releases:PMRelease[]}>,string>({query:query=>({url:'/product-management/search',params:{query,limit:12}})}),
  getPMNotifications:b.query<E<PMNotification[]>,void>({query:()=>'/product-management/notifications',providesTags:['ProductNotification']}),
  readPMNotification:b.mutation<E<PMNotification>,string>({query:id=>({url:`/product-management/notifications/${id}/read`,method:'PATCH'}),invalidatesTags:['ProductNotification']}),
  readAllPMNotifications:b.mutation<E<{updated:number}>,void>({query:()=>({url:'/product-management/notifications/read-all',method:'PATCH'}),invalidatesTags:['ProductNotification']}),

  getPMConversations:b.query<E<PMConversation[]>,void>({query:()=>'/product-management/chat/conversations',providesTags:[{type:'ProductChat',id:'LIST'}]}),
  createPMConversation:b.mutation<E<PMConversation>,{type:'direct'|'group';name?:string;memberIds:string[]}>({query:body=>({url:'/product-management/chat/conversations',method:'POST',body}),invalidatesTags:[{type:'ProductChat',id:'LIST'}]}),
  updatePMConversation:b.mutation<E<PMConversation>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/product-management/chat/conversations/${id}`,method:'PATCH',body}),invalidatesTags:[{type:'ProductChat',id:'LIST'}]}),
  leavePMConversation:b.mutation<E<{left:boolean}>,string>({query:id=>({url:`/product-management/chat/conversations/${id}/leave`,method:'POST'}),invalidatesTags:[{type:'ProductChat',id:'LIST'}]}),
  getPMMessages:b.query<P<PMMessage>,{conversationId:string;page?:number;limit?:number}>({query:({conversationId,...params})=>({url:`/product-management/chat/conversations/${conversationId}/messages`,params}),providesTags:[{type:'ProductChat',id:'MESSAGES'}]}),
  searchPMMessages:b.query<P<PMMessage>,{query:string;conversationId?:string;page?:number;limit?:number}>({query:params=>({url:'/product-management/chat/messages/search',params})}),
  sendPMMessage:b.mutation<E<PMMessage>,{conversationId:string;text:string;replyTo?:string}>({query:({conversationId,...body})=>({url:`/product-management/chat/conversations/${conversationId}/messages`,method:'POST',body}),invalidatesTags:[{type:'ProductChat',id:'MESSAGES'},{type:'ProductChat',id:'LIST'}]}),
  readPMConversation:b.mutation<E<{readAt:string}>,{conversationId:string;messageId?:string}>({query:({conversationId,...body})=>({url:`/product-management/chat/conversations/${conversationId}/read`,method:'PATCH',body}),invalidatesTags:[{type:'ProductChat',id:'LIST'}]}),
})});
export const {
  useGetPMOverviewQuery,useGetPMProjectsQuery,useLazyGetPMProjectsQuery,useGetPMProjectQuery,useCreatePMProjectMutation,useUpdatePMProjectMutation,useArchivePMProjectMutation,useSearchPMUsersQuery,useLazySearchPMUsersQuery,
  useGetPMSprintsQuery,useGetPMSprintSummaryQuery,useCreatePMSprintMutation,useUpdatePMSprintMutation,useStartPMSprintMutation,useCompletePMSprintMutation,
  useGetPMTasksQuery,useLazyGetPMTasksQuery,useGetPMTaskQuery,useLazyGetPMTaskQuery,useCreatePMTaskMutation,useUpdatePMTaskMutation,useTransitionPMTaskMutation,useDuplicatePMTaskMutation,useMovePMTaskMutation,useAddPMDependencyMutation,useReorderPMTasksMutation,useArchivePMTaskMutation,useReopenPMTaskMutation,useDeletePMTaskMutation,useAddPMTaskAttachmentsMutation,useRemovePMTaskAttachmentMutation,useSubmitPMTaskMutation,useAcceptPMTaskMutation,useRejectPMTaskMutation,useBulkPMTasksMutation,useGetPMMyWorkQuery,
  useGetPMCommentsQuery,useCreatePMCommentMutation,useUpdatePMCommentMutation,useDeletePMCommentMutation,useGetPMWorklogsQuery,useCreatePMWorklogMutation,useUpdatePMWorklogMutation,useDeletePMWorklogMutation,
  useGetPMTimelineQuery,useGetPMMilestonesQuery,useCreatePMMilestoneMutation,useUpdatePMMilestoneMutation,useDeletePMMilestoneMutation,
  useGetPMReleasesQuery,useCreatePMReleaseMutation,useUpdatePMReleaseMutation,useTransitionPMReleaseMutation,useGetPMReleaseReadinessQuery,useDecidePMReleaseMutation,useGetPMDeliveriesQuery,useCreatePMDeliveryMutation,useUpdatePMDeliveryMutation,useDecidePMDeliveryMutation,
  useGetPMTeamQuery,useGetPMGlobalTeamQuery,useAddPMTeamMembersMutation,useUpdatePMTeamMemberMutation,useRemovePMTeamMemberMutation,useGetPMSavedViewsQuery,useCreatePMSavedViewMutation,useUpdatePMSavedViewMutation,useDeletePMSavedViewMutation,
  useGetPMReportQuery,useGetPMPerformanceQuery,useGetPMActivityQuery,useLazyGlobalPMSearchQuery,useGetPMNotificationsQuery,useReadPMNotificationMutation,useReadAllPMNotificationsMutation,
  useGetPMConversationsQuery,useCreatePMConversationMutation,useUpdatePMConversationMutation,useLeavePMConversationMutation,useGetPMMessagesQuery,useLazyGetPMMessagesQuery,useLazySearchPMMessagesQuery,useSendPMMessageMutation,useReadPMConversationMutation,
}=productManagementApi;
