"use client";
import Image from "next/image";
import Link from "next/link";
import { BookOpen, ExternalLink, GraduationCap } from "lucide-react";
import { useGetCoursesQuery } from "@/src/features/course/api/courseApi";

export default function CoursesPage() {
  const { data, isLoading, error } = useGetCoursesQuery({ status: "active", limit: 100 });
  const courses = data?.data ?? [];
  return <section className="space-y-7">
    <div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-cyan-300">Learning workspace</p><h1 className="mt-3 text-4xl font-black tracking-tight">My <span className="text-cyan-300">courses.</span></h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Access available QuantumFinix learning programs and continue building practical technology skills.</p></div>
    {isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item)=><div key={item} className="h-72 animate-pulse rounded-3xl border border-white/10 bg-white/[0.04]" />)}</div> : error ? <div className="rounded-3xl border border-red-400/20 bg-red-400/[0.06] p-6 text-sm text-red-200">Courses could not be loaded right now.</div> : courses.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map((course)=><article key={course._id} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035] shadow-2xl"><div className="relative aspect-[16/9] bg-slate-900">{course.bannerImage?.url ? <Image src={course.bannerImage.url} alt={course.bannerImage.altText || course.bannerImage.title || course.title} fill className="object-cover" /> : <div className="grid h-full place-items-center"><GraduationCap className="h-12 w-12 text-cyan-300/60" /></div>}</div><div className="p-6"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">{course.category}</p><h2 className="mt-3 text-xl font-black text-white">{course.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-400">{course.shortDescription}</p><div className="mt-5 flex gap-3"><Link href={`/course/${course.slug}`} className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-cyan-300 to-blue-500 px-5 py-2.5 text-sm font-black text-[#020711]"><BookOpen size={16}/>Open course</Link>{course.purchaseUrl ? <a href={course.purchaseUrl} target="_blank" rel="noreferrer" className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-slate-300"><ExternalLink size={16}/></a> : null}</div></div></article>)}</div> : <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-10 text-center"><BookOpen className="mx-auto h-12 w-12 text-cyan-300/60"/><h2 className="mt-4 text-xl font-black">No active courses yet</h2><p className="mt-2 text-sm text-slate-400">New learning programs will appear here when published.</p><Link href="/course" className="mt-6 inline-flex rounded-full border border-cyan-300/30 px-5 py-2.5 text-sm font-bold text-cyan-200">Explore course catalogue</Link></div>}
  </section>;
}
