import {baseApi} from "@/src/lib/api/base-api";import type{DevMessage,DevProject,DevReport,DevSprint,DevTask,LeaderboardRow}from"./developer-types";
type E<T>={success:boolean;data:T};
export const developerApi=baseApi.injectEndpoints({endpoints:(b)=>({
 getDevProjects:b.query<E<DevProject[]>,void>({query:()=>"/developer/projects",providesTags:[{type:"DeveloperProject",id:"LIST"}]}),
 createDevProject:b.mutation<E<DevProject>,{key:string;name:string;description?:string;lead?:string;members?:string[]}>({query:(body)=>({url:"/developer/projects",method:"POST",body}),invalidatesTags:[{type:"DeveloperProject",id:"LIST"}]}),
 updateDevProject:b.mutation<E<DevProject>,{id:string;body:{name?:string;description?:string;lead?:string;members?:string[]}}>({query:({id,body})=>({url:`/developer/projects/${id}`,method:"PATCH",body}),invalidatesTags:[{type:"DeveloperProject",id:"LIST"}]}),
 getDevSprints:b.query<E<DevSprint[]>,string>({query:(projectId)=>({url:"/developer/sprints",params:{projectId}}),providesTags:[{type:"DeveloperTask",id:"SPRINTS"}]}),
 createDevSprint:b.mutation<E<DevSprint>,{projectId:string;name:string;goal?:string;startDate?:string;endDate?:string}>({query:(body)=>({url:"/developer/sprints",method:"POST",body}),invalidatesTags:[{type:"DeveloperTask",id:"SPRINTS"}]}),
 updateDevSprint:b.mutation<E<DevSprint>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/developer/sprints/${id}`,method:"PATCH",body}),invalidatesTags:[{type:"DeveloperTask",id:"SPRINTS"}]}),
 getDevTasks:b.query<{success:boolean;data:DevTask[];pagination:{total:number}},Record<string,string|number|undefined>>({query:(params)=>({url:"/developer/tasks",params}),providesTags:[{type:"DeveloperTask",id:"LIST"}]}),
 createDevTask:b.mutation<E<DevTask>,Record<string,unknown>>({query:(body)=>({url:"/developer/tasks",method:"POST",body}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},"Workspace"]}),
 updateDevTask:b.mutation<E<DevTask>,{id:string;body:Record<string,unknown>}>({query:({id,body})=>({url:`/developer/tasks/${id}`,method:"PATCH",body}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},"Workspace"]}),
 submitDevTask:b.mutation<E<DevTask>,string>({query:(id)=>({url:`/developer/tasks/${id}/submit`,method:"POST"}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},"Workspace"]}),
 acceptDevTask:b.mutation<E<DevTask>,string>({query:(id)=>({url:`/developer/tasks/${id}/accept`,method:"POST"}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},{type:"DeveloperTask",id:"REPORT"},{type:"DeveloperTask",id:"LEADERBOARD"},"Workspace"]}),
 rejectDevTask:b.mutation<E<DevTask>,{id:string;reason:string}>({query:({id,reason})=>({url:`/developer/tasks/${id}/reject`,method:"POST",body:{reason}}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},"Workspace"]}),
 deleteDevTask:b.mutation<{success:boolean;message:string},string>({query:(id)=>({url:`/developer/tasks/${id}`,method:"DELETE"}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"},{type:"DeveloperTask",id:"REPORT"},{type:"DeveloperTask",id:"LEADERBOARD"},"Workspace"]}),
 addDevTaskAttachments:b.mutation<E<DevTask>,{id:string;attachments:File[]}>({query:({id,attachments})=>{const body=new FormData();attachments.forEach(f=>body.append("attachments",f));return{url:`/developer/tasks/${id}/attachments`,method:"POST",body}},invalidatesTags:[{type:"DeveloperTask",id:"LIST"}]}),
 removeDevTaskAttachment:b.mutation<E<DevTask>,{id:string;storageKey:string}>({query:({id,storageKey})=>({url:`/developer/tasks/${id}/attachments`,method:"DELETE",params:{storageKey}}),invalidatesTags:[{type:"DeveloperTask",id:"LIST"}]}),
 getDevMessages:b.query<{success:boolean;data:DevMessage[]},{projectId:string;taskId?:string}>({query:(params)=>({url:"/developer/messages",params}),providesTags:[{type:"DeveloperMessage",id:"LIST"}]}),
 sendDevMessage:b.mutation<E<DevMessage>,{projectId:string;taskId?:string;text?:string;attachments?:File[]}>({query:(input)=>{const body=new FormData();body.set("projectId",input.projectId);if(input.taskId)body.set("taskId",input.taskId);if(input.text)body.set("text",input.text);input.attachments?.forEach(f=>body.append("attachments",f));return{url:"/developer/messages",method:"POST",body}},invalidatesTags:[{type:"DeveloperMessage",id:"LIST"}]}),
 getDevLeaderboard:b.query<E<LeaderboardRow[]>,string|void>({query:(projectId)=>({url:"/developer/leaderboard",params:projectId?{projectId}:undefined}),providesTags:[{type:"DeveloperTask",id:"LEADERBOARD"}]}),
 getDevReport:b.query<E<DevReport>,string|void>({query:(projectId)=>({url:"/developer/reports",params:projectId?{projectId}:undefined}),providesTags:[{type:"DeveloperTask",id:"REPORT"}]}),
 getMyDevPerformance:b.query<E<{assigned:number;done:number;inReview:number;points:number;overdue:number}>,void>({query:()=>"/developer/me/performance",providesTags:[{type:"DeveloperTask",id:"ME"}]}),
 getDevNotifications:b.query<E<Array<{_id:string;type:string;title:string;message:string;readAt?:string;createdAt:string}>>,void>({query:()=>"/developer/notifications",providesTags:[{type:"DeveloperNotification",id:"LIST"}]}),
 markDevNotificationRead:b.mutation<E<{_id:string;readAt?:string}>,string>({query:(id)=>({url:`/developer/notifications/${id}/read`,method:"PATCH"}),invalidatesTags:[{type:"DeveloperNotification",id:"LIST"},"Workspace"]}),
})});
export const{useGetDevProjectsQuery,useCreateDevProjectMutation,useUpdateDevProjectMutation,useGetDevSprintsQuery,useCreateDevSprintMutation,useUpdateDevSprintMutation,useGetDevTasksQuery,useCreateDevTaskMutation,useUpdateDevTaskMutation,useSubmitDevTaskMutation,useAcceptDevTaskMutation,useRejectDevTaskMutation,useDeleteDevTaskMutation,useAddDevTaskAttachmentsMutation,useRemoveDevTaskAttachmentMutation,useGetDevMessagesQuery,useSendDevMessageMutation,useGetDevLeaderboardQuery,useGetDevReportQuery,useGetMyDevPerformanceQuery,useGetDevNotificationsQuery,useMarkDevNotificationReadMutation}=developerApi;
